### ISSUE TITLE
Block placer with custom block

### ISSUE THREAD

**Issue by Ielelele29** [xenondevs/Nova#10]
**Describe the bug**
If you put in a block placer multiple custom blocks if places it twice and when you break it, remain the texture without hitbox

**To Reproduce**
1. Put 2 or more custom blocks of the same tipe in a block placer
2. Break it in any way

**Expected behavior**
A normal placement

**Errors**
There isn't any arror in console

**Screenshots**
![2021-07-08_01 21 38](https://user-images.githubusercontent.com/76882886/124840289-ebd4ba00-df8a-11eb-8b97-341f5bed01dc.png)

**Comment by NichtStudioCode** [comment]
Thanks for reporting!
