### ISSUE TITLE
[Bug]Power Cell Repairing Items, Removes Enchantments 

### ISSUE THREAD

**Issue by ktkus** [xenondevs/Nova#100]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Other plugins

This bug also occurs when no other plugins are present.

### Plugin Version, Server Software, Server Version

Nova: 0.8.5, Paper: git-paper-160 (MC: 1.18.1)

### Observed/Actual behavior

The UI of power cells is not accessible when right clicking with certain items equipped (that can be modified on the anvil).

When right clicked twice, the basic and advanced power cells will repair damaged weapons, tools etc. in your hand. I assume this is true of the other power cells, but I have not tested. You need to have the items in the inventory to carry out the repair.

The main problem is, it also will remove any enchantments from your items if you are a low level (stating "You were not skilled enough to keep any enchantments").

I'm not sure if this is something that you are aware of, or whether it can be fixed, but thought I'd make you aware all the same.

### Steps to reproduce

1. Place power cell
2. Have items in inventory needed for repair (e.g. iron ingots for iron hoe)
3. Equip enchanted item that can be repaired (i.e. not full health)
4. Right click power cell twice (first right click is a confirm message).
5. Item will be repaired and enchantments removed if you are not high enough level.

**Comment by NichtStudioCode** [comment]
This is 100% caused by another plugin.
You're also not running the latest paper version.
