### ISSUE TITLE
[Request - Item] Some electric tools.

### ISSUE THREAD

**Issue by Shengmang** [xenondevs/Nova#102]
### Potential name of the item

Drill or chainsaw.

### Describe the item

They can be used for the early stage of the game to offer some convenience to those who are till use stone pickaxe. In addition, they can be unbreakable, which can make the demands of  experience fixing.

### Additional context

Maybe it is hard for plugin to do such things, but it is helpful for a survival game.

**Comment by NichtStudioCode** [comment]
Feature requests have been moved to [Discord](https://discord.gg/hnEknVWvUe).
