### ISSUE TITLE
[Request - Generic] Redstone Support (Minecraft Vanilla)

### ISSUE THREAD

**Issue by strich3** [xenondevs/Nova#104]
### Describe your feature request.

That you could power Redstone Lamps with Nova or other Stuff. I guess it would be great to have something like that :)

**Comment by ByteZ1337** [comment]
What exactly do you mean by "power Redstone Lamps"? Do you want to power redstone lamps using Novas energy?

**Comment by strich3** [comment]
like power redstone lamps, implement buttons.
