### ISSUE TITLE
[Request - Generic] Request Protection plugin compatibility

### ISSUE THREAD

**Issue by Teenkung123** [xenondevs/Nova#110]
### Describe your feature request.

Hi,
I want to request a protection plugin to make nova compatible with it
my server used this protection plugin for a long time now and I want to add more content to my server so I picked this plugin because it has an interesting plugin idea and no mods required but unfortunate that it isn't compatible with the protection plugin my server used.

Hope you can add compatibility soon! Thanks!

Protection plugin link:
https://www.spigotmc.org/resources/protectionstones-updated-for-1-17.61797/

**Comment by ByteZ1337** [comment]
Doesn't ProtectionStones work with WorldGuard regions?

**Comment by Teenkung123** [comment]
> Doesn't ProtectionStones work with WorldGuard regions?

when Quarry dig the protection block the WorldGuard region won't gone
and I'm not sure will Quarry mine block that was in a protected region

**Comment by ByteZ1337** [comment]
>and I'm not sure will Quarry mine block that was in other player's protected region

If it's a worldguard region, no.

>when Quarry dig the protection block the WorldGuard region won't gone

So the only compatibility you need is preventing the protection stone from being broken?

**Comment by Teenkung123** [comment]
> > and I'm not sure will Quarry mine block that was in other player's protected region
> 
> If it's a worldguard region, no.
> 
> > when Quarry dig the protection block the WorldGuard region won't gone
> 
> So the only compatibility you need is preventing the protection stone from being broken?

yes maybe if I found more bugs I will tell you later thanks!
