### ISSUE TITLE
Error found in my server console

### ISSUE THREAD

**Issue by Boomer-1** [xenondevs/Nova#112]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Other plugins

This bug also occurs when no other plugins are present.

### Plugin Version, Server Software, Server Version

paper 175 mc 1.18.1

### Expected behavior

I have no clue what this error is. i caught it in my logs while recording a yt episode.

### Observed/Actual behavior

again, no idea.

### Steps to reproduce

don't know

### Errors

https://pastebin.com/C08Y3NBA

### Additional context

I am not in a position to test this without any other plugins currently. When I can I'll also update paper, but in investigating, this has come up a few different days on this server. There are no Nova items currently in the world, so I can say with 100% certainty it's not related to anything I've done on the server.

**Comment by NichtStudioCode** [comment]
This just means that Nova could not connect to spigotmc in order to check if any new updates are available. It should not cause any other issues. We'll change it to a more self-explanatory error message in the future.
