### ISSUE TITLE
[Request - Generic] Add lore to Item Filter

### ISSUE THREAD

**Issue by Teenkung123** [xenondevs/Nova#115]
### Describe your feature request.

Add lore display what item filter is filtering
Example
![image](https://user-images.githubusercontent.com/51858378/157246461-523ed390-ed85-45c4-b7e4-59c268b58440.png)

**Comment by NichtStudioCode** [comment]
Feature requests have been moved to [Discord](https://discord.gg/hnEknVWvUe).
