### ISSUE TITLE
[Bug] Nova has no commands registered for some reason

### ISSUE THREAD

**Issue by BookWyrm114** [xenondevs/Nova#116]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Other plugins

This bug also occurs when no other plugins are present.

### Plugin Version, Server Software, Server Version

Nova 0.8.7, purpur, git-purpur-1565

### Expected behavior

For nova to have working commands and load correctly

### Observed/Actual behavior

![image](https://user-images.githubusercontent.com/79489385/157284727-1a5162c3-6e50-4b83-b829-769744822c03.png)
![image](https://user-images.githubusercontent.com/79489385/157284771-408f0356-ada2-48d6-9b55-1bc51bc43c5d.png)
![image](https://user-images.githubusercontent.com/79489385/157284885-0aa1e16d-44b5-4bd4-a35b-66ef463be29b.png)

It says it's loaded, yet none of it's commands work

### Steps to reproduce

Load nova on pupur

### Errors

no errors

### Additional context

it's as if nova commands just don't exist

**Comment by BookWyrm114** [comment]
ok, here it is:


[latest.log](https://github.com/xenondevs/Nova/files/8208219/latest.log)

**Comment by NichtStudioCode** [comment]
Nova v0.8.8 does not run on 1.18.1

**Comment by BookWyrm114** [comment]
![image](https://user-images.githubusercontent.com/79489385/157292885-b45086a4-8db5-463f-bb7f-89c57ff9d7ec.png)

**Comment by BookWyrm114** [comment]
This bug also occurred a few times in the past with other versions of nova but I just removed nova, so I'm pretty sure it's a plugin/server software incompatibility

**Comment by NichtStudioCode** [comment]
No, you just didn't switch back to 0.8.7 properly. You need to stop the server, replace the plugin jar and start it again.
Instead, you used some weird plugin manager plugin:
``[11:47:51] [Server thread/INFO]: BookWyrm_ issued server command: /serverutils loadplugin Nova-0.8.7.jar``
