### ISSUE TITLE
[Bug] After a while cables stop working

### ISSUE THREAD

**Issue by BookWyrm114** [xenondevs/Nova#118]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Other plugins

This bug also occurs when no other plugins are present.

### Plugin Version, Server Software, Server Version

Nova 0.8.7, purpur, git-purpur-1565

### Expected behavior

Cables will connect and work properly

### Observed/Actual behavior

![image](https://user-images.githubusercontent.com/79489385/157536575-379e29f2-01a3-4bdc-897a-6c11c921db2a.png)

### Steps to reproduce

use cables in some way then wait a while, then after a bit no cables in the world will connect to anything and the machine will no longer require cables nor a power source to keep going as it is stuck with whatever power input level it had before

### Additional context

everything else seems to run perfectly. only cables are broken

**Comment by NichtStudioCode** [comment]
You're running an outdated Nova version.
