### ISSUE TITLE
[Bug] failed to make basic machine frame 

### ISSUE THREAD

**Issue by gurachan** [xenondevs/Nova#119]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Other plugins

This bug also occurs when no other plugins are present.

### Plugin Version, Server Software, Server Version

Nova 0.8.9 Paper 1.18.2-R0.1-SNAPSHOT git: b55ba19

### Expected behavior

![image](https://user-images.githubusercontent.com/12135498/157896893-57768356-9a46-47da-b8e2-b01ff6448ce6.png)

### Observed/Actual behavior

![image](https://user-images.githubusercontent.com/12135498/157896784-12bb4021-2a34-43bd-afef-4da6e92630eb.png)

### Steps to reproduce

just craft it

### Errors

idk

### Additional context

idk

**Comment by ByteZ1337** [comment]
Did you actually test if this happens without other plugins?
