### ISSUE TITLE
[Bug] Nova not loading

### ISSUE THREAD

**Issue by BookWyrm114** [xenondevs/Nova#120]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Other plugins

This bug also occurs when no other plugins are present.

### Plugin Version, Server Software, Server Version

Nova 0.8.9, purpur, git-purpur-1585

### Expected behavior

Nova loads properly

### Observed/Actual behavior

Nova did not load, no commands work, and all custom blocks don't work

### Steps to reproduce

Try loading nova on 1.18.2

### Errors

[latest.log](https://github.com/xenondevs/Nova/files/8238057/latest.log)

**Comment by ByteZ1337** [comment]
Did you actually test if this happens without other plugins?
