### ISSUE TITLE
[Bug] Nova is creating world folder !!

### ISSUE THREAD

**Issue by ErythroCraft** [xenondevs/Nova#121]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Other plugins

This bug also occurs when no other plugins are present.

### Plugin Version, Server Software, Server Version

Nova: 0.8.9 | Spigot: CraftBukkit version 3462-Spigot-ffceeae-2c47af0 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT)

### Expected behavior

The plugin Nova is creating a folder called world while installation the datapack of Nova.

The problem is, that the world "world" is not existing (by me) and overidden by me in the server.properties file.
I don't have a world called world.

Your plugin is not calling the "server.properties" file overridden world main name.

Part (server.properties): level-name=Living

### Observed/Actual behavior

!! Missing !!

https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Server.html#getWorlds()

![world_folder](https://user-images.githubusercontent.com/76217862/159448606-9c565bf0-d9a9-4c8b-aac1-73a4b14644e6.PNG)

### Steps to reproduce

1. Installing the plugin Nova
2. Nova is creating the folder world instead the folder Living.

### Errors

No Error in Console, yet.

**Comment by ArtelGG** [comment]
This also happens when you relocate the world folder using the startup flag for Spigot based servers. Nova is only saving a data pack, not that big of a deal and doesn't seem to affect the functionality of the plugin in any way, based on my experience.

The startup flag is the new way to handle the old `bukkit.yml` option. Read more [here](https://hub.spigotmc.org/jira/browse/SPIGOT-5824)

**Comment by ArtelGG** [comment]
That doesn't really provide any useful information. My post was about Nova not respecting the world folder being **moved**, similar to your original issue being about Nova not respecting the world folder being **renamed**, not accessing keys within the datapack.
