### ISSUE TITLE
[Request - Generic] Quarry machine break blocks or not.

### ISSUE THREAD

**Issue by h266579110** [xenondevs/Nova#122]
### Describe your feature request.

Can we config Quarry machine break blocks or not?

Most like a flag can setting
`prevent-block-damage: true or false`

Whether prevent-block-damage set true or false, we can still get ores by machine.

**Comment by ByteZ1337** [comment]
Doesn't really work with the current model. Sounds more like a different block like the digital miner from Mekanism.
