### ISSUE TITLE
[Bug] the plugin completely nukes the recipes for all other plugins like craftory and space

### ISSUE THREAD

**Issue by legitbox** [xenondevs/Nova#125]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Other plugins

This issue is about a specific plugin incompatibility.

### Plugin Version, Server Software, Server Version

Nova 0.8.9 paper 276

### Expected behavior

i expected the plugin to not nuke the recipes

### Observed/Actual behavior

just install any plugin with custom recipes

### Steps to reproduce

just install any plugin with custom recipes

### Errors

just install any plugin with custom recipes

### Additional context

just install any plugin with custom recipes

**Comment by NichtStudioCode** [comment]
Can reproduce it, looking into it now!

**Comment by NichtStudioCode** [comment]
Thanks for reporting, the update containing the fixed will be released shortly. Btw, you don't need to fill out the boxes which are not marked with an asterisk 😉
