### ISSUE TITLE
[Bug] Incompatability with ItemsAdder Emotes

### ISSUE THREAD

**Issue by Andre601** [xenondevs/Nova#126]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Other plugins

This issue is about a specific plugin incompatibility.

### Plugin Version, Server Software, Server Version

Nova: 0.8.10, PaperMC git-Paper-277 (MC: 1.18.2)

### Expected behavior

When using Nova alongside ItemsAdder (while following the wiki about how to merge resource packs) should `/iaemote`s work without interferences.

### Observed/Actual behavior

Nova for some reason cancels out Packets send by ItemsAdder resulting in the animation being "stuck". This behaviour cannot be observed when Nova is removed from the server.

### Steps to reproduce

1. Install Nova and ItemsAdder
2. Setup resource pack in IA according to the wiki [[Link](https://itemsadder.devs.beer/compatibility-with-other-plugins/compatible/nova)]
3. Restart server to apply all changes
4. Run an emote (i.e. `/iaemote death`)

### Additional context

While this is also something that could (and perhaps should?) be fixed on ItemsAdder's end do I still report it here for possible solutions/reasons as to why this random behaviour is happening.

LoneDev pointed this section out, which may be the cause?
https://github.com/xenondevs/Nova/blob/76f120dd855a31878d697b8fcbcb444a39bc2c9b/Nova/src/main/kotlin/xyz/xenondevs/nova/network/PacketListener.kt#L31

Also mentioned something about registering own Netty pipelines and stuff. He can probably give more in-depth info on what the issue here is.

**Comment by ByteZ1337** [comment]
![RrfYEaQ](https://user-images.githubusercontent.com/42820438/162494478-eb241df4-b046-47ca-8b4f-4d0e0e7f340c.png)
This was the issue. Lonedev directly sends serialized data instead of packets.

**Comment by Andre601** [comment]
Awesome, thanks.
