### ISSUE TITLE
[Bug] Block Placer Bug

### ISSUE THREAD

**Issue by AsOne2020** [xenondevs/Nova#128]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Other plugins

This bug also occurs when no other plugins are present.

### Plugin Version, Server Software, Server Version

Nova: 0.8.11, git-Purpur-1603 (MC: 1.18.2)

### Expected behavior

Use the block place to place the fully Power Cell out. The Power Cell should be fully charged.

### Observed/Actual behavior

The Power Cell is dead.

### Steps to reproduce

1、Place the Block Placer with electricity
2、Put the fully Power Cell into Block Placer

**Comment by NichtStudioCode** [comment]
Will be fixed in 0.9
