### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by istarengwa** [xenondevs/Nova#129]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Other plugins

This issue is about a specific plugin incompatibility.

### Plugin Version, Server Software, Server Version

Nova: delete

### Expected behavior

I deleted the plugin and players still have advancements that appear in game related to the plugin, how to remove this problem?

### Observed/Actual behavior

Players collect objects in games and have achievements called achievements.nova.ultimate_power_cell.title and many others like that; while I reset my server and the worlds, I don't know where to remove to no longer have this

### Steps to reproduce

retrieve an object
gets the achievement

**Comment by NichtStudioCode** [comment]
Delete ``world/datapacks/nova``

Please also fill out the report properly next time
