### ISSUE TITLE
[Bug] placed block turn into cobblestone after server restart

### ISSUE THREAD

**Issue by MINICRUSADER** [xenondevs/Nova#13]
I have a pretty simple setup on my server but every time I stop the server and relaunch it all nova blocks that are placed in my server turn into cobblestone. I can break the cobblestone but the mesh of whatever was there before stays there, I'm able to walk through it and place stuff inside the mesh. to sum it up all nova blocks break and are inoperable after a server restart

![Minecraft Screenshot 2021 07 10 - 19 09 05 08](https://user-images.githubusercontent.com/48370422/125179233-6af80700-e1b2-11eb-9bd4-da723b76aa73.png)

**Comment by NichtStudioCode** [comment]
Are these blocks in the spawn chunks by any chance?

**Comment by NichtStudioCode** [comment]
Should be fixed in 0.3
