### ISSUE TITLE
[Request - Block]  Ender tank, Storage

### ISSUE THREAD

**Issue by NotZer0Two** [xenondevs/Nova#131]
### Potential name of the block

Ender tank, Computer Storage

### Describe the block

EnderTank: a tank like an enderchest but for liquid
Computer Storage: its a sort of computer full of thing and you can get wirless block and everything from that chest like as the refined

### Additional context

https://www.curseforge.com/minecraft/mc-mods/endertanks
https://www.curseforge.com/minecraft/mc-mods/refined-storage

**Comment by NichtStudioCode** [comment]
Feature requests have been moved to [Discord](https://discord.gg/hnEknVWvUe).
