### ISSUE TITLE
[Bug] Block becomes stone

### ISSUE THREAD

**Issue by NotZer0Two** [xenondevs/Nova#132]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Other plugins

This bug also occurs when no other plugins are present.

### Plugin Version, Server Software, Server Version

git-Paper-301 (MC: 1.18.2), Nova version 0.8.12

### Expected behavior

Normal Block texture

### Observed/Actual behavior

A stone block

### Steps to reproduce

1. Place [furnace generator, charger, block breaker] (i didn't listed all but are many all use the cobblestone texture)
2. Then the texture is glitched  but if you watch it in different prospective you can see them

![eNWH2BJu4UWLN84dBb79M7](https://user-images.githubusercontent.com/63092138/164935316-7ef00d73-3561-4132-8f96-f290c6d9b4cc.png)

**Comment by NotZer0Two** [comment]
i notest even the power cell became iron block

**Comment by ByteZ1337** [comment]
Probably has something to do with your client's rendering. Test if it happens on a vanilla client

**Comment by NotZer0Two** [comment]
Yes the bug was about badlion render
