### ISSUE TITLE
[Bug] Server Crashed - 

### ISSUE THREAD

**Issue by ErythroCraft** [xenondevs/Nova#134]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Other plugins

This issue is about a specific plugin incompatibility.

### Plugin Version, Server Software, Server Version

Nova: 0.8.12 | spigot-1.18.2-R0.1-SNAPSHOT.jar:3482-Spigot-42b6152-e87f2e3

### Expected behavior

Explore the Minecraft world.

### Observed/Actual behavior

**Word render stopped working.**

![2022-05-03_22 06 09](https://user-images.githubusercontent.com/76217862/166558094-fd8c1d90-b0c9-4946-9c33-a89f9ef45ea4.png)

### Steps to reproduce

**1. wolking arround the world.
2. world render crashed
3. server crashed**

![Bild_2022-05-03_221308554](https://user-images.githubusercontent.com/76217862/166558318-329a28b1-98c9-4cbd-bed4-331c953bb89b.png)

### Errors

[2022-05-03-6.log](https://github.com/xenondevs/Nova/files/8614027/2022-05-03-6.log)

**Comment by NichtStudioCode** [comment]
Hi, you can't just select "specific plugin incompatibility" without stating the actual incompatibility. I assume you never actually tested anything.

**Comment by ErythroCraft** [comment]
What's that a shit? I can't just select "specific plugin incompatibility" without stating the actual incompatibility.

**### Your plugin is incompetible. All other plugins are working fine.**
Watch out the log file.

    [21:49:56] [Spigot Watchdog Thread/ERROR]: Current Thread: Async Nova Worker - 1
    [21:49:56] [Spigot Watchdog Thread/ERROR]: 	PID: 200 | Suspended: false | Native: false | State: WAITING
    [21:49:56] [Spigot Watchdog Thread/ERROR]: 	Stack:
    [21:49:56] [Spigot Watchdog Thread/ERROR]: 		java.base@17.0.1/jdk.internal.misc.Unsafe.park(Native Method)
    [21:49:56] [Spigot Watchdog Thread/ERROR]: 		 
    java.base@17.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
    [21:49:56] [Spigot Watchdog Thread/ERROR]: 
    @17.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506)
    [21:49:56] [Spigot Watchdog Thread/ERROR]: 		 
    java.base@17.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463)
    [21:49:56] [Spigot Watchdog Thread/ERROR]: 		 
    java.base@17.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434)
    [21:49:56] [Spigot Watchdog Thread/ERROR]: 		 
    java.base@17.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await<br> 
    (AbstractQueuedSynchronizer.java:1623)
    [21:49:56] [Spigot Watchdog Thread/ERROR]: 		 
    java.base@17.0.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take<br> 
    (ScheduledThreadPoolExecutor.java:1170)
    [21:49:56] [Spigot Watchdog Thread/ERROR]: 		 
    java.base@17.0.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take<br> 
    (ScheduledThreadPoolExecutor.java:899)
    [21:49:56] [Spigot Watchdog Thread/ERROR]: 		 
    java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062)
    [21:49:56] [Spigot Watchdog Thread/ERROR]: 		 
    java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122)
    [21:49:56] [Spigot Watchdog Thread/ERROR]: 		 
    java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    [21:49:56] [Spigot Watchdog Thread/ERROR]: 		java.base@17.0.1/java.lang.Thread.run(Thread.java:833)

**Comment by ErythroCraft** [comment]
Offensive

**Comment by NichtStudioCode** [comment]
"Specific plugin incompatibility" means that there is an incompatibility between Nova and a specific plugin. 
Your server is running like 50 plugins, do you expect me to test that all for you, also magically knowing how they are configured?

If you're not able to report a bug and break the issue down into a minimum reproducible example, please abstain from creating further reports in the future. I also find your language very inappropriate.

**Comment by ErythroCraft** [comment]
OK. Then I apologize if I offended you. I will no longer send messages in the future. However, I expected more for my money. A few tips on how to solve the problem or hints as to what could be causing these problems would not have been bad.

**Comment by ByteZ1337** [comment]
>I expected more for my money
Are you a patron? If so I don't think StudioCode knew that.
