### ISSUE TITLE
[Request - Generic] Bluemap compatibility

### ISSUE THREAD

**Issue by BookWyrm114** [xenondevs/Nova#137]
### Describe your feature request.

Bluemap is a plugin like dynmap, but generates a 3d model for a map, so viewers can easily look around the server map as if they are in spectator mode. Bluemap has compatibility for normal methods of adding custom blocks, but since nova uses entities, nova quarries look like this:
![image](https://user-images.githubusercontent.com/79489385/169060054-eb86dd5d-b612-4ffb-926b-2ad5a9488d00.png)

It would be nice if there were some way to make bluemap generate and render nova quarries correctly

**Comment by ByteZ1337** [comment]
They'd have to implement compatibility. We can't implement custom rendering via their API.
