### ISSUE TITLE
[Request - Generic] Optimising performance

### ISSUE THREAD

**Issue by CivicXFB** [xenondevs/Nova#138]
### Describe your feature request.

I don't know when my server has been lagging badly, I found out with timings that Nova is taking up 98% I'm not sure what's happening, I've been learning to write plugins to limit the number of mechanics by myself recently but no luck I need your help!

### Additional context

This link proves that https://timings.aikar.co/?id=49078e6d955148b6bc90723be12244f1 nova is sending serious lags

**Comment by ByteZ1337** [comment]
Please send us a spark timings report as well.

**Comment by CivicXFB** [comment]
[profile-2022-05-25_19.18.51.zip](https://github.com/xenondevs/Nova/files/8770567/profile-2022-05-25_19.18.51.zip)

**Comment by CivicXFB** [comment]
I'm not used to using Spark please understand

**Comment by ByteZ1337** [comment]
How big is your world file? Would it be possible to upload it (and the nova database file) somewhere for debugging?

**Comment by CivicXFB** [comment]
The archive is not particularly large, do you mean to leave only the Nova plugin to test it?

**Comment by ByteZ1337** [comment]
No, I'm talking about the ``plugins/Nova/database.db`` file. Nova stores block data there. Just send me that and your world.

**Comment by CivicXFB** [comment]
Thank you, xenondevs team

**Comment by CivicXFB** [comment]
Could you add a limit to the number of machines and wires allowed in a single block, some players will place a large number of machines in a block causing client lag

**Comment by ByteZ1337** [comment]
Sounds like #109. Set ``islandRecalculateInterval`` to a high number or turn it off entirely
