### ISSUE TITLE
[Bug] translate page linked on README is broken

### ISSUE THREAD

**Issue by justADeni** [xenondevs/Nova#143]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

GitHub README issue - translation related

### Expected behavior

I love this project and would love to help by translating into Czech, Spanish, Russian, but unfortunately project's translate page is broken

### Observed/Actual behavior

![Screenshot from 2022-06-18 14-34-06](https://user-images.githubusercontent.com/59316835/174437875-da773606-3796-4d35-8d28-cdfbcce909a1.png)
https://translate.xenondevs.xyz/projects/nova/ fails

### Steps to reproduce

click on translate link in README - it goes straight to https://translate.xenondevs.xyz/projects/nova/ and I can't access the page

**Comment by ByteZ1337** [comment]
You have to authenticate yourself [via GitHub first](https://translate.xenondevs.xyz/accounts/register/). The link will be fixed shortly.
