### ISSUE TITLE
[Request - Generic] Filter specific files from added base_packs

### ISSUE THREAD

**Issue by Andre601** [xenondevs/Nova#145]
### Describe your feature request.

The `base_packs` option is quite a neat solution to support other content from different Custom Item/Block plugins such as ItemsAdder.
However, this option isn't that perfect as it includes everything without any exceptions, which can be weird.

In the example with ItemsAdder (Which requires you to create a resource pack at least once for all generated model files and stuff) would the following, not needed files be included in the generated Nova resource pack (At least last time I checked):

- A `pack.zip` file which is the latest resource pack generated by ItemsAdder
- A `index.html` that is generated by ItemsAdder... for whatever reason

It should be considered to filter files that aren't required for a valid resource pack (i.e. HTML files and zip files should be excluded).

**Comment by NichtStudioCode** [comment]
Will do. I'm also planning to remove the modelDataStart property (maybe material type too) from the config and choose it based on what model data is already used in the base packs. This should make resource pack creating easier and less confusing for new users.

**Comment by NichtStudioCode** [comment]
The font directory is definitely not included, not sure if there are any other files not present.
