### ISSUE TITLE
[Bug] Nova blocks invisible when Model Engine is installed

### ISSUE THREAD

**Issue by TORPADEKA** [xenondevs/Nova#146]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

This issue is about a specific plugin incompatibility.

### Plugin Version, Server Software, Server Version

Model Engine (Demo Version) R2.5.2, Nova 0.9.3, Paper version git-Paper-34 (MC: 1.19) Implementing API version 1.19-R0.1-SNAPSHOT (Git: e52499e)

### Nova Addons and Versions

Logistics v0.1, Machines v0.1.2, Jetpacks v0.1

### Expected behavior

Nova blocks showing properly when put down on the ground.

### Observed/Actual behavior

Nova blocks can be put down, has hitbox and can be interacted with, but are invisible 
(no appearance, armor stand also missing when in spectator mode)
![2022-06-23_23 06 55](https://user-images.githubusercontent.com/80013032/175344781-1b7240b7-94cd-4a4f-90fb-ef0c38da5a98.png)
![2022-06-23_23 07 34](https://user-images.githubusercontent.com/80013032/175344890-8424ddbc-8582-4b33-a4aa-a426258256c9.png)

### Steps to reproduce

1. Use a Paper server
2. Install latest Nova plugin and addons & Model Engine latest demo version
3. Use '/nova give' command to get any place-able block and put it on the ground

### Full server log

https://pastebin.com/TZ6mpfAq

### Errors

There are no errors shown in console

### Additional context

As soon a I remove Model Engine and restart the server though, the existing blocks that had no appearance and armor stand reappear normally.

Model Engine also has no models loaded and I am only using Nova's generated resource pack on vanilla Minecraft 1.19.

Thank you in advance! o.o

**Comment by Creaous** [comment]
I experience something similar, but they randomly go invisible after I go offline for a while. Thought to post it here since its similar to my issue and might be another plugin conflict.
Plugins:
![image](https://user-images.githubusercontent.com/68230846/175938524-4920e7b3-0bbd-4e89-abf4-728c03fb6de6.png)
Server Version: Purpur 1.19

**Comment by Creaous** [comment]
Update to my previous comment. I noticed that they disappear when really deep under ground and the ones I have had above ground are still there. However, one of the cables have turned into a cable which actually might be from my disasters plugin. So this could be a separate issue too.

**Comment by Maks1116** [comment]
This happens to me when I teleport somewhere. I also get this at console.
```
[11:35:08 WARN]: Exception in thread "Nova WorldDataManager" java.lang.IllegalStateException: TileEntity is not initialized
[11:35:08 WARN]: 	at Nova-0.9.9.jar//xyz.xenondevs.nova.data.world.block.state.NovaTileEntityState.getTileEntity(NovaTileEntityState.kt:27)
[11:35:08 WARN]: 	at Nova-0.9.9.jar//xyz.xenondevs.nova.data.world.block.state.NovaTileEntityState.handleRemoved(NovaTileEntityState.kt:57)
[11:35:08 WARN]: 	at Nova-0.9.9.jar//xyz.xenondevs.nova.data.world.WorldDataManager.unloadChunk(WorldDataManager.kt:86)
[11:35:08 WARN]: 	at Nova-0.9.9.jar//xyz.xenondevs.nova.data.world.WorldDataManager.access$unloadChunk(WorldDataManager.kt:28)
[11:35:08 WARN]: 	at Nova-0.9.9.jar//xyz.xenondevs.nova.data.world.WorldDataManager$init$2.invoke(WorldDataManager.kt:45)
[11:35:08 WARN]: 	at Nova-0.9.9.jar//xyz.xenondevs.nova.data.world.WorldDataManager$init$2.invoke(WorldDataManager.kt:40)
[11:35:08 WARN]: 	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
```

**Comment by NichtStudioCode** [comment]
Can you check if this is still an issue with Model Engine v3? The bug seems to have resolved itself.
