### ISSUE TITLE
[Bug] Compatibility with Block Breaker and BentoBox's AOneBlock Gamemode

### ISSUE THREAD

**Issue by Teenkung123** [xenondevs/Nova#147]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

This issue is about a specific plugin incompatibility.

### Plugin Version, Server Software, Server Version

Nova 0.9.7, git-Purpur-1682 (MC: 1.19)

### Nova Addons and Versions

Logistics 0.1.1, Machines 0.1.3, Jetpacks 0.1.1

### Expected behavior

I am making a One Block Server (Skyblock that has only 1 block that will re-generate itself when broken) and block breaker should break that one block without any issues 

### Observed/Actual behavior

Block breaker break that one block but that block never re-generate again

### Steps to reproduce

1) Create an empty server (1.19)
2 ) Download AOneblock File from this link https://download.bentobox.world
![image](https://user-images.githubusercontent.com/51858378/176177033-a5b1f3c8-cc78-4ff1-b45f-cbe7a3f2a4b7.png)
3) Extract the file to the server then install Nova plugin with machine addon installed
4) Start the server
5) Create a new island with command /ob create
6) try break that one block (it will re-generate itself)
7) place Block Breaker like this 
![image](https://user-images.githubusercontent.com/51858378/176177526-fb7b4ab2-a53c-4283-9359-f939018a9956.png)
8) give it some Energy to work
9) and that block never re-generate again
(I haven't tried quarry yet maybe it causes the same issue too)

### Full server log

it actually has nothing to do with a server log file, but here 
https://pastebin.com/efLRcSgc

### Additional context

I don't know what Devepor I should report this bug to (Nova Devs or BentoBox devs)
(sorry if I have bad English it is not my native language)

**Comment by NichtStudioCode** [comment]
You should report this to the BentoBox devs, it has to be fixed on their side.
