### ISSUE TITLE
[Bug] Crafting recipe not showing correctly 

### ISSUE THREAD

**Issue by NotZer0Two** [xenondevs/Nova#149]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

git-Purpur-1670 (MC: 1.19), Nova version 0.9.8

### Nova Addons and Versions

Logistics, Jetpacks, Machines all latest

### Observed/Actual behavior

Video: https://www.dropbox.com/s/jm09826fg9d3vdt/Minecraft%202022.06.29%20-%2022.10.23.02.DVR%20%282%29.mp4?dl=0

### Steps to reproduce

1. make a crafting on Nova
2. restart the server for recipe book
3. try without item and will show the shulker shell
4. with the item in the inventory work

### Full server log

https://pastebin.com/wD0w7xSZ

### Additional context

Crafting recipe
```
{
  "result": "iasurvival:cpu_avanzata",
  "shape": [
    "cld",
    "gug",
    "apa"
  ],
  "ingredients": {
    "c": "nova:copper_dust",
    "l": "nova:lapis_dust",
    "d": "nova:diamond_dust",
    "g": "minecraft:gold_ingot",
    "p": "nova:iron_plate",
    "a": "nova:coal_dust",
    "u": "iasurvival:cpu" 
  }
}
```

**Comment by NichtStudioCode** [comment]
1. "There are no other plugins running on my server." means that there are no other plugins running on the server, which is not the case.
2. Your reproduction steps are not proper English, I have no idea what you're saying.
3. The linked video has nothing to do with the rest of the report.

Please fix the above-mentioned issues with your report and create a new one. If you want to report multiple bugs, please create separate issues for each of them.
