### ISSUE TITLE
[Bug] Crafting recipe not showing correctly

### ISSUE THREAD

**Issue by NotZer0Two** [xenondevs/Nova#150]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

This issue is about a specific plugin incompatibility.

### Plugin Version, Server Software, Server Version

git-Purpur-1670 (MC: 1.19), Nova version 0.9.8

### Nova Addons and Versions

Logistics, Jetpacks, Machines all latest

### Observed/Actual behavior

Video: https://www.dropbox.com/s/hou309e3nkw0l7t/Minecraft%202022.07.03%20-%2012.20.52.04.mp4?dl=0

### Steps to reproduce

1. Make a recipe with nova
2. restart the server for the recipe book to reload
3. try without the item in the inventory required and will show the same thing on the video

### Full server log

https://pastebin.com/wD0w7xSZ

### Additional context

Crafting recipe
```
{
  "result": "iasurvival:cpu_avanzata",
  "shape": [
    "cld",
    "gug",
    "apa"
  ],
  "ingredients": {
    "c": "nova:copper_dust",
    "l": "nova:lapis_dust",
    "d": "nova:diamond_dust",
    "g": "minecraft:gold_ingot",
    "p": "nova:iron_plate",
    "a": "nova:coal_dust",
    "u": "iasurvival:cpu" 
  }
}
```

**Comment by NotZer0Two** [comment]
this time i tried to be more concern and i sent was wrong

**Comment by NichtStudioCode** [comment]
Will be fixed in the next patch!
