### ISSUE TITLE
[Request - Generic] Apply to support version 1.18x

### ISSUE THREAD

**Issue by Annijang** [xenondevs/Nova#151]
### Describe your feature request.

When I was using "nova", the version was 0.8.9, and I found that the item filter could not save data. When I reported on another github, the author told me that the version was too low, but I downloaded the latest version on spigotmc , it prompts me that 1.18.2 is not supported, only 1.19 is supported. Could you please add support for 1.18 in "nova", "machines", and "logistics", thank you, if it bothers you, please Forgive me, I'm sorry
![PKEUSQ5L%UH33{W_HPZ @Q4](https://user-images.githubusercontent.com/75552974/178108344-370d3289-ac53-4ea7-a24b-7e2d1599dfd2.png)
.

**Comment by NichtStudioCode** [comment]
As mentioned in our [FAQ](https://xenondevs.xyz/docs/nova/admin/faq/), there are currently no plans on adding multi-version support.
