### ISSUE TITLE
[Bug] Resource pack is not downloaded

### ISSUE THREAD

**Issue by LisuS3** [xenondevs/Nova#154]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova-0.9.8 , git-Pufferfish-17 (MC: 1.19)

### Nova Addons and Versions

Logistics-0.1.1, Machines-0.1.4, jetpacks-0.1.1

### Expected behavior

download resourcepack by the server

### Observed/Actual behavior

I'm trying to configure the automatic download of the resurepack on my server and unfortunately the resourcepack does not want to download

config.yml
auto_upload:
    enabled: true
    service: SelfHost
    port: 1337
    portNeeded: true

> nova resourcePack reupload
[02:22:46 INFO]: Uploading resource pack... please wait
[02:22:46 ERROR]: [Nova] Server responded with an invalid pack URL: http://135.181.60.45
:1337/AZrwr
[02:22:46 INFO]: The resource pack could not be uploaded.

other plugins
[02:25:51 INFO]: Plugins (8):  Nova, OneblockAPI, PlaceholderAPI, SlimeWorldManager, spark, ZeriaAPI, ZeriaOneblock

### Steps to reproduce

I turn on the server
I go to the server (resource pack is not downloaded)
I use the command: Nova ResourcePack replouad
I am getting an error

### Full server log

https://pastebin.com/aVxnhAHB

### Errors

[02:22:46 INFO]: Uploading resource pack... please wait
[02:22:46 ERROR]: [Nova] Server responded with an invalid pack URL: http://135.181.60.45
:1337/AZrwr
[02:22:46 INFO]: The resource pack could not be uploaded.

**Comment by ByteZ1337** [comment]
Could you run ``curl https://checkip.amazonaws.com > ip.txt`` and check if ``ip.txt`` has a new line appended at the end of the file/has multiple addresses in it?

**Comment by LisuS3** [comment]
![Zrzut ekranu 2022-07-21 o 14 42 32](https://user-images.githubusercontent.com/64312209/180215902-45f321c1-7df0-4f21-944e-7a63d307ae32.png)

there is only an ip dedication in the file

**Comment by ByteZ1337** [comment]
But it does have a newline character appended at the end. Weird. Doesn't do that for me. Should be an easy fix though
