### ISSUE TITLE
[Bug] error message on login

### ISSUE THREAD

**Issue by freethemice** [xenondevs/Nova#155]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Plugin Version, Server Software, Server Version

Nova: 0.9.8 Papper 68 1.19

### Nova Addons and Versions

Logistics-0.1.1 Machines-0.1.4

### Expected behavior

No error message

### Observed/Actual behavior

Error message, on login

### Steps to reproduce

1. I placed a lot of logistics:ultimate_cable
2. server restarted
3. error message started spamming
4. I removed all nova items in the world
5. I deleted all nova files from the server, to reinstall it
6. the spamming stop but now I get a error message on login

### Full server log

https://pastebin.com/PsJjrdj0

### Errors

Login error now -> https://pastebin.com/wCL4ZPpb

spamming error - >https://pastebin.com/aKeie2HC

**Comment by ByteZ1337** [comment]
>I deleted all nova files from the server, to reinstall it

Did you also delete the ``nova_region`` folders in your world folders?

**Comment by freethemice** [comment]
> > I deleted all nova files from the server, to reinstall it
> 
> Did you also delete the `nova_region` folders in your world folders?

no, also its if you place cable bellow y =0 in the negatives it spams this error when you restart the server and all cables below y =0 are chains
