### ISSUE TITLE
[Bug] Cable network stopped working

### ISSUE THREAD

**Issue by freethemice** [xenondevs/Nova#157]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Plugin Version, Server Software, Server Version

Nova 0.9.9, paper 1.19

### Nova Addons and Versions

Logistics-0.1.1, Machines-0.1.4

### Expected behavior

No errors, and every thing works

### Observed/Actual behavior

restarting server error in console, and cable network stopped working.
All, cables connected to chest didn't open gui, and had to be replaced.
most of the cables had to be replace also

### Steps to reproduce

1. I don't know

### Full server log

[2022-07-24-2.log.gz](https://github.com/xenondevs/Nova/files/9176760/2022-07-24-2.log.gz)

[2022-07-24-7.log.gz](https://github.com/xenondevs/Nova/files/9176759/2022-07-24-7.log.gz)

[2022-07-24-3.log.gz](https://github.com/xenondevs/Nova/files/9176755/2022-07-24-3.log.gz)
[2022-07-24-4.log.gz](https://github.com/xenondevs/Nova/files/9176756/2022-07-24-4.log.gz)
[2022-07-24-5.log.gz](https://github.com/xenondevs/Nova/files/9176757/2022-07-24-5.log.gz)
[2022-07-24-6.log.gz](https://github.com/xenondevs/Nova/files/9176758/2022-07-24-6.log.gz)

### Errors

https://pastebin.com/0KvTWHMi
https://pastebin.com/MKd8tPmu

**Comment by ByteZ1337** [comment]
Please test if this is a plugin compatibility issue instead of just deleting that section of the issue template.

**Comment by NichtStudioCode** [comment]
Hi, the sections in the bug report form are there for a reason. You can't just delete them.
You've also uploaded six log files instead of one for no apparent reason, and then they're also in archive format instead of uploaded to a paste site such as Pastebin. There are no steps to reproduce, and "paper 1.19" is not a valid server version.

**Comment by freethemice** [comment]
I'm trying to help you guy, you need to do better testing before release the plugin. I have had to reset my server once when the plugin was finally updated, again when you didn't code the negative y value and now a 3rd time to remove this plugin for good. Good luck.

**Comment by ByteZ1337** [comment]
>I'm trying to help you guy

You're doing the exact opposite. If the issue is caused by another plugin, we could spend hours wasting our time trying to find an issue that doesn't even exist in Nova alone.

Addressed your other points on Spigot.
