### ISSUE TITLE
[Bug]  can't create a resource pack using self host

### ISSUE THREAD

**Issue by PickleOnAString** [xenondevs/Nova#161]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

0.10.2, server is latest purpur, on 1.19.2

### Nova Addons and Versions

none

### Expected behavior

have resource pack applied

### Observed/Actual behavior

nothing happens and I get an error

### Steps to reproduce

just put a resource pack in basepacks folder and use self hosting

### Full server log

https://pastebin.com/NdQvP9x7

### Errors

ERROR [Nova] Failed to download resourcepack! Is the server down?
08.08 04:59:50 [Server] INFO java.io.IOException: Service returned response code 404
08.08 04:59:50 [Server] INFO at de.studiocode.invui.resourcepack.ForceResourcePack.setResourcePack(ForceResourcePack.java:104) ~[Nova-0.10.2.jar:?]
08.08 04:59:50 [Server] INFO at de.studiocode.invui.resourcepack.ForceResourcePack.setResourcePack(ForceResourcePack.java:122) ~[Nova-0.10.2.jar:?]
08.08 04:59:50 [Server] INFO at xyz.xenondevs.nova.data.resources.upload.AutoUploadManager.forceResourcePack(AutoUploadManager.kt:146) ~[Nova-0.10.2.jar:?]
08.08 04:59:50 [Server] INFO at xyz.xenondevs.nova.data.resources.upload.AutoUploadManager.uploadPack(AutoUploadManager.kt:123) ~[Nova-0.10.2.jar:?]
08.08 04:59:50 [Server] INFO at xyz.xenondevs.nova.data.resources.Resources$createResourcePack$1.invokeSuspend(Resources.kt:50) ~[Nova-0.10.2.jar:?]
08.08 04:59:50 [Server] INFO at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[?:?]
08.08 04:59:50 [Server] INFO at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[?:?]
08.08 04:59:50 [Server] INFO at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:279) ~[?:?]
08.08 04:59:50 [Server] INFO at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85) ~[?:?]
08.08 04:59:50 [Server] INFO at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59) ~[?:?]
08.08 04:59:50 [Server] INFO at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source) ~[?:?]
08.08 04:59:50 [Server] INFO at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38) ~[?:?]
08.08 04:59:50 [Server] INFO at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source) ~[?:?]
08.08 04:59:50 [Server] INFO at xyz.xenondevs.nova.data.resources.Resources.createResourcePack(Resources.kt:49) ~[Nova-0.10.2.jar:?]
08.08 04:59:50 [Server] INFO at xyz.xenondevs.nova.command.impl.NovaCommand$createResourcePack$1.invoke(NovaCommand.kt:129) ~[Nova-0.10.2.jar:?]
08.08 04:59:50 [Server] INFO at xyz.xenondevs.nova.command.impl.NovaCommand$createResourcePack$1.invoke(NovaCommand.kt:127) ~[Nova-0.10.2.jar:?]
08.08 04:59:50 [Server] INFO at xyz.xenondevs.nova.util.AsyncExecutor.run$lambda-0(SchedulerUtils.kt:88) ~[Nova-0.10.2.jar:?]
08.08 04:59:50 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
08.08 04:59:50 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
08.08 04:59:52 [Server] INFO at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
08.08 04:59:52 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) ~[?:?]
08.08 04:59:52 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
08.08 04:59:52 [Server] INFO at java.lang.Thread.run(Thread.java:831) ~[?:?]

**Comment by Cyq20100313** [comment]
Are you sure you can use your self-hosted url upload resource-pack by you-self, without any 404 not found error?

**Comment by Cyq20100313** [comment]
Are you sure the upload url exist

**Comment by PickleOnAString** [comment]
will check

**Comment by PickleOnAString** [comment]
this is the config:

  auto_upload:
    enabled: true
    service: SelfHost
    port: 8158

and your do I check if I can use your self-hosted URL your self?

**Comment by NichtStudioCode** [comment]
Try ``/nova resourcePack reupload``. This will also give you the link from which the pack should be accessible.
