### ISSUE TITLE
[Bug] Nova recipe

### ISSUE THREAD

**Issue by Creepdasheep** [xenondevs/Nova#162]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova 0.10.2   git.Purpur-1751 (Mc: 1.19.1) Latest version

### Nova Addons and Versions

Jetpack 0.1.3, Machines 0.1.5, Logistics 0.1.2

### Expected behavior

By clicking on another nova item recipe in a nova item recipe it shows how to make said item.

### Observed/Actual behavior

Instead shows Fishing Rod.

### Steps to reproduce

Open nova items /nova items
Go to the best jetpack and click the other nova jetpack it needs and it shows a fishing rod

### Full server log

https://pastebin.com/YcU29ipy
​

### Errors

None

### Additional context

I have a YouTube video to show it better https://www.youtube.com/watch?v=UqhqM70Upag

also in the server log it shows that the resource pack failed but I was just testing something. And the resource pack was on local computer hard drive loaded into Minecraft.

**Comment by ByteZ1337** [comment]
Fixed in 0.10.3
