### ISSUE TITLE
Blocks wont place 

### ISSUE THREAD

**Issue by Beavercody765** [xenondevs/Nova#163]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova: 0.10.3 Spigot Minecraft: 1.19.1

### Nova Addons and Versions

Logistics 0.1.2 Jetpacks-0.1.3 Machines-0.1.5

### Expected behavior

The blocks would place 

### Observed/Actual behavior

When i right click the blocks wont place 

### Steps to reproduce

1. Craft he block 
2. Place the block

### Full server log

Cant find the logs

**Comment by NichtStudioCode** [comment]
Fixed in 0.10.4
