### ISSUE TITLE
[Bug] Nova disables on startup

### ISSUE THREAD

**Issue by sarhatabaot** [xenondevs/Nova#164]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova: 0.10.4, Purpur: 1.19.2 b1760

### Nova Addons and Versions

Logistics: 0.1.2, Machines: 0.1.5, Jetpacks: 0.1.3

### Expected behavior

Plugin should load up with no errors.

### Observed/Actual behavior

Plugin is disabled on server start.
See server log below.

### Steps to reproduce

Load the server

### Full server log

https://pastebin.com/09GkjjT7 - With additional plugins
https://bin.bloom.host/ixiyotomaf - With only nova

### Additional context

I've tried completely removing the nova folder and a doing a clean install. No luck.
Removing all other plugins removed some of the errors but the plugin disables on load.

**Comment by ByteZ1337** [comment]
> I've tried completely removing the nova folder and a doing a clean install. No luck.

Did you also delete the ``nova_region`` folders in your world folders?

**Comment by sarhatabaot** [comment]
I haven't I'll try that now.

**Comment by sarhatabaot** [comment]
That seems to have fixed my issue. Thanks for the help!

**Comment by sarhatabaot** [comment]
After restarting my server once the issue seems to have returned.

**Comment by ByteZ1337** [comment]
Could you send your actual server log files instead of console output?

**Comment by sarhatabaot** [comment]
Sure
Just nova: https://pastebin.com/rEU5tQWZ
With plugins: https://pastebin.com/t55twmek

**Comment by ByteZ1337** [comment]
[Nova-test.zip](https://github.com/xenondevs/Nova/files/9333811/Nova-test.zip)

Could you use the Nova version in this zip and check what it prints when it gets disabled?

**Comment by sarhatabaot** [comment]
https://pastebin.com/6xYP607p

This only happen after I create a resource pack with `/nova resourcePack create`. First load up - before remaking the resource pack - was fine.

**Comment by ByteZ1337** [comment]
Do you have any AutoUpload service enabled?

**Comment by sarhatabaot** [comment]
I'm using selfhost with autoupload disabled.
config.yml: https://pastebin.com/ECcuS6gk

**Comment by ByteZ1337** [comment]
I'm so confused...

This `if` fails for some reason, which leads to Nova being disabled.

https://github.com/xenondevs/Nova/blob/30e621aede0d91d662e997794653434415512025/Nova/src/main/kotlin/xyz/xenondevs/nova/initialize/Initializer.kt#L106-L118

However, as printed here

![log](https://i.imgur.com/YcMSsrk.png)

everything was properly initialized. So how can the `if` fail? I'm running the exact same server version/software with the exact same addons and config, but it works fine for me. Are you by any chance familiar with debugging in IntelliJ?

**Comment by sarhatabaot** [comment]
Sure, I can set it up. Perhaps it has something to do with pack merging?

**Comment by ByteZ1337** [comment]
I doubt it, since the class responsible for merging resourcepacks is also in the initialized list. But you can send me your base packs if you want.

**Comment by ByteZ1337** [comment]
Or you could send me your entire server in a zip via discord

**Comment by ByteZ1337** [comment]
We might've found the issue, I'll send you a build with a potential fix soon
