### ISSUE TITLE
[Bug] Shift Right click gives you the item.

### ISSUE THREAD

**Issue by Creepdasheep** [xenondevs/Nova#165]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

git-Purpur-1751 (1.19.1), Nova 0.10.3

### Nova Addons and Versions

Jetpacks-0.1.3, Logistics-0.1.2, Machines-0.1.5, 

### Observed/Actual behavior

Shift right click gives you the item

### Steps to reproduce

1. Open nova items
2. Shift right click a item

### Full server log

https://cdn.discordapp.com/attachments/954479131880464475/1008413413917069322/latest_1.log

### Errors

No Errors

### Additional context

It still does it when people aren't op

**Comment by ByteZ1337** [comment]
Are the players in creative?

**Comment by Creepdasheep** [comment]
Nope

**Comment by Creepdasheep** [comment]
Also is there a way to remove all nova items on the server because alot of people abused this

**Comment by NichtStudioCode** [comment]
Just tested it again, [you can only take items when you're in creative mode](https://github.com/xenondevs/Nova/blob/main/Nova/src/main/kotlin/xyz/xenondevs/nova/ui/menu/item/recipes/RecipeChoiceItem.kt#L43-L55).

Did you check if it is caused by another plugin? Because that's what you selected when creating this issue, but there are a lot of other plugins in your server log...

> Also is there a way to remove all nova items on the server because alot of people abused this

No, there isn't.

**Comment by Creepdasheep** [comment]
Wait It only works for jetpacks

**Comment by Creepdasheep** [comment]
I mean you can only get the item with jetpacks all other items works

**Comment by ByteZ1337** [comment]
I can reproduce it with Jetpacks. We'll look into it

**Comment by Creepdasheep** [comment]
Okay thanks

**Comment by ByteZ1337** [comment]
You can remove jetpacks from the ``item_categories.yml`` file in the meantime if you want.

**Comment by Creepdasheep** [comment]
It still does it but now the item does not disappear after shift right click and the item appears but the item still

**Comment by ByteZ1337** [comment]
Can't reproduce on latest Nova + addons
https://www.youtube.com/watch?v=KHhGvWczLlA

**Comment by Creepdasheep** [comment]
try 1.19.1

**Comment by ByteZ1337** [comment]
Nope, still doesn't work. Are you in creative?

**Comment by Creepdasheep** [comment]
Nope

**Comment by Creepdasheep** [comment]
It fixed itself after I deleted the nova folder
