### ISSUE TITLE
[Request - Generic] Add support to lands plugin

### ISSUE THREAD

**Issue by Creepdasheep** [xenondevs/Nova#166]
### Describe your feature request.

Items like trash can, quarry, pipes can be broken edited placed in claimed land

**Comment by Creepdasheep** [comment]
There is also a dev api https://github.com/Angeschossen/LandsAPI

**Comment by NichtStudioCode** [comment]
Hi, I've contacted the Lands dev about this a year ago, but he just blocked me without any response. Therefore, it is not possible for us to implement any compatibility. It's also an open issue on their GitHub: https://github.com/Angeschossen/LandsAPI/issues/10

**Comment by Angeschossen** [comment]
I just saw this now. And think this is a misunderstanding. I never blocked you. I don't have DMs open. Maybe I had them temporarily enabled to test something and forgot that we weren't friends on Discord.
