### ISSUE TITLE
[Bug] Itemsadder & Nova failed to merge/apply

### ISSUE THREAD

**Issue by SteelsSystem** [xenondevs/Nova#167]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

This issue is about a specific plugin incompatibility.

### Plugin Version, Server Software, Server Version

nova0.10.5,git-purpur1762, 1.19.2

### Nova Addons and Versions

currently 0 on fresh install

### Expected behavior

I expected resource pack to apply from both itemsadder&nova

nova resource worked

### Observed/Actual behavior

I expected resource pack to apply from both itemsadder&nova however when i followed the steps on xenondev' docs
several time i even deleted old plugins now to test if i made a mistake.

itemsadder fails to apply any resource in nova

### Steps to reproduce

Install itemsadder, 
install nova, 
stop server,
 configure both plugins accordingly to guide, disabled , start server, do /iazip, do /nova resourcepack create, restart server. resource pack still not applied

### Full server log

https://mclo.gs/49joT3V

### Additional context

![obrazek](https://user-images.githubusercontent.com/92061582/187014965-96b6e493-e326-47e2-bfbe-ac5f8a6dbda9.png)

**Comment by ByteZ1337** [comment]
Send us your ItemsAdder config

**Comment by SteelsSystem** [comment]
https://mclo.gs/Si4Iv4T

**Comment by ByteZ1337** [comment]
You didn't follow the steps.
![image](https://user-images.githubusercontent.com/42820438/187032686-f7cb8c79-d876-4839-8cb9-cd51384e5212.png)

**Comment by SteelsSystem** [comment]
i was doing it multiple times however my problem
 was lightapi messing with everything
 i disabled it now and it applied the GUIs and everything on itemsadder :)))

**Comment by ByteZ1337** [comment]
We just tested ItemsAdder with LightAPI and Nova and everything worked fine, so it wasn't related to that.
