### ISSUE TITLE
[Bug] Failed to load chunk data

### ISSUE THREAD

**Issue by KyozXD** [xenondevs/Nova#17]
**Plugin Version and Server Software**
Nova 0.33 | Purpur 1.17.1 (git-Purpur-1287)

**Describe the bug**
When placing nova blocks down and the player leaving the server and either the server restarts or the chunk unloads when the player logs back on the console throws an error regarding failed to read chunk followed by a failed to load chunk error. The blocks are then replaced with cobblestone and other random blocks.

Error below

**To Reproduce**
1. Place Nova blocks down
2. Close server and save data
3. Start the server and join (Blocks should be replaced with cobble and others)

**Expected behavior**
Start the server and have the server load the respected chunk without error

**Errors**
Console error
https://pastebin.com/hfi2wkb6

**Screenshots**
None applicable

**Additional context**

**Comment by ByteZ1337** [comment]
I'm unable to reproduce this error: https://youtu.be/1qHCnHJDVN0. Have you tested if the same error still occurs on another world?

**Comment by KyozXD** [comment]
Seems to be the world itself. Using a different one works fine with the same plugins and settings
