### ISSUE TITLE
[Request - Generic] Add a prefix for each message

### ISSUE THREAD

**Issue by xiaozhangup** [xenondevs/Nova#171]
### Describe your feature request.

Add a prefix for each message

**Comment by ByteZ1337** [comment]
Why?

**Comment by xiaozhangup** [comment]
> Why?

This makes the plugin's messages neat and tidy and not easily confused with other message texts

**Comment by ByteZ1337** [comment]
It makes the messages clunky and is completely unnecessary. All of our messages appear after running a command or interacting with nova (for example, changing the wrench mode). The only exception is the update reminder, which literally tells you exactly what to update.

**Comment by xiaozhangup** [comment]
> It makes the messages clunky and is completely unnecessary. All of our messages appear after running a command or interacting with nova (for example, changing the wrench mode). The only exception is the update reminder, which literally tells you exactly what to update.

OK,I know. but why this?
![9(_F4Y19K4FCK{7O5F)EX{V](https://user-images.githubusercontent.com/68374769/189070260-8b3f7a3a-0071-4a23-ad82-c564463b1405.png)

**Comment by ByteZ1337** [comment]
Don't see how that's related.

**Comment by xiaozhangup** [comment]
> Don't see how that's related.

If I sell Nova items with Shopkeepr, the items are not displayed properly

**Comment by ByteZ1337** [comment]
Yes, which has nothing to do with prefixes. I'll fix it, but please create separate issues for separate bugs in the future.

**Comment by xiaozhangup** [comment]
> Yes, which has nothing to do with prefixes. I'll fix it, but please create separate issues for separate bugs in the future.

OK
