### ISSUE TITLE
[Request - Generic] Add support for IridiumSkyblock

### ISSUE THREAD

**Issue by xiaozhangup** [xenondevs/Nova#172]
### Describe your feature request.

Here is IridiumSkyblock's link [IridiumSkyblock](https://github.com/Iridium-Development/IridiumSkyblock)
And you can add support just like https://github.com/HAPPYLAND-Dev/Slimefun4/commit/2ccb35b430d493635985102dff975c58f3bb175c

**Comment by ByteZ1337** [comment]
You can also PR it in the [0.11](https://github.com/xenondevs/Nova/tree/0.11) branch if you want. Check out the [other protection implementations](https://github.com/xenondevs/Nova/tree/0.11/nova/src/main/kotlin/xyz/xenondevs/nova/integration/protection/plugin) if you need more context.

**Comment by xiaozhangup** [comment]
> You can also PR it in the [0.11](https://github.com/xenondevs/Nova/tree/0.11) branch if you want. Check out the [other protection implementations](https://github.com/xenondevs/Nova/tree/0.11/nova/src/main/kotlin/xyz/xenondevs/nova/integration/protection/plugin) if you need more context.

Okay, wait for me.

**Comment by xiaozhangup** [comment]
> You can also PR it in the [0.11](https://github.com/xenondevs/Nova/tree/0.11) branch if you want. Check out the [other protection implementations](https://github.com/xenondevs/Nova/tree/0.11/nova/src/main/kotlin/xyz/xenondevs/nova/integration/protection/plugin) if you need more context.

I have submitted my PR
