### ISSUE TITLE
[Bug] Nova causes server threads to freeze

### ISSUE THREAD

**Issue by xiaozhangup** [xenondevs/Nova#175]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

This issue is about a specific plugin incompatibility.

### Plugin Version, Server Software, Server Version

Nova Version: 0.11;git-petal-"eb64b15" (MC: 1.19.2)*

### Nova Addons and Versions

Jetpacks-0.1.4 Logistics-0.2 Machines-0.2

### Expected behavior

[2022-09-10-4.log](https://github.com/xenondevs/Nova/files/9539388/2022-09-10-4.log)

### Observed/Actual behavior

Nothing in game

### Steps to reproduce

1. Start server
2. wait for it

### Full server log

[2022-09-10-4.log](https://github.com/xenondevs/Nova/files/9539389/2022-09-10-4.log)

**Comment by NichtStudioCode** [comment]
Fixed in https://github.com/Nova-Addons/Machines/commit/f83b6105ef34352c0730abafe912d3a652567167 in [Machines v0.2.1](https://github.com/Nova-Addons/Machines/releases/tag/0.2.1).

You might also want to take a look at your network configuration. Downloading a 3 bytes file shouldn't take over 60s.
