### ISSUE TITLE
[Bug] Crash server

### ISSUE THREAD

**Issue by xiaozhangup** [xenondevs/Nova#176]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova Version: 0.11;git-Paper-132 (MC: 1.19.2) 

### Nova Addons and Versions

nul

### Expected behavior

[2022-09-10-18.log](https://github.com/xenondevs/Nova/files/9540283/2022-09-10-18.log)

### Observed/Actual behavior

[Uploading 2022-09-10-18.log…]()

### Steps to reproduce

1. Start server and join it
2. Wait for it

### Full server log

[2022-09-10-18.log](https://github.com/xenondevs/Nova/files/9540286/2022-09-10-18.log)

**Comment by NichtStudioCode** [comment]
Already fixed in e55d9867f7afcd2b3193b48e1602247ca9adcdce

**Comment by xiaozhangup** [comment]
> Already fixed in [e55d986](https://github.com/xenondevs/Nova/commit/e55d9867f7afcd2b3193b48e1602247ca9adcdce)

ok，how to download it?

**Comment by NichtStudioCode** [comment]
You'll need to wait for Nova v0.11.2

**Comment by xiaozhangup** [comment]
> You'll need to wait for Nova v0.11.2

Okay, so can you tell me approximately when it will be released?

**Comment by NichtStudioCode** [comment]
now
