### ISSUE TITLE
[Request] Instruction Book / YouTube demonstration

### ISSUE THREAD

**Issue by AlterDimension** [xenondevs/Nova#18]
+ Add instruction book for newbies
+ Add link of YouTube demonstration

**Comment by ByteZ1337** [comment]
For now, you can use ``/nova inventory`` to see what's available. But I can definitely record videos demonstrating some features.

**Comment by AlterDimension** [comment]
A video demonstration would be great! There are some stuff that I haven't fully understand yet. Please give me a video link if you are making one 👍

**Comment by ByteZ1337** [comment]
You can join the [Support Discord](https://discord.gg/EpVMXtXB2t) if you have any specific questions.
