### ISSUE TITLE
[Bug] CustomNameplates incompatibility

### ISSUE THREAD

**Issue by EiderFC** [xenondevs/Nova#182]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

This issue is about a specific plugin incompatibility.

### Plugin Version, Server Software, Server Version

Nova-0.11.6 git-Purpur-1778 (MC: 1.19.2)

### Nova Addons and Versions

Nova-0.11.6 

### Observed/Actual behavior

spamming errors in console

### Steps to reproduce

![image](https://user-images.githubusercontent.com/88196950/192615721-08217fca-8ed0-4546-9a40-ee92a5ad2658.png)
with the custom nameplates plugin and nova, the console starts to fill up with error messages

### Full server log

[latest.log](https://github.com/xenondevs/Nova/files/9658992/latest.log)

**Comment by NotZer0Two** [comment]
I fixed the problem by removing the background and bossbar from modules.yml and works everything just fine

**Comment by EiderFC** [comment]
> I fixed the problem by removing the background and bossbar from modules.yml and works everything just fine

what I want to do is keep both, the waila and the bossbar of custom nameplates

**Comment by NotZer0Two** [comment]
> > I fixed the problem by removing the background and bossbar from modules.yml and works everything just fine
> 
> what I want to do is keep both, the waila and the bossbar of custom nameplates

Nova can't help and even customnameplate, because they use a similar system probably more from customnameplate for not checking empty or some character try ask them

**Comment by NichtStudioCode** [comment]
Will be fixed in `0.13`.
