### ISSUE TITLE
[Bug] Item material rendering error

### ISSUE THREAD

**Issue by xiaozhangup** [xenondevs/Nova#183]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

This issue is about a specific plugin incompatibility.

### Plugin Version, Server Software, Server Version

0.11.6 git-Mirai-23 (MC: 1.19.2)

### Nova Addons and Versions

L0.2 M0.2.1 J0.1.4

### Observed/Actual behavior

https://streamable.com/x6mjag

### Steps to reproduce

1.Placing a machine
2.Place a block next to him

### Full server log

[2022-10-18-19.log](https://github.com/xenondevs/Nova/files/9815745/2022-10-18-19.log)
[2022-10-19-1.log](https://github.com/xenondevs/Nova/files/9815709/2022-10-19-1.log)

### Additional context

I've been using the official version of Nova since you told me to try it.

**Comment by NichtStudioCode** [comment]
Works fine for me. Please actually check if this is caused by another plugin or your server software (which explicitly states that it is not ready for production use).

**Comment by xiaozhangup** [comment]
> Works fine for me. Please actually check if this is caused by another plugin or your server software (which explicitly states that it is not ready for production use).

I tried to test it with Purpur and the problem still exists.
Could this be related to Paper's new chunk system?

**Comment by NichtStudioCode** [comment]
> I tried to test it with Purpur and the problem still exists.
Could this be related to Paper's new chunk system?

Works fine for me on both Paper and Purpur, so it's probably caused by one of your plugins

**Comment by xiaozhangup** [comment]
> > I tried to test it with Purpur and the problem still exists.
> > Could this be related to Paper's new chunk system?
> 
> Works fine for me on both Paper and Purpur, so it's probably caused by one of your plugins

I have Itemsadder on my server, I'll test it later and tell you the result

**Comment by xiaozhangup** [comment]
This is a problem caused by ItemsAdder, sorry.
