### ISSUE TITLE
[Bug] Nova locked my server thread

### ISSUE THREAD

**Issue by xiaozhangup** [xenondevs/Nova#184]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

This issue is about a specific plugin incompatibility.

### Plugin Version, Server Software, Server Version

0.11.6 git-Mirai-23 (MC: 1.19.2)

### Nova Addons and Versions

L0.2 M0.2.1 J0.1.4

### Observed/Actual behavior

When I started my server, suddenly the server stuck. So I used arthas to locate what was causing the problem and then found the problem.
![unknown](https://user-images.githubusercontent.com/68374769/196566300-5a9bb841-4ad9-4fc6-9862-76e112b15ce2.png)

### Steps to reproduce

1. Start the server.
Not every time will trigger at startup. But it is bound to trigger once in 24 hours

### Full server log

In fact, after he caused the main thread of the server to deadlock, no more logs appeared and the console was frozen.
[2022-10-18-19.log](https://github.com/xenondevs/Nova/files/9815745/2022-10-18-19.log)
![unknown](https://user-images.githubusercontent.com/68374769/196566336-151891a2-a8d8-4ff9-8836-ded6027c18e0.png)

**Comment by NichtStudioCode** [comment]
Fixed in 9a02e8688718d0fdc1fb16525a5953dcafbcaa50
