### ISSUE TITLE
[Bug] Can be placed above the height limitf

### ISSUE THREAD

**Issue by xiaozhangup** [xenondevs/Nova#186]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

This issue is about a specific plugin incompatibility.

### Plugin Version, Server Software, Server Version

0.11.6 git-Mirai-23 (MC: 1.19.2)

### Nova Addons and Versions

L0.2 M0.2.1 J0.1.4

### Observed/Actual behavior

https://streamable.com/gbwyev

### Steps to reproduce

Reaching the height ceiling position
Placing a machine

### Full server log

Null

### Errors

Null

**Comment by NichtStudioCode** [comment]
Thanks for reporting!
