### ISSUE TITLE
[Bug] Causes the note box to become useless

### ISSUE THREAD

**Issue by xiaozhangup** [xenondevs/Nova#187]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

This issue is about a specific plugin incompatibility.

### Plugin Version, Server Software, Server Version

0.11.6 git-Mirai-23 (MC: 1.19.2)

### Nova Addons and Versions

L0.2 M0.2.1 J0.1.4

### Observed/Actual behavior

The note box can only make one sound.
After I uninstalled Nova on my server, the note box became normal. But when I install Nova again, the problem appears again.

### Steps to reproduce

1. Place a noteblock

### Full server log

[latest.log](https://github.com/xenondevs/Nova/files/9818558/latest.log)

### Additional context

In the logs you will see that I hot loaded/unloaded Nova, which is the action I took to determine if the problem was caused by Nova.

**Comment by NichtStudioCode** [comment]
Works fine for me. Can the note block only output one specific tone, or does it make no sounds at all?

**Comment by xiaozhangup** [comment]
> Works fine for me. Can the note block only output one specific tone, or does it make no sounds at all?

only output one specific tone

**Comment by NichtStudioCode** [comment]
Try running `/nova debug updateChunkSearchId` and restarting your server. You should also consider enabling `use_agent` in the main config, if possible.

**Comment by xiaozhangup** [comment]
> Try running `/nova debug updateChunkSearchId` and restarting your server. You should also consider enabling `use_agent` in the main config, if possible.
> 
> If that doesn't work, it might be caused by other plugins on your server / your server software

When I enable the 'use_agent',the problem sloved.
