### ISSUE TITLE
[Bug] Nova tiles get unusable after using some CMI teleportation commands

### ISSUE THREAD

**Issue by AllayBreeze** [xenondevs/Nova#190]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

This issue is about a specific plugin incompatibility.

### Plugin Version, Server Software, Server Version

Nova: 0.11.7; Purpur: 1.19.2-build-1825; CMI: 9.2.4.7

### Nova Addons and Versions

Logistics: 0.2; Machines: 0.2.1; PoweredGear: 1.4

### Expected behavior

When using CMI commands such as /cmi:back or /cmi:home to teleport, nova tiles such as machines and cables near the tp location should work normally.

### Observed/Actual behavior

When players teleport into an unloaded chunk using commands above, most or all nova tiles at this chunk will become useless, not interactable anymore (or sometimes can be interacted for only one time).

Every time trying to interact with these tiles, an exception will be thrown at the console.

Cable connectors are most likely to get broken. After a teleportation usually all connectors will become not interactable.

Sometimes machines will lost all functions, and breaking tiles does not break the model at the same time.

After server restarts, broken tiles will be removed. 

### Steps to reproduce

1. Install CMI, CMILib and Nova
2. Go to a location far away from the spawn (I chose (1200, 66, 1200)) to place machines and cables
3. Teleport back to the spawn location and wait for the chunk to be unloaded
4. Use /cmi:back to get back to that chunk
5. And nova tiles in that chunk will get broken

### Full server log

https://pastebin.com/CNyWjBae

### Errors

[18:58:46] [Server thread/WARN]: [Nova] Task #44 for Nova v0.11.7 generated an exception
java.util.NoSuchElementException: No element of the map was transformed to a non-null value.
	at xyz.xenondevs.nova.tileentity.network.NetworkNode$DefaultImpls.getConnectedNode(NetworkNode.kt:50) ~[nova8104186001683864484.jar:?]
	at xyz.xenondevs.nova.tileentity.network.NetworkBridge$DefaultImpls.getConnectedNode(NetworkBridge.kt:9) ~[nova8104186001683864484.jar:?]
	at xyz.xenondevs.nova.tileentity.network.energy.EnergyBridge$DefaultImpls.getConnectedNode(EnergyBridge.kt:5) ~[nova8104186001683864484.jar:?]
	at xyz.xenondevs.nova.logistics.tileentity.Cable.getConnectedNode(Cable.kt:58) ~[?:?]
	at xyz.xenondevs.nova.logistics.tileentity.Cable$handleAttachmentHit$1.invoke(Cable.kt:290) ~[?:?]
	at xyz.xenondevs.nova.logistics.tileentity.Cable$handleAttachmentHit$1.invoke(Cable.kt:289) ~[?:?]
	at xyz.xenondevs.nova.tileentity.network.NetworkManagerImpl$init$1.invoke(NetworkManager.kt:185) ~[nova8104186001683864484.jar:?]
	at xyz.xenondevs.nova.tileentity.network.NetworkManagerImpl$init$1.invoke(NetworkManager.kt:172) ~[nova8104186001683864484.jar:?]
	at xyz.xenondevs.nova.util.SchedulerUtilsKt.runTaskTimer$lambda-2(SchedulerUtils.kt:28) ~[nova8104186001683864484.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1825]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.2.jar:git-Purpur-1825]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.2.jar:git-Purpur-1825]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.19.2.jar:git-Purpur-1825]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.2.jar:git-Purpur-1825]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.2.jar:git-Purpur-1825]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1825]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Additional context

Vanilla /tp command won't cause this issue.

I have only tried /cmi:back, /cmi:home and /cmi:tppos, and the first two can cause issues, but the last one didn't seem to.

I haven't been using solid blocks.

**Comment by NichtStudioCode** [comment]
Hi, thanks for the detailed report! While it is very likely that this is an issue on our side, we can't do much about it as CMI is a premium plugin, and we're therefore unable to do any testing with it. We've already tried to contact the dev about previous issues over a year ago, without any success.
Maybe reporting this issue to the CMI dev might get their attention.

**Comment by xiaozhangup** [comment]
> Hi, thanks for the detailed report! While it is very likely that this is an issue on our side, we can't do much about it as CMI is a premium plugin, and we're therefore unable to do any testing with it. We've already tried to contact the dev about previous issues over a year ago, without any success. Maybe reporting this issue to the CMI dev might get their attention.

There is no CMI on my server, but this happens anyhow.
Even https://github.com/xenondevs/Nova/issues/192

**Comment by idnthvn** [comment]
So we have been testing this on the server i play on.
Running PURPUR we lost logistic cables after a reboot. Teleported in and out of the chunk fine, unloaded loaded worked great until the reboot happened.
NOW,
we got rid of PURPUR and went with PAPER,
That fixed the REBOOT issue, HOWEVER the new issue is now when the chunk unloads and loads back up, (from teleporting),
that the cables become invalid.

**Comment by NichtStudioCode** [comment]
@idnthvn What Nova version did you test this on? There have been some significant changes to chunk loading in the last few release candidates. Could you check if this is still an issue with 0.12-rc4?

**Comment by idnthvn** [comment]
0.11.7 and all of the official add-ons of the current version too.
Now i am playing on the server that has these issues, i am not the owner,
on MY own server  i use Spigot, i do not use PAPER, or PURPUR, or other forks, i also am not using CMI for my teleportations. and i have zero issues.
Problem may lay with the chunks loading unloading with the forked versions of SPIGOT.......... I am going to get PAPER and try on my own server that has minimal plugins to see if i can replicate it.

**Comment by Norava** [comment]
Can confirm the same behavior occurs due to chunks loading and unloading here, using basic Essentials TP commands so assuming it's probably the chunks unloading that's causing it. Seeing the following in the console on /back ing
![image](https://user-images.githubusercontent.com/3203765/200126483-ede4eddd-008a-412c-909f-805c2aeb5c3f.png)

**Comment by NichtStudioCode** [comment]
> Can confirm the same behavior occurs due to chunks loading and unloading here, using basic Essentials TP commands so assuming it's probably the chunks unloading that's causing it. Seeing the following in the console on /back ing

Works fine for me on 0.12-rc5

**Comment by Norava** [comment]
Are there any prebuilt addons for rc5? I want to install to test but I'm not seeing any of the addons available for download and want to make sure I'm aligned with what ya'll are using (I'm unfamiliar with building jars! My apologies!)

**Comment by xiaozhangup** [comment]
> Are there any prebuilt addons for rc5? I want to install to test but I'm not seeing any of the addons available for download and want to make sure I'm aligned with what ya'll are using (I'm unfamiliar with building jars! My apologies!)

https://github.com/Nova-Addons

**Comment by NichtStudioCode** [comment]
> But there is a problem with one of the Logistics builds, which seems to be a github issue

Was related to GitHub caching, fixed now

**Comment by NichtStudioCode** [comment]
@AllayBreeze Could you check if this is still an issue on [0.12-rc7](https://github.com/xenondevs/Nova/releases/tag/0.12-rc7)?

**Comment by AllayBreeze** [comment]
Seems that it's fixed now. /back and /home will not break tiles anymore.
Thanks for your hard works to fix it!
