### ISSUE TITLE
[Request - BinaryAdapter]  Bukkit BlockFace adapter

### ISSUE THREAD

**Issue by brettsaunders21** [xenondevs/Nova#191]
### Class name

BlockFace

**Comment by ByteZ1337** [comment]
Enum's should already be covered by the [EnumBinaryAdapter](https://github.com/xenondevs/Cosmic-Binary-Format/blob/main/Cosmic-Binary-Format/src/main/kotlin/xyz/xenondevs/cbf/adapter/default/EnumBinaryAdapter.kt)
