### ISSUE TITLE
[Bug] Nova-0.12-rc3 Crystallizer can't be automated

### ISSUE THREAD

**Issue by Whitebrim** [xenondevs/Nova#195]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova-0.12-rc3

### Nova Addons and Versions

machines-0.3, Jetpacks-0.1.5, logistics-0.2.1

### Expected behavior

Crystallizer can be automated via cables. Cables removes only Star Crystal from the Crystallizer and puts only Block of Star Dust to process.

### Observed/Actual behavior

Cable is taking Block of Star Dust from the Crystallizer while it's being processed, so Crystallizer can't create any Star Crystal.

### Steps to reproduce

![image](https://user-images.githubusercontent.com/23287829/198860457-33358c7b-417a-4db7-b91f-ad6644efc894.png)
Set both cable's IOs to Input & Output mode.

### Full server log

Unnecessary

**Comment by NichtStudioCode** [comment]
This is intended behavior to incentivize the use of item filters.

However, there is also a side-config rework planned in 0.13 which would make this work without item filters.
