### ISSUE TITLE
[Bug] When server restart,some cables will break.

### ISSUE THREAD

**Issue by xiaozhangup** [xenondevs/Nova#196]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova 0.12 r4 git-Purpur-1832 (MC: 1.19.2)*

### Nova Addons and Versions

L0.2.1 M0.3 J0.1.5

### Expected behavior

No

### Observed/Actual behavior

The cable becomes a chain

### Steps to reproduce

1. Place some cable
2. Restart the server

### Full server log

No

**Comment by NichtStudioCode** [comment]
I cannot reproduce this. Did you test this on a fresh installation? Are there any errors in the console?

**Comment by MeanKid619** [comment]
Hey to reproduce this you need orefubscator installed, as for the server software we swapped from purpur to paper.

**Comment by xiaozhangup** [comment]
[2022-11-01-1.log](https://github.com/xenondevs/Nova/files/9905846/2022-11-01-1.log)

**Comment by xiaozhangup** [comment]
https://discordapp.com/channels/859080327096172544/1036733666937815060/1036733666937815060
