### ISSUE TITLE
[Bug] machines 0.3.1 crash

### ISSUE THREAD

**Issue by Whitebrim** [xenondevs/Nova#199]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova-0.12-rc5, 

### Nova Addons and Versions

logistics-0.2.2, Jetpacks-0.1.6, machines-0.3.1

### Observed/Actual behavior

Server crash on start

### Steps to reproduce

1. Update all addons and Nova
2. Start the server

### Full server log

https://mclo.gs/inX7f07

### Additional context

Feel free to request anything else. I've migrated from rc3 that was working on this setup

**Comment by NichtStudioCode** [comment]
Should be fixed now.
Just redownload Machines v0.3.1: https://github.com/Nova-Addons/Machines/releases/tag/0.3.1
