### ISSUE TITLE
[Bug] Server performance issues

### ISSUE THREAD

**Issue by Iseason2000** [xenondevs/Nova#20]
**Plugin Version and Server Software**
Plugin Version: Nova-0.4
Server Version: [purpur-1.17.1-1291](https://purpur.pl3x.net/)

**Describe the bug**
Excellent plugin, which is exactly what I wanted. So I couldn't wait to get it installed on my server.
But after about 5 minutes, The server's TPS has dropped from 20 to 8。(with 50 player)
![TIM图片20210731144829](https://user-images.githubusercontent.com/65019366/127731465-a9ad89d2-9aed-4d30-9e0c-bd07ce05b76e.jpg)
![TIM图片20210731144844](https://user-images.githubusercontent.com/65019366/127731466-5dfda395-1dba-4d34-b9d5-209310067ddc.png)
Wnen i check the timings report [https://timings.pl3x.net/?id=a513a32d2fb347dcb0650b4bb029e5cd#plugins](https://timings.pl3x.net/?id=a513a32d2fb347dcb0650b4bb029e5cd#plugins)
![image](https://user-images.githubusercontent.com/65019366/127731493-49105de8-160c-422c-91bf-32ed4451bba3.png)

**Another problem**
When I installed the plugin, I noticed that the  islandWorld([BskyBlock](https://bentobox.world/)) chunk are not being loaded correctly
![image](https://user-images.githubusercontent.com/65019366/127731644-4d42ebdd-01ac-46ff-b6ff-d2094fda5f0d.png)
![TIM图片20210731145909](https://user-images.githubusercontent.com/65019366/127731744-98247e0d-0664-4ca5-b557-560689a9eb44.jpg)
![TIM图片20210731145915](https://user-images.githubusercontent.com/65019366/127731746-57b01b1c-3902-4390-9423-eeef219a70b4.png)

**This problem was fixed after I removed the plugin(Nova0.4)**

**Errors**
No error message

**And other suggestions**
* reload command
* Method of disabling the machine

Expect to be better

Sorry for my pool English(Not a native language)

**Comment by NichtStudioCode** [comment]
Thanks for reporting!
We're currently working on rewriting the tile entity system, which will hopefully reduce lag.
The big lag spike you're experiencing is probably caused by a timer that checks all vanilla tile entities for changes without block updates. We will look into improving the performance of this function.
About the chunks not loading at all, we're not quite sure what causes this, but it seems to only affect Purpur servers.

**Comment by ByteZ1337** [comment]
Performance issues should be fixed in the upcoming 0.5 update.
