### ISSUE TITLE
[Bug] shulker box break problem

### ISSUE THREAD

**Issue by xiaozhangup** [xenondevs/Nova#202]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova 0.12.1 Purpur1845

### Nova Addons and Versions

*

### Observed/Actual behavior

All items in shulker box disappear

### Steps to reproduce

1. Place shulker box
2. Add some items to it
3. Break the shulker box

### Full server log

*

**Comment by NichtStudioCode** [comment]
Works fine for me

https://user-images.githubusercontent.com/51272202/202853752-3706d688-ab1e-43cf-902d-a36eba5ae654.mp4

**Comment by xiaozhangup** [comment]
> Works fine for me
> javaw_WCY5W0TIJW.mp4

I will do more test later

**Comment by xiaozhangup** [comment]
> Works fine for me
> javaw_WCY5W0TIJW.mp4

My bad,sorry
