### ISSUE TITLE
[Bug] Cables randomly stop working

### ISSUE THREAD

**Issue by xiaozhangup** [xenondevs/Nova#203]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova 0.12.1 Purpur1845

### Nova Addons and Versions

Logistics: 0.2.2, Machines: 0.3.1, Jetpacks: 0.1.6

### Expected behavior

No

### Observed/Actual behavior

1.Start the server and running for a while
2.the pipeline suddenly stop running
3.run /nova debug reloadNetwork
4.everything become normaly

### Steps to reproduce

1.Start the server and running for a while
2.the pipeline suddenly stop running
3.run /nova debug reloadNetwork
4.everything become normaly

### Full server log

[latest.log](https://github.com/xenondevs/Nova/files/10047243/latest.log)

**Comment by xiaozhangup** [comment]
New:
even when player afk at that place,pipeline also will suddenly stop running

**Comment by sarhatabaot** [comment]
Can confirm this also happen to some of my players. 
Running Nova 0.12.6 Purpur-1858
Addons: Logistics 0.2.2, Machines: 0.3.1, Jetpacks: 0.1.6

**Comment by VulcanoSoftware** [comment]
pls fix this issue fast, i used chuckloaders do let the cables work, but it doesn't. my players are rage quiting because of this bug.

we don't need new features but bug fixes

first do bug fixes, then add new features

**Comment by xiaozhangup** [comment]
> pls fix this issue fast, i used chuckloaders do let the cables work, but it doesn't. my players are rage quiting because of this bug.
> 
> we don't need new features but bug fixes
> 
> first do bug fixes, then add new features

Please don't worry, fixing bugs is far from easy as you might think.

**Comment by NichtStudioCode** [comment]
I've done some changes that should fix this in 0.13-alpha.1. It'd be great if someone could test if this still issue occurs. (Be careful though, as it's an alpha)

**Comment by NichtStudioCode** [comment]
Do you still encounter this issue? @sarhatabaot @xiaozhangup

**Comment by sarhatabaot** [comment]
Not anymore. Haven't experienced this in a while.

**Comment by NichtStudioCode** [comment]
> Not anymore. Haven't experienced this in a while.

Even before updating to 0.13?

**Comment by sarhatabaot** [comment]
> > Not anymore. Haven't experienced this in a while.
> 
> Even before updating to 0.13?

I can't say for certain. Since it only happen sometimes, but my players stopped reporting this when I updated to one of 0.13 alpha versions.
