### ISSUE TITLE
[Bug] No water when breaking ice block

### ISSUE THREAD

**Issue by xiaozhangup** [xenondevs/Nova#205]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova 0.12.4 Purpur

### Nova Addons and Versions

No

### Observed/Actual behavior

No water when breaking ice blocks

### Steps to reproduce

[Uploading 录屏 2022-11-23 21-14-28.webm…]()

### Full server log

No

**Comment by NichtStudioCode** [comment]
Fixed in 1f6bbb2072bdb1c04168198a8f754003a40f4e22
