### ISSUE TITLE
[Bug] VacuumChest lag my server

### ISSUE THREAD

**Issue by xiaozhangup** [xenondevs/Nova#207]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova: v0.12, Paper: git-Paper-270 

### Nova Addons and Versions

Machines v0.3.1, Logistics v0.2.2, Jetpacks v0.1.6

### Observed/Actual behavior

My server lag

### Steps to reproduce

I don't know why,but my server have many drops.
https://spark.lucko.me/KiBqBpU40a

### Full server log

[latest.log](https://github.com/xenondevs/Nova/files/10089105/latest.log)

**Comment by NichtStudioCode** [comment]
You can set up [tile-entity limits](https://xenondevs.xyz/docs/nova/admin/configuration/#tile-entity-limits) to prevent your players from placing too many tile-entities.

**Comment by xiaozhangup** [comment]
> You can set up [tile-entity limits](https://xenondevs.xyz/docs/nova/admin/configuration/#tile-entity-limits) to prevent your players from placing too many tile-entities.

But,no one VacuumChest on my server
