### ISSUE TITLE
[Bug] Duping jetpack using armored jetpack crafting recipe

### ISSUE THREAD

**Issue by CraftCoderr** [xenondevs/Nova#208]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova: v0.12.3, Paper: git-Paper-270 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: e22dacf)

### Nova Addons and Versions

Machines v0.3.1, Logistics v0.2.2, Jetpacks v0.1.6

### Expected behavior

Armored jetpack crafted, ingredients used. And crafted jetpack goes to main inventory section.

### Observed/Actual behavior

Armored jetpack crafted, ingredients not used (say duped). And crafted jetpack immediately weared (goes to armor inventory section).

### Steps to reproduce

1. Place armored jetpack ingredients (jetpack + corresponding chestplate) in player's inventory crafting section.
2. Click+Shift on crafting result (resulting armored jetpack).
3. Close inventory or move ingredients from crafting slots to main inventory.

### Full server log

No errors

**Comment by NichtStudioCode** [comment]
I cannot reproduce this.

https://user-images.githubusercontent.com/51272202/204044207-e1d489c0-a844-484f-85c4-f9eb93d7e586.mp4

Although probably unrelated, you're not on the latest version of either Nova or Paper.
You also didn't attach the server log.

**Comment by CraftCoderr** [comment]
To reproduce you should use player's crafting inventory, not workbench.
![2022-11-25_21 55 28](https://user-images.githubusercontent.com/7105938/204046752-a65b51f4-13a7-43b6-872d-2d1bf5186378.png)
![2022-11-25_21 55 40](https://user-images.githubusercontent.com/7105938/204046771-1e47e737-a78a-4f93-99f0-c17c0a7e4b99.png)
![2022-11-25_21 55 45](https://user-images.githubusercontent.com/7105938/204046778-ca7daccc-b827-4105-bdb8-8171fa9ceb46.png)

**Comment by NichtStudioCode** [comment]
> To reproduce you should use player's crafting inventory, not workbench.

Oops, sorry, seems like I read over that part.
