### ISSUE TITLE
[Bug] will not package bar.png from other resource packages

### ISSUE THREAD

**Issue by xiaozhangup** [xenondevs/Nova#209]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova 0.12.5 Purpur

### Nova Addons and Versions

No

### Observed/Actual behavior

will not package bar.png from other resource packages

### Steps to reproduce

1. Add some pack with bar.png
2. Make Nova regen the pack

### Full server log

Not need

**Comment by xiaozhangup** [comment]
![图片](https://user-images.githubusercontent.com/68374769/204092960-be300961-7f1d-4a31-845b-04e5afd0a851.png)
This is the IA' pack

![图片](https://user-images.githubusercontent.com/68374769/204092982-24b1fb28-b388-429b-995a-78ded0efe5d8.png)
After Nova pack

**Comment by NichtStudioCode** [comment]
Fixed in f69dbc21f78da085fe343a6199bdb731d25991d4 and will be included in 0.13
