### ISSUE TITLE
[Bug] The cable will stop working

### ISSUE THREAD

**Issue by xiaozhangup** [xenondevs/Nova#210]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova 0.12.5 Purpur

### Nova Addons and Versions

Machines v0.3.1, Logistics v0.2.2, Jetpacks v0.1.6

### Observed/Actual behavior

The cable will stop working

### Steps to reproduce

![图片](https://user-images.githubusercontent.com/68374769/204131092-b9aa3736-b492-4f90-8f19-795fb648f8cb.png)

### Full server log

[latest.log](https://github.com/xenondevs/Nova/files/10098069/latest.log)

**Comment by NichtStudioCode** [comment]
Please do not open new issues every time you encounter the same bug again. If you have new information, amend #203.

**Comment by xiaozhangup** [comment]
> Please do not open new issues every time you encounter the same bug again. If you have new information, amend #203.

Sorry, I forgot.
