### ISSUE TITLE
Crash on init

### ISSUE THREAD

**Issue by ErfinderLabyrinth** [xenondevs/Nova#215]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [x] I am using an official build of Nova.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova: 0.12.9, Spigot: Paper (MC: 1.19.3)

### Nova Addons and Versions

no

### Expected behavior

Nova sets up successfully

### Observed/Actual behavior

Just put the plugin on my server (there is no other plugin on the server) and got the error

### Steps to reproduce

1. Pack the plugin on the server
2. Lucky for the error to occur

### Full server log

[log.txt](https://github.com/xenondevs/Nova/files/10262268/log.txt)

### Errors

[log.txt](https://github.com/xenondevs/Nova/files/10262272/log.txt)

### Additional context

The server was hosted on Ploudos

**Comment by NichtStudioCode** [comment]
Your server fails to connect to our maven repository (https://repo.xenondevs.xyz). Since this doesn't seem to be an issue on our side, it's likely that the connection is blocked by a firewall. You'd need to contact your hoster in order to resolve this issue.

Please also keep everything in English here :)

**Comment by ErfinderLabyrinth** [comment]
> Your server fails to connect to our maven repository (https://repo.xenondevs.xyz). Since this doesn't seem to be an issue on our side, it's likely that the connection is blocked by a firewall. You'd need to contact your hoster in order to resolve this issue.
> 
> Also, please keep everything in English here :)

then give me please the Link to the .pom file of xyz.xenondevs:minecraft-asset-downloader:pom:1.2 before i go to the server hoster to see, that error is realy client-side

**Comment by ByteZ1337** [comment]
https://repo.xenondevs.xyz/releases/xyz/xenondevs/minecraft-asset-downloader/1.2/minecraft-asset-downloader-1.2.pom
