### ISSUE TITLE
[Request - Generic] Font File Merging

### ISSUE THREAD

**Issue by Entrodor** [xenondevs/Nova#228]
### Describe your feature request.

whilst trying to get an emoji plugin to work, Nova gives the following error (truncated to remove irrelevant info) \assets\minecraft\font\default.json: File type cannot be merged

i know theres another program that can do it, but would be nice to just let Nova handle everything to do with resourcepacks

**Comment by NichtStudioCode** [comment]
Will be fixed in `0.13`.
