### ISSUE TITLE
Jatpack render

### ISSUE THREAD

**Issue by Ielelele29** [xenondevs/Nova#23]
**Plugin Version and Server Software**
Minecraft server verison: git-Paper-90 (1.17.1)
Plugin version: 0.4.1

**Describe the bug**
![2021-08-15_12 58 35](https://user-images.githubusercontent.com/76882886/129476968-a59bec12-5777-4130-9eed-adfcf420f377.png)

**To Reproduce**
1. Watch a player (not yourself) with jetpack

**Expected behavior**
The jetpack in the exact position

**Errors**
No error in console

**Comment by ByteZ1337** [comment]
Already fixed in the next update
