### ISSUE TITLE
[Machines Addon] Count of some ingredients in electric brewing stand is increasing

### ISSUE THREAD

**Issue by MushroomMif** [xenondevs/Nova#235]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova: 0.12.16, Purpur: git-Purpur-1924 (MC: 1.19.3)

### Nova Addons and Versions

Machines: 0.3.2

### Expected behavior

Ingredients count are stay the same

### Observed/Actual behavior

Ingridients count arent stay the same

### Steps to reproduce

1. Place electric brewing stand
2. Configure a potion in it
3. Exit the potion creation menu
4. Look at ingredients count
5. Go again in this menu and exit it again
6. See that count of some ingredients has been increased compared to the previous time

Alternatively:
1. Place electric brewing stand
2. Configure a potion in it
3. Exit the potion creation menu
4. Look at ingredients count
5. Unload the chunk containing this electric brewing stand
6. Load it back
7. See that count of some ingredients has been increased compared to the previous time

### Full server log

https://pastebin.com/umeHLuLB

### Additional context

I'm not sure that I report it in the right place but I cant open an issue in Machines github page.
You can find demonstration of this bug here: https://youtu.be/DsTkClPR_vM

**Comment by NichtStudioCode** [comment]
Fixed in Nova-Addons/Machines@7348894ef1520394378eeb6ca814ed2e788d6370
