### ISSUE TITLE
Stuck on Calculating char sizes

### ISSUE THREAD

**Issue by Creepdasheep** [xenondevs/Nova#237]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

There are no other plugins running on my server when I logged the issue after it was first found

### Plugin Version, Server Software, Server Version

Nova v0.12.16 git-Purpur-1931 (MC: 1.19.3)*

### Nova Addons and Versions

None (for testing reasons, same issue with addons machines and logistics)

### Expected behavior

Let players join and finish the server booting up

### Observed/Actual behavior

Will not let players join and stuck on setting up

### Steps to reproduce

Start up the server with nova, no add-ons needed

### Full server log

https://pastebin.com/rWYWNLCD

### Errors

None

### Additional context

Same outcome with Paper, Issue does not happen when tested on a Ubuntu distro, the issue happens on windows

**Comment by Creepdasheep** [comment]
Same outcome with Paper, Issue does not happen when tested on a Ubuntu distro, the issue happens on windows

**Comment by NichtStudioCode** [comment]
How long did you wait?

**Comment by Creepdasheep** [comment]
I waited 20 minutes.

**Comment by Creepdasheep** [comment]
Tried it with my laptop that has oracle java 17 instead of adoptium java 17 and it works instantly.
