### ISSUE TITLE
All cables really laggy

### ISSUE THREAD

**Issue by Ielelele29** [xenondevs/Nova#24]
**Plugin Version and Server Software**
Minecraft server verison: git-Paper-90 (1.17.1)
Plugin version: 0.4.1

**Describe the bug**
1) Placing some cables a big amount of armor stands were summoned causing tps drop
2) If you place any block (like common stone) or summon an entity (with spawn eggs) near to some cables the server has a lag spike

**To Reproduce**
1. Place some connected cables (like 50)
2. Place any block or summon any mob near to the cables
3. Get lag spike

**Screenshots**
Cable placed in this way: 
![2021-08-15_17 09 17](https://user-images.githubusercontent.com/76882886/129483357-cf84f50b-db12-4ded-8a07-3836e028fe9d.png)
When place block or summon mobs: 
![image](https://user-images.githubusercontent.com/76882886/129483437-6e70c779-d4a2-421e-8580-1713ba9bcee7.png)

Timings:
![image](https://user-images.githubusercontent.com/76882886/129483456-e5bd5d95-014f-4bfd-b6ed-fe0b0d9c4175.png)
https://timings.aikar.co/?id=36985ae522cc4b52939845d51f798569

**Comment by ByteZ1337** [comment]
ArmorStand performance should be fixed with the next update, since they're completely packet based.

**Comment by Ielelele29** [comment]
Also the client performance?
Currently if I'm close to the cables the armor stands make me lag also if I can't see them (gamemode survival, not gamemode spectator)

**Comment by NichtStudioCode** [comment]
> Also the client performance?
> Currently if I'm close to the cables the armor stands make me lag also if I can't see them (gamemode survival, not gamemode spectator)

Yes, we've also optimized the cables models, so fewer armor stands are needed, which will improve performance.
