### ISSUE TITLE
Conflict with plugins using spigot's library loader

### ISSUE THREAD

**Issue by sarhatabaot** [xenondevs/Nova#240]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

This issue is about a specific plugin incompatibility.

### Plugin Version, Server Software, Server Version

Nova v0.13-alpha.1, git-Purpur-1957 (MC: 1.19.4)*

### Nova Addons and Versions

jetpacks v0.1.8-RC, simple_upgrades v1.0-RC, logistics v0.2.4-RC, machines v0.4-RC

### Expected behavior

1. Plugin "ConfigurableMenus" should load.

### Observed/Actual behavior

The plugin "ConfigurableMenus" cannot load class net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl although it uses spigot's library loading feature.
See error & log linked below.

If I remove Nova it loads properly.

### Steps to reproduce

1. Install [ConfigurableMenus](https://github.com/Lapzupi/ConfigurableMenus/releases/tag/0.3.0).
2. Run the server.

### Full server log

https://pastebin.com/3QJEZPA4

### Errors

https://pastebin.com/sDnkqTvq

**Comment by NichtStudioCode** [comment]
Is it intentional that ConfigurableMenus is also a fat jar that includes kyori-adventure's classes?
![image](https://user-images.githubusercontent.com/51272202/231430228-c24e6e62-fa3a-4713-9816-4c361e04708f.png)

Anyway, this still shouldn't happend, I'll look into it

**Comment by sarhatabaot** [comment]
> Is it intentional that ConfigurableMenus is also a fat jar that includes kyori-adventure's classes? ![image](https://user-images.githubusercontent.com/51272202/231430228-c24e6e62-fa3a-4713-9816-4c361e04708f.png)
> 
> Anyway, this still shouldn't happend, I'll look into it

Not intentional. Uhrm, I will fix that. 
Anyways, thanks for the help!

**Comment by sarhatabaot** [comment]
Perfect, thank you!
