### ISSUE TITLE
Furnace generator not working!

### ISSUE THREAD

**Issue by Vlad0Crystal** [xenondevs/Nova#241]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova v0.13-alpha.4, paper-1.19.4-519, minecraft 1.19.4

### Nova Addons and Versions

Jetpacks-0.1.8-RC, Logistics-0.2.4-RC.2, Machines-0.4-RC.2, Simple-Upgrades-1.0-RC, Vanilla-Hammers-1.0-RC

### Expected behavior

A-furnace generator is not working. It does not consume any fuel. And there is no configuration to find out what it consumes. The configuration is very small and general.

### Observed/Actual behavior

Even if you put down the fuel, it's impossible.

### Steps to reproduce

Place the generator and try to light the coals.

### Full server log

https://pastebin.com/VrNTD4WN

### Errors

No, and that's the problem.

### Additional context

 Please implement settings for items that can be used. At least a white list.

**Comment by Vlad0Crystal** [comment]
https://user-images.githubusercontent.com/47213885/234138644-0bc3291e-d554-49b4-a5b3-4cdeeb5965b1.mp4

**Comment by ByteZ1337** [comment]
Fixed in Machines v0.4-RC.3
