### ISSUE TITLE
Console error spam when searching.

### ISSUE THREAD

**Issue by sarhatabaot** [xenondevs/Nova#247]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova v0.13-alpha.9, Purpur git-Purpur-1967 (1.19.4)

### Nova Addons and Versions

jetpacks v0.1.8-RC, simple_upgrades v1.0-RC, logistics v0.2.4-RC.2, machines v0.4-RC.5

### Observed/Actual behavior

Error spam in the console.

### Steps to reproduce

1. Run /nova items
2. Click on the search button
3. Go to the second page
4. **Quickly** search something.

### Full server log

https://mcpaste.io/49924b8b54031283

### Errors

https://pastebin.com/Rk7W8E5h

### Additional context

Also, maybe a different issue, but the "search for an item" text is outside of the gui.
https://puu.sh/JG75f/70d40c7851.png

**Comment by NichtStudioCode** [comment]
> Also, maybe a different issue, but the "search for an item" text is outside of the gui.

Different issue, but this should be fixed after running the new debug command `/nova debug invalidateCharSizes` and then `/nova resourcePack create`
