### ISSUE TITLE
Safari Net (Mob Imprisonement Tool)

### ISSUE THREAD

**Issue by Ielelele29** [xenondevs/Nova#25]
**Potential name of the block**
Safari Net or Mob Imprisonement Tool (like the Industrial Foregoing item)

**Describe the block.**
This can be an object with the function of the actual glass bottle (bottled mob). I think that can be useful have a different item from glass bottle for catch a mob. Moreover in this way we can have a different and maybe harder recipe for the "bottled mob".

**Comment by Sheikins** [comment]
I agree, this is far too simple and can get overused very quickly. Maybe even add the fact that we can only recover the mob if it only has - 20% health left to prevent catching mobs that have a lot of health easily.
