### ISSUE TITLE
exception connecting:quietexception : unexpected packet reveived during server login process! 

### ISSUE THREAD

**Issue by zetapin** [xenondevs/Nova#253]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova 0.13 paper 1.19.4 #all (i tested alls 1.19.4)

### Nova Addons and Versions

logistic, machines, jetpacks, simple upgrades (all latest versiones)

### Observed/Actual behavior

Users can connect fine, the problem is when you disconnect and try to connect again, the following error pops up:
exception connecting:quietexception : unexpected packet reveived during server login process! 52b1040c1b00000000000000003f21e6

### Steps to reproduce

connect and disconnect

### Full server log

no error appears in the console, if I remove the addon machines, no error occurs, the error is in the addon machines

### Errors

no error appears in the console, if I remove the addon machines, no error occurs, the error is in the addon machines

### Additional context

if I remove the addon machines, no error occurs, the error is in the addon machines

**Comment by NichtStudioCode** [comment]
"Full server log" is not an optional field. Regardless of exceptions, you should upload your server log here

> paper 1.19.4 #all (i tested alls 1.19.4)

I doubt you've tested this on all 97 paper builds

> logistic, machines, jetpacks, simple upgrades (all latest versiones)

Please provide actual version numbers

**Comment by zetapin** [comment]
Server log: https://pastebin.com/h02B3QsJ
server version: paper-1.19.4-543
Nova addons and versions:
Jetpacks-0.1.8.jar
Logistics-0.2.4.jar
Machines-0.4.jar ([Machines v0.4.1](https://github.com/Nova-Addons/Machines/releases/tag/0.4.1))
Simple-Upgrades-1.0.jar

**Comment by AllayBreeze** [comment]
I seem to figure out that it's caused by some kind of Machines & Logistic tiles. If a player join and there're these kinds of tiles near the player, this issue will occur.
Wind Turbines always cause this issue. Some working machines (Tree Factory, Quarry, Star Collector, and mayby more) can also cause it. Maybe the moving model of these tiles are the key to this problem.

**Comment by AllayBreeze** [comment]
Yes it works without issues now. Thanks for your timely works to fix recent issues!
