### ISSUE TITLE
Breaking Nova blocks or tiles doesn't cause block updates to nearby blocks

### ISSUE THREAD

**Issue by AllayBreeze** [xenondevs/Nova#258]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova 0.14-alpha.3, git-Purpur-1995 (MC: 1.20.1)

### Nova Addons and Versions

Vanilla Hammers§f, Jetpacks§f, Simple Upgrades§f, Logistics§f, Machines

### Expected behavior

When breaking Nova blocks or tiles, nearby blocks should receive updates (e.g. water should flow, attached glow lichen should break)

### Observed/Actual behavior

Breaking Nova blocks or tiles won't update nearby blocks.
Water will not flow into it and attached lichens won't break.

https://github.com/xenondevs/Nova/assets/108282297/1902f4ac-4a7d-4911-a441-98e501f9e22e

https://github.com/xenondevs/Nova/assets/108282297/d8adec06-a191-48b7-9959-78370f88f652

### Steps to reproduce

1. Place a nova block or tile near a water (or Place a lichen attached to the block or tile);
2. Break the block or tile, the water won't flow, or the lichen won't break.

### Full server log

https://pastebin.com/Q6TAapTZ

**Comment by NichtStudioCode** [comment]
Block updates have actually been intentionally disabled in 23d997f89a9bee21a2a0606971d646da281e60db because they caused other issues. We will revisit this in the future (probably during the planned rewrite of Nova's world format and block states), but it's not a priority right now.

**Comment by NichtStudioCode** [comment]
Will be fixed in 0.17
