### ISSUE TITLE
Autofisher doesn't fish

### ISSUE THREAD

**Issue by Ielelele29** [xenondevs/Nova#26]
**Plugin Version and Server Software**
Minecraft server verison: git-Paper-90 (1.17.1)
Plugin version: 0.4.1

**Describe the bug**
The autofisher doesn't fish

**To Reproduce**
1. Place an autofisher with Creative Power Cell above
2. Wait 600 ticks and than throw an error in console

**Errors**
![image](https://user-images.githubusercontent.com/76882886/129494507-2c43b50e-fbf9-471a-8a30-b09710a0842d.png)

**Screenshots**
![2021-08-16_00 31 12](https://user-images.githubusercontent.com/76882886/129494607-ab2f87d0-507e-4f98-8268-53c3766fe0b5.png)

**Comment by ByteZ1337** [comment]
Your paper version is completely outdated. Update your server software before opening issues. https://github.com/PaperMC/Paper/issues/6367
