### ISSUE TITLE
Fluid is broken in many aspects

### ISSUE THREAD

**Issue by AllayBreeze** [xenondevs/Nova#260]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova 0.14-alpha.3, git-Purpur-1995 (MC: 1.20.1)

### Nova Addons and Versions

None

### Expected behavior

Flowing fluid should pull entities away, most mobs should float onto the water, water should extinguish fires on entities, lava should damage mobs and destroy most dropped items.

### Observed/Actual behavior

Flowing fluid doesn't pull entities away (both water and lava, dropped items also not, though the client will try to perdict this), all mobs don't float onto the water, water doesn't extinguish fires on entities, lava doesn't damage mobs and destroy most dropped items.

Maybe also more fluid bugs. In a word, fluid is broken.

### Steps to reproduce

1. Create a stream of flowing water and flowing lava.
2. Summon entities onto the fluid, they won't get pushed, and won't be damaged or destroyed by lava.
3. Put ignited entity into the water, the water won't extinguish the fire.
4. Create a pool with 2 or more blocks deep, Summon mobs onto it, mobs won't float up.

### Full server log

https://pastebin.com/DVQpLW3S

**Comment by NichtStudioCode** [comment]
Users have reported that this is a purpur specific issue, so a workaround would be using paper until this is fixed
