### ISSUE TITLE
Nova Recipe Fallback 0 on ItemsAdder item

### ISSUE THREAD

**Issue by Teenkung123** [xenondevs/Nova#263]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

This issue is about a specific plugin incompatibility.

### Plugin Version, Server Software, Server Version

Nova 0.14.2, ItemsAdder 3.5.0c, git-Purpur-2004 (MC: 1.20.1) 

### Nova Addons and Versions

Jetpacks-0.1.10, Logistics-0.2.5-RC.1, Machines-0.4.3, Simple-Upgrades-1.1

### Observed/Actual behavior

When Nova load it's recipe folder and found ItemsAdder in that file it should not throw an error recipe fallback 0 because 
net.minecraft.ResourceKeyInvalidException: Non [a-z0-9/._-] character in path of location

### Steps to reproduce

1. Install Nova and ItemsAdder
2. Put ItemsAdder item into nova's recipe folder
3. Restart / Reload the recipes
4. and there the error in console

### Full server log

The Error starts at line 3709-5681

[logs.txt](https://github.com/xenondevs/Nova/files/11949903/logs.txt)

**Comment by NichtStudioCode** [comment]
> [19:06:04] [Server thread/ERROR]: [Nova] Could not load recipe in file plugins\Nova\recipes\machines\pulverizer\ores\Bloodstone\bloodstone_crystal.json (recipe fallback 0)
net.minecraft.ResourceKeyInvalidException: Non [a-z0-9/._-] character in path of location: nova:Bloodstone.bloodstone_crystal

You cannot have upper case characters in recipe ids - and since these ids are constructed from the directory path, you cannot have upper case characters there either.
