### ISSUE TITLE
The tileEntity#getDrops method doesn't return the name of the Nova block or item

### ISSUE THREAD

**Issue by steve4744** [xenondevs/Nova#264]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova: 0.14.2, Paper version git-Paper-63 (MC: 1.20.1) 

### Nova Addons and Versions

Logistics: 0.2.6, Machines: 0.4.3, Simple-Upgrades: 1.1

### Expected behavior

The `tileEntity#getDrops(true)` method should return the name of the Nova block or item.

### Observed/Actual behavior

The method returns `SHULKER_SHELL` instead of the name of the Nova block

![image](https://github.com/xenondevs/Nova/assets/6975392/a8717f77-5c8b-47ce-be45-13ed5138e7ca)

### Steps to reproduce

1. place a Planter (or any other Nova block)
2. optionally place items (seeds) in it
3. get the drops from the tile entity at that location
```
TileEntity tileEntity = manager.getTileEntity(loc);
tileEntity.getDrops(true).forEach(i -> {
	Bukkit.getLogger().info("string = " + i.getType().toString());
	Bukkit.getLogger().info("is = " + i);
});
```
4. check console messages
```
[21:09:51 INFO]: string = SHULKER_SHELL
[21:09:51 INFO]: is = ItemStack{SHULKER_SHELL x 1, UNSPECIFIC_META:{meta-type=UNSPECIFIC, internal=H4sIAAAAAAAA/x2LXQ5AMBAGv/XbNB5cwTXcwCmkWDRhiZakt6fmbZIZDWhkcjxGIbET6t2MqxV27bkZ8XylyN09dBMiJVRM+3GYP2uI/pNIe7sxi7c+VEQFC19LSAh4Adi6MT9fAAAA}}
[21:09:51 INFO]: string = CARROT
[21:09:51 INFO]: is = ItemStack{CARROT x 2}
[21:09:51 INFO]: string = BEETROOT_SEEDS
[21:09:51 INFO]: is = ItemStack{BEETROOT_SEEDS x 5}
```

### Full server log

https://pastebin.com/tNj0weHe

**Comment by NichtStudioCode** [comment]
1. Material is an enum
2. The item display name is applied on a packet level

You can get the localized name via ``NovaItem#getLocalizedName``
