### ISSUE TITLE
Auto merge resource pack not working?

### ISSUE THREAD

**Issue by ignorant-wolf** [xenondevs/Nova#266]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

This issue is about a specific plugin incompatibility.

### Plugin Version, Server Software, Server Version

Nova 0.14.2, Paper 1.20.1, MC 1.20.1

### Nova Addons and Versions

All of em

### Expected behavior

As far as I can understand it NOVA can auto merge resource packs from other mods, I only have one mod that requires a resource pack, the mod "vane". I enter the command "vane generate_resource_pack" in my servers console to generate its resource pack. I than put that pack (which is a zip file) into "plugins/Nova/resource_pack/base_packs/" as per the setup guide. Now, unless its simply not compatible for some reason, when I restart my server, nothing happens. I force a re-download and still nothing as far as I can tell. The mod vane works, its just missing all the textures and what not for many of the items it adds. Am I just missing something?

### Observed/Actual behavior

Nothing

### Steps to reproduce

Put a mods resource pack into the proper folder for NOVA
Start or restart server
Load up minecraft
Log into server
???

### Full server log

https://pastebin.com/C62pnQX1

### Additional context

I wasn't sure where else I could ask this so here's hoping here is okay. Anyway...
Perhaps the problem is me and my ignorance, but I've been reading and searching and researching this for the past few days. I'm just lost on this.

**Comment by NichtStudioCode** [comment]
You'll need to run `/nova resourcePack create` to regenerate the resource pack with the base packs.

**Comment by ignorant-wolf** [comment]
Well that did it, thank you. Perhaps I just missed it somewhere, but it would have been nice if this could have been mentioned in the set up guide or something. Anyway, sorry for the bother but thank you very much for your time and help, it is appreciated.

**Comment by NichtStudioCode** [comment]
Yeah, it wasn't really made clear in the setup guide before, but I've added that now 👍
