### ISSUE TITLE
Duplication Bug working with nova item recipes.

### ISSUE THREAD

**Issue by YusufKGD** [xenondevs/Nova#272]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova-0.14.7 , Purpur , 1.20.1

### Nova Addons and Versions

Jetpacks-0.1.10 , Logistics-0.2.6 , Machines-0.4.3 , Simple-Upgrades-1.1 , Vanilla-Hammers-1.2

### Expected behavior

I found duplication bug for nova item recipes.
This error is actually very simple and I would expect it not to happen.

### Observed/Actual behavior

I found a duplication bug  on nova.
I have an error video but I couldn't upload it to this site.
Short video of this error:
https://youtu.be/bkFjtt6T8ow

### Steps to reproduce

1) Open recipe book.
2) Select uncraftable items.
3)Put any item in 2x2 crafting.
4)And just click nova item recipes.
5)Booom you are duplicated many items.

### Full server log

I couldn't provide the logs :(

### Errors

Nothing errors on console.

### Additional context

Video for bug:
https://youtu.be/bkFjtt6T8ow

**Comment by NichtStudioCode** [comment]
Thanks for reporting

**Comment by YusufKGD** [comment]
Not problem :)

**Comment by YusufKGD** [comment]
I don't want to bother you but when will the bug be fixed?

**Comment by NichtStudioCode** [comment]
The patch has been released 5 hours ago: https://github.com/xenondevs/Nova/releases/tag/0.14.9
