### ISSUE TITLE
Block placer does not consume energy

### ISSUE THREAD

**Issue by CptbeffHeart** [xenondevs/Nova#279]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Check for plugin incompatibilites

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova-0.14.10

### Nova Addons and Versions

Machines-0.1.3

### Expected behavior

The block placer doesn't consumes energy

xyz.xenondevs.nova.machines.tileentity.world.BlockPlacer
The function placeBlock() never return true
You should return true after line 48

### Observed/Actual behavior

Block placer doesn't consume energy

### Steps to reproduce

Use block placer

### Full server log

No log

**Comment by NichtStudioCode** [comment]
Fixed in Nova-Addons/Official-Addons@d5b729e9953ada5e6e5027645ed0a550af6f3895
