### ISSUE TITLE
Custom Resource Pack DL for serverside Bedrock

### ISSUE THREAD

**Issue by naruofa** [xenondevs/Nova#28]
I'd like to be able to download the Custom Resource Pack needed to play on Bedrock so I can add it to my Java-Bedrock server.

You don't need to do anything to the mod; I just need a Bedrock Resource Pack made if possible so I can install the Resource Pack on my Bedrock Edition then add it to the server so others can download it when joining.

**Comment by ByteZ1337** [comment]
Bedrock isn't supported. See #21
