### ISSUE TITLE
resource pack randomly stopped working

### ISSUE THREAD

**Issue by ND2009** [xenondevs/Nova#285]
![2023-10-02_20 34 31](https://github.com/xenondevs/Nova/assets/109348907/6c048898-6974-493a-9286-ffad62c8b74e)
![2023-10-02_20 34 42](https://github.com/xenondevs/Nova/assets/109348907/e05aeac1-f5a8-443d-a929-9be39368e359)
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Check for plugin incompatibilites

This issue is about a specific plugin incompatibility.

### Plugin Version, Server Software, Server Version

paper 1.20.1

### Nova Addons and Versions

all official nova addons

### Expected behavior

the resource pack should work and be hosted so it can be downloaded by players.

### Observed/Actual behavior

the resource pack randomly stopped bening hosted by nova so now it doesen't show up in the resource packs menu as world textures.

### Steps to reproduce

/

### Full server log

no nova errors in the server log

### Errors

```log
/
```

### Additional context

i just joined my server and the resource pack diden't load and diden't show up anymore in the resource packs menu.

**Comment by NichtStudioCode** [comment]
If you're using https://resourcepack.host (which is the default uploader), you'll need to switch to a different one or wait until they've resolved their server issues

**Comment by ND2009** [comment]
oh ok
so https://resourcepack.host/ is offline?

**Comment by NichtStudioCode** [comment]
Seems like it, and they've been down for at least 40 hours now. I can't say anything about whats going on and when (or if) they're going to be back up again, because we're in no way affiliated with them and are just using their service.
