### ISSUE TITLE
Nova Problem

### ISSUE THREAD

**Issue by PanGeo-Code** [xenondevs/Nova#3]
Hi, i have a Few Problems.

1st.
The quarry and all interactable blocks break whenever i restart my server. Unusable. and i also cant remove them,

2nd
The griefprevention support should be so the quarry arm doesnt go into the claim. Or that it isnt allawed within a scertain amount of blocks from a other persons claim.

3rd 
Make a disallow  for the usage of the quarry in a world but allow in in lets say a mine world. This would Fix the Massive holes everywhere in the world.

**Comment by NichtStudioCode** [comment]
Hey, thanks for your feedback!
About your first issue:
This only appears when you don't restart your server properly or it crashes during that process. How do you restart your server? Can you provide the server log?

2:
That's a good idea! I will change that behavior in the next version!

3:
This is also a good idea, I will probably implement some sort of world whitelist or blacklist in the config file.

Thanks for reporting these issues, I appreciate you taking the time to help improve Nova!

**Comment by PanGeo-Code** [comment]
Hi, No problem i would love to help more with this plugin.

1:
This had to do with that i'm using paper instead of spigot, are you going to support paper?
There were no errors when using paper on server stop or start.
i have seen errors while trying stuff out

2 & 3:
Sounds Great, i will keep testing and if i see or notice anything ill repost it her on the girhub.

4:
Maybe add a permission so that a standard player isnt allowed to use any quarrys but if you give them a permission that they will get acces to lets say 1 quarry. Permission Node: Nova.quarry.1 Amount of quarry's a player is allowed to place or use.

**Comment by NichtStudioCode** [comment]
> i have seen errors while trying stuff out

can you send the log?

**Comment by PanGeo-Code** [comment]
> > i have seen errors while trying stuff out
> 
> can you send the server log?

errors from paper or spigot?

**Comment by PanGeo-Code** [comment]
[2021-06-30-6.log](https://github.com/xenondevs/Nova/files/6749296/2021-06-30-6.log)

This is the server log from the paper server when i was getting errors.

**Comment by ByteZ1337** [comment]
> add mysql support instead of flat file in the plugins folder

What exactly should we add database support for? All tileentity data is already saved in the ArmorStands NBT.

**Comment by PanGeo-Code** [comment]
> > add mysql support instead of flat file in the plugins folder
> 
> What exactly should we add database support for? All tileentity data is already saved in the ArmorStands NBT.

i thougth for storage of where the machines are but i see that there is only a config and a file for the chunkloaders. 

Question: Are the quarrys async? i've tryed to get my server to lagg but it takes a while so i was curious if it was breaking blocks async?

**Comment by NichtStudioCode** [comment]
> Question: Are the quarrys async? i've tryed to get my server to lagg but it takes a while so i was curious if it was breaking blocks async?

No, quarrys are not working async

**Comment by ByteZ1337** [comment]
So it looks like the TileEntities not loading properly is a spigot issue as well. https://hub.spigotmc.org/jira/browse/SPIGOT-6547

**Comment by ByteZ1337** [comment]
Split into #4 #5 #6
