### ISSUE TITLE
Resource pack crashes client (Probably related to font)

### ISSUE THREAD

**Issue by Rinuuri** [xenondevs/Nova#301]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Check for plugin incompatibilites

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova 0.14.10, Pufferfish 1.20.1 R0.1 (build #27)

### Nova Addons and Versions

No addons

### Expected behavior

I expect that my client would load the resource pack in a reasonable amount of time without crashing 

### Observed/Actual behavior

Upon loading the resource pack client freezes for several minuses, disconnects from server and then crashes, see the client log file here: https://paste.ee/p/MQM9Y

### Steps to reproduce

1. Install Pufferfish (or Patina and probably any other core)
2. Install Nova 0.14.10
3. Run server
4. Set up resource pack auto upload (self_host in my case)
5. Join the server

### Full server log

https://paste.ee/p/SOMnf

### Additional context

Resource pack crashes client even when loaded manually from client menu, I tried giving client/server more/less RAM
OS: Windows 22H2 and Ubuntu 23.04
CPU: Ryzen 5 3500U
GPU: Radeon Vega Mobile Gfx
RAM 8GB (6GB CPU RAM/2GB VRAM)

Offtopic. You didn't really fix #297, I keep having the same issue using Nova 0.15 alpha 5

**Comment by NichtStudioCode** [comment]
How much ram did you allocate to Minecraft? We cannot really do anything about the client's ram consumption, if this doesn't work for you, you might need to disable certain Nova features.

**Comment by Rinuuri** [comment]
I allocated 1,2,3 and 4 GB - on 1 and 2 the client throws the out of memory error, on 3 and 4 it crashes upon loading a certain file mentioned in the client log

**Comment by Rinuuri** [comment]
I allocated 1,2,3 and 4 GB - on 1 and 2 the client throws the out of memory error, on 3 and 4 it crashes upon loading a certain file mentioned in the client log
