### ISSUE TITLE
Break network connections during chunk save / chunk load ?

### ISSUE THREAD

**Issue by CptbeffHeart** [xenondevs/Nova#304]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Check for plugin incompatibilites

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova-0.15-alpha.5

### Nova Addons and Versions

Logistics-0.2.7-RC.2, Machines-0.4.4-RC.1, Simple-Upgrades-1.2-RC.1

### Observed/Actual behavior

I create an installation with pipes and fluid tanks, then when the server restart, some pipes no longer work and need to be updated to work again (or break).
Most of the time, pipes near chunk border break

### Steps to reproduce

1. place a creativ fluid tank on the edge of a chunk
2. place a pipe in the chunk next to the fluid tank
3. Place an ultimate fluid tank at the end to collect the fluid from the creative.
(The 2 fluid tanks must be in different chunks)
4. Fill the creative tank with fluid.
5. Restart the server (may require more than one restart - usually no more than 5)
6. If the bug has occurred, the utlimate fluid tank will no longer load with fluid.

### Full server log

https://pastebin.com/grF4sy8L

### Additional context

![](https://cdn.discordapp.com/attachments/1167969087503220736/1170468927348932608/image.png?ex=65592722&is=6546b222&hm=eb24e1a542e47c4d97244617c93a37b0a742ef6dfebde60fa478481055511acb&)

Here is a screen of the broken setup
The cable circled in red is broken (even if another cable can break)

**Comment by NichtStudioCode** [comment]
Hi, please upload your log as a file as instructed in the issue template, because this is not very readable.

**Comment by CptbeffHeart** [comment]
Done

**Comment by CptbeffHeart** [comment]
I updated the issue, cause it don't break only pipes but it break network connection
It can break network connection between 2 networked tile entity
