### ISSUE TITLE
Advancement with multiple item do not work

### ISSUE THREAD

**Issue by CptbeffHeart** [xenondevs/Nova#305]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Check for plugin incompatibilites

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova-0.15-alpha.5

### Nova Addons and Versions

Logistics-0.2.7-RC.2, Machines-0.4.4-RC.1, Simple-Upgrades-1.2-RC.1

### Observed/Actual behavior

Achievements that only require one item work perfectly.
However, achievements that can be completed using one or all of the items on the list do not work.

### Steps to reproduce

1. Take mecanical press from the nova inventory you will get the achievement
2. Take all existing gear you will not get any achievement

### Full server log

https://pastebin.com/WEGKcwqy

**Comment by NichtStudioCode** [comment]
Hi, please upload your log as a file as instructed in the issue template, because this is not very readable.

**Comment by CptbeffHeart** [comment]
Done
