### ISSUE TITLE
Bossbars ?

### ISSUE THREAD

**Issue by NesChrome** [xenondevs/Nova#309]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Check for plugin incompatibilites

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova v0.15-alpha.8 , PaperMC , paper-1.20.2-307

### Nova Addons and Versions

no addons

### Expected behavior

No bossbars? (As theres no boss in the zone i am)

### Observed/Actual behavior

boss bars : 
![image](https://github.com/xenondevs/Nova/assets/105519787/8884e1ab-d038-40c4-a3c0-5849d5d07925)

### Steps to reproduce

1. Setup a Server on papermc on version : 1.20.2-307
2. Add the nova plugins
3. Join the server

### Server log

[latest.log](https://github.com/xenondevs/Nova/files/13466578/latest.log)
.

**Comment by NichtStudioCode** [comment]
It seems like you do not have the resourcepack set up.
See: https://docs.xen.cx/nova/admin/setup/

**Comment by NesChrome** [comment]
where can i download the resource pack?
