### ISSUE TITLE
[Request - Block] Machine - Auto Crafter block

### ISSUE THREAD

**Issue by Sheikins** [xenondevs/Nova#31]
### Potential name of the block

Auto Crafter

### Describe the block

My idea would be to add a machine, which would automatically craft or block items. When you click on the machine, it opens a menu with a 3x3 box to define a craft that the machine will reproduce automatically if the craft exists. After having defined the craft, it is necessary to send the necessary resources in the machine by pipes. The machine can then send the result of the craft to a storage connected by cable. It is also possible to connect different autocrafter together without having storage in between.

The machine uses electricity and can be turned on and off by pressing a button in the menu.
The machine therefore needs, an input for the materials, an output for the result of the craft and an input for the electricity.

All crafts should be compatible including those of the CustomCrafting plugin and ItemsAdder for example.
CustomCrafting is a free plugin : https://www.spigotmc.org/resources/customcrafting-advanced-custom-recipe-plugin-1-15-1-17-free.55883/
(The best is to make CustomCrafting compatible as a priority, which is itself compatible with ItemsAdder and many other plugins. It can therefore automatically make the link.)

Optional: Have a little sound every time the machine does a craft.

**Comment by Sheikins** [comment]
The system :

![2021-09-29_14 50 14](https://user-images.githubusercontent.com/50546556/135275071-cad64fbf-263d-48f4-aca6-6be9bdcd7ed4.png)

Input the AutoCrafter

![2021-09-29_14 51 48](https://user-images.githubusercontent.com/50546556/135275110-2c91602d-21c7-4cc3-90df-f245c25bcf1d.png)

Inside of the AutoCrafter

![2021-09-29_14 51 52](https://user-images.githubusercontent.com/50546556/135275203-c300455b-77fd-4344-8186-c5fb89eb29b4.png)

Output the AutoCrafter

![2021-09-29_14 51 55](https://user-images.githubusercontent.com/50546556/135275255-d16a2a2a-8a34-4700-9f73-de52ddd58df5.png)

**Comment by EchocallingEarth** [comment]
> Input the AutoCrafter

Adding to the Auto-crafter concept if possible:

Allow for crafting of any items not just vanilla or NOVA. I suggest this only because of the huge growing ItemsAdder Community and the need for more and more servers to have custom blocks etc. The world of vanilla crafting is changing and NOVA like all other plugins will have to be able to at some point integrate into this world, so why not now starting with the Auto-crafter

**Comment by NichtStudioCode** [comment]
Feature requests have been moved to [Discord](https://discord.gg/hnEknVWvUe).
