### ISSUE TITLE
[Request - Generic] 

### ISSUE THREAD

**Issue by Rinuuri** [xenondevs/Nova#310]
### Describe your feature request.

I wanna have support for nova blocks in the plugin called [SuperiorSkyblock](https://github.com/BG-Software-LLC/SuperiorSkyblock2) because currently nova blocks don't even correctly processed by it's protection - you couldn't break nova blocks on other players' islands but you could place them, that's the main issue, I'm not even mentioning that they aren't counting into island level and worth

**Comment by ByteZ1337** [comment]
That's all stuff SuperiorSkyblock needs to implement/fix on their end.
