### ISSUE TITLE
[Request - Generic] :(

### ISSUE THREAD

**Issue by Hiho2950** [xenondevs/Nova#316]
### Describe your feature request.

when geysermc support (no problem with the resource pack there is some converters) pls and how to fix the problem:
[Nova] Something went wrong

**Comment by ByteZ1337** [comment]
Geyser is not supported

**Comment by Hiho2950** [comment]
> Geyser is not supported

why? :(

**Comment by ByteZ1337** [comment]
That "option" is hundreds of hours of work we neither have nor want to invest in something that's supported natively.

**Comment by Hiho2950** [comment]
> That "option" is hundreds of hours of work we neither have nor want to invest in something that's supported natively.

OK sorry :(
