### ISSUE TITLE
unable to load addons on startup on paper 1.20.4

### ISSUE THREAD

**Issue by patetisk** [xenondevs/Nova#319]
### Agreements

- [X] I am using an official build of Nova.
- [X] I am running the latest version of Nova.
- [X] I am using a [server software supported by Nova](https://docs.xen.cx/nova/admin/compatibility/#compatible-server-software)
- [X] I am running the latest version of my server software.
- [x] I have checked for similar issues.

### Check for plugin incompatibilites

This issue is about a specific plugin incompatibility.

### Plugin Version, Server Software, Server Version

Nova-0.16-alpha.1 , paper-1.20.4-370 (MC: 1.20.4)

### Nova Addons and Versions

Nova-0.16-alpha.1 , Machines-0.4.5-RC.1 , Logistics-0.2.8-RC.1 , Simple-Upgrades-1.3-RC.1

### Observed/Actual behavior

The errors inside the cmd

### Steps to reproduce

![Skärmbild 2024-01-07 171346](https://github.com/xenondevs/Nova/assets/111516158/7a4d413a-7d0e-4c0f-ad34-0d365162de2c)

### Server log

[latest.log](https://github.com/xenondevs/Nova/files/13854266/latest.log)

### Errors

```log
[16:58:51 ERROR]: [STDERR] [sun.instrument.InstrumentationImpl] WARNING: A Java agent has been loaded dynamically (C:\Users\Admin\Desktop\paper 1.20.4\libraries\net\bytebuddy\byte-buddy-agent\1.12.20\byte-buddy-agent-1.12.20.jar)
WARNING: If a serviceability tool is in use, please run with -XX:+EnableDynamicAgentLoading to hide this warning
WARNING: If a serviceability tool is not in use, please run with -Djdk.instrument.traceUsage for more information
WARNING: Dynamic loading of agents will be disallowed by default in a future release
```

**Comment by NichtStudioCode** [comment]
Addons are not plugins.
Please refer to the [setup guide](https://docs.xen.cx/nova/admin/setup/#step-2-installing-addons).
