### ISSUE TITLE
Nova 0.16.alpha-2 

### ISSUE THREAD

**Issue by Kletterhamster** [xenondevs/Nova#323]
### Agreements

- [X] I am using an official build of Nova.
- [X] I am running the latest version of Nova.
- [X] I am using a [server software supported by Nova](https://docs.xen.cx/nova/admin/compatibility/#compatible-server-software)
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Check for plugin incompatibilites

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova 0.16-alpha-2 MC: purpur 1.20.4

### Nova Addons and Versions

Logistics-0.2.8-RC.1 Machines-0.4.5-RC.1 Simple-Upgrades-1.3-RC.1

### Observed/Actual behavior

See Server logs

### Steps to reproduce

purpur 1.20.4 install all plugins at Nova and start server

### Server log

https://pastebin.com/YGGu0wuD

**Comment by NichtStudioCode** [comment]
No info and incomplete server log
