### ISSUE TITLE
Block break sound not playing for stone/sandstone/etc

### ISSUE THREAD

**Issue by evilbocchi** [xenondevs/Nova#325]
### Agreements

- [X] I am using an official build of Nova.
- [X] I am running the latest version of Nova.
- [X] I am using a [server software supported by Nova](https://docs.xen.cx/nova/admin/compatibility/#compatible-server-software)
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Check for plugin incompatibilites

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova: 0.16-alpha.2, Paper 392 (MC 1.20.4)

### Nova Addons and Versions

-

### Observed/Actual behavior

https://github.com/xenondevs/Nova/assets/71329833/1b5c7b1c-401c-475c-bcfe-75337f2e19f0

### Steps to reproduce

1. Break any block that produces the sound of a stone block being broken.

### Server log

[2024-01-22-10.log](https://github.com/xenondevs/Nova/files/14002400/2024-01-22-10.log)

### Additional context

Note: Even without the "Mna" addon and additional plugins the issue still occurs.

**Comment by AMDBartek** [comment]
Can confirm this issue on my Purpur-based (fork) 1.20.4 server using `Nova v0.16-alpha.2`. It's surprisingly more annoying than one would think even when just playing survival. I would greatly appreciate if it could be fixed, I may take a look at fixing it myself and make a PR, but it will be difficult to do so without knowing the exact source in Nova of the issue. It's not anything to do with an addon obviously so it must be something in Nova itself I guess? But I'm not exactly sure.

**Comment by NichtStudioCode** [comment]
> but it will be difficult to do so without knowing the exact source in Nova of the issue

My guess is that this is caused by one of [SoundPatches](https://github.com/xenondevs/Nova/blob/main/nova/src/main/kotlin/xyz/xenondevs/nova/transformer/patch/sound/SoundPatches.kt) not working properly with the new Minecraft version, but I don't really have the time to look into that at the moment.

**Comment by AMDBartek** [comment]
Thanks, I might take a closer look later and make a PR.

**Comment by TheHuky** [comment]
I have the same.
