### ISSUE TITLE
Auto crafter does not save upgrades

### ISSUE THREAD

**Issue by RAPHAEL599** [xenondevs/Nova#328]
### Agreements

- [X] I am using an official build of Nova.
- [X] I am running the latest version of Nova.
- [X] I am using a [server software supported by Nova](https://docs.xen.cx/nova/admin/compatibility/#compatible-server-software)
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Check for plugin incompatibilites

This issue is about a specific plugin incompatibility.

### Plugin Version, Server Software, Server Version

Nova: 0.16-alpha.3 Current: git-Purpur-2139 (MC: 1.20.4)* * You are running the latest version

### Nova Addons and Versions

Logistics-0.2.8-RC.1 Machines-0.4.5-RC.1 Simple-Upgrades-1.3-RC.1

### Expected behavior

As soon as the server restarts the upgrades are inside the machine

### Observed/Actual behavior

Every time the server turns on again, there are no upgrades in the auto crafter

### Steps to reproduce

[https://youtu.be/SiYq8PYxk1s](https://youtu.be/SiYq8PYxk1s)

### Server log

[latest (3).log](https://github.com/xenondevs/Nova/files/14232732/latest.3.log)

**Comment by NichtStudioCode** [comment]
Fixed in Nova-Addons/Official-Addons@f8a7edcb98b652335e7085555056abc6ccb2f0a3
