### ISSUE TITLE
[Machines] Cannot enchant Star armors

### ISSUE THREAD

**Issue by AllayBreeze** [xenondevs/Nova#334]
### Agreements

- [X] I am using an official build of Nova.
- [X] I am running the latest version of Nova.
- [X] I am using a [server software supported by Nova](https://docs.xen.cx/nova/admin/compatibility/#compatible-server-software)
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Check for plugin incompatibilites

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova 0.16-alpha.3, git-Purpur-2153 (MC: 1.20.4)

### Nova Addons and Versions

Jetpacks 0.1.12-RC.1, Logistics 0.2.8-RC.1, Machines-0.4.5-RC.2, Simple Upgrades 1.3-RC.1, Vanilla Hammers 1.4-RC.1

### Expected behavior

Star armors should have enchantment values and catogories, and can be enchanted via enchanting table or anvil.

### Observed/Actual behavior

Star armors do not have enchantment values or catogories, and cannot be enchanted, even when manually add catogory "armor", "armor_head" etc. to the config file of them.

### Steps to reproduce

1. Place any piece of Star armor into enchanting table, or into anvil with an adequate enchanting book
2. Both ways cannot enchant the armor
3. Try to add enchantment values and catogories for Star armors
4. Run /nova reload configs or restart the server
5. Still cannot enchant them.

### Server log

[latest.log](https://github.com/xenondevs/Nova/files/14545535/latest.log)

### Additional context

My Star Helmet config that adds enchantment values and catogories (changed to txt as cannot upload yaml): 
[star_helmet.txt](https://github.com/xenondevs/Nova/files/14545540/star_helmet.txt)

**Comment by NichtStudioCode** [comment]
Fixed in Nova-Addons/Official-Addons@a8b8d940d806e18e4bfa1f2e6a0a622145688556
