### ISSUE TITLE
[Request - Item] Sickle

### ISSUE THREAD

**Issue by Sheikins** [xenondevs/Nova#34]
### Potential name of the item

Sickle

### Describe the item

This item is a tool that can destroy large areas of tall grass, flowers or crops and plants. By left clicking the tool will break the plants at the same level within a radius depending on the level of the tool. It would be necessary to create 3 levels of tool, iron, diamond and netherite for example. Each level will have a different radius (configurable in the config) and different durability.

Example:
Iron : 3x3
Diamond: 4x4
Netherite: 6x6

The names to use and the levels are examples.

**Comment by NichtStudioCode** [comment]
Feature requests have been moved to [Discord](https://discord.gg/hnEknVWvUe).
