### ISSUE TITLE
[Request - Block] Watermill and Rotator Block

### ISSUE THREAD

**Issue by Sheikins** [xenondevs/Nova#35]
### Potential name of the block

Watermill - Rotator Block

### Describe the block

The watermill is an electricity generator using water as a source of energy. The watermill is an block that must be placed in a rotatory block. 

The rotatory block will be the support to put the watermill wheel. The rotatory block also makes it possible to recover the electricity generated by the watermill. For all this to work, the rotatory block must be placed above the water so that the watermill is one third in the water and two thirds in the air.

To put the watermill on the rotatory you can right click on the block or open it. 

The watermill would be made of wood, it would be good to be able to have several variants depending on the wood (oak wood, birch wood ...) It would also be lively during its operation while rotating.

![2021-09-29_14 31 44](https://user-images.githubusercontent.com/50546556/135360237-688dd87f-440f-4443-be62-af25b2ea8eb8.png)

**Comment by NichtStudioCode** [comment]
Feature requests have been moved to [Discord](https://discord.gg/hnEknVWvUe).
