### ISSUE TITLE
[Request - Generic] Redstone Activator for Machine

### ISSUE THREAD

**Issue by Sheikins** [xenondevs/Nova#36]
### Describe your feature request.

Add a function in the machine configuration (Input / Output ...) to be able to activate or deactivate the machine by sending it a redstone current. Put this feature on all machines.

**Comment by EchocallingEarth** [comment]
Maybe instead of Redstone interaction adding an on/off operation to the machine. This could be done in the same GUI as all other machine functions such as upgrades etc.

**Comment by ByteZ1337** [comment]
Could you provide a specific use case for this? I've played modded Minecraft for thousands of hours and have never used the turn off buttons in machines.

**Comment by Sheikins** [comment]
To connect it to an observer block for example or just to shut down a machine without having to remove the cable. I have another example but it does not occur to me at the moment.

**Comment by XxMr1234GamerzxX** [comment]
i think the way slimefun handles this function is graceful maybe influence from that where in the gui theres "states"
On , Off, Redstone

on - would be like they are now
off - turns the machine off
Redstone - uses Redstone power state as a external toggle (like lever or something)

**Comment by NichtStudioCode** [comment]
Feature requests have been moved to [Discord](https://discord.gg/hnEknVWvUe).
