### ISSUE TITLE
Leather and Star Armor Texture broken

### ISSUE THREAD

**Issue by P3YC1** [xenondevs/Nova#364]
### Agreements

- [X] I am using an official build of Nova.
- [X] I am running the latest version of Nova.
- [X] I am using a [server software supported by Nova](https://docs.xen.cx/nova/admin/compatibility/#compatible-server-software)
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Check for plugin incompatibilites

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova: 0.16 RC 1, Paper: git-Paper-463 (MC: 1.20.4)

### Nova Addons and Versions

Jetpacks v0.1.12-RC.2, Logistics v0.2.8-RC.1, Machines v0.4.5-RC.4, Simple-Upgrades v1.3-RC.2, Vanilla Hammers v1.4-RC.2

### Expected behavior

The leather and star armor look like regular armor when worn.

### Observed/Actual behavior

The leather and star armor have a broken texture when worn.

### Steps to reproduce

1. Install Plugin with Addons on the given Version.
2. Execute /nova resourcePack create
3. Restart the Server
4. Put the generated Resource Pack into your Resource Pack Folder and activate it
5. Equip The Star Armor or the Leather Armor
6. Look at yourself outside the inventory (Inside the inventory, everything seems to be working, even in the preview)

### Server log

[latest.log](https://github.com/xenondevs/Nova/files/14893012/latest.log)

**Comment by NichtStudioCode** [comment]
Are you using any client-side rendering mods, such as OptiFine or Iris?

**Comment by P3YC1** [comment]
Interesting. I thought this had nothing to do with it, but yes. I am using a Fabric installation with the Iris Shader Mod. Trying this in Vanilla, the textures are totally fine. So I guess it is an incompatibility, instead of a bug.

**Comment by NichtStudioCode** [comment]
Custom armor textures are implemented via a core shader, and both OptiFine shaders and Iris disable those. It's not an issue for OptiFine, because OptiFine has built-in ways to do custom armor, but you'll need to install additional mods for that when using Iris.
