### ISSUE TITLE
Resolve unexplained discord communication issue

### ISSUE THREAD

**Issue by austanss** [xenondevs/Nova#379]
### Describe your feature request.

Sorry, I don’t know how to categorize this. My discord username goes by “austanss”. I joined the server a few days ago to inquire about what process I need to go through to become a contributor. I didn’t get a response, so I, rather dramatically, pleaded for a response, as I was rather desperate to see this very clever project come to fruition. Well, I went to check today, just to see that I was banned. I don’t see how I could have possibly broken any of the rules, and there was no explanation provided to me, and the reason is not clear to me, at all.

i really want to help contribute to this project, and I have a non-negligible amount of Minecraft modding experience, so I’m rather confused as to why I was abruptly banned. I believe it was an error.

is there an explanation?

**Comment by austanss** [comment]
I am aware this issue is formatted completely incorrectly, but please forgive me. I am not aware of any alternative channels of communication.

**Comment by ByteZ1337** [comment]
> I joined the server a few days ago to inquire about what process I need to go through to become a contributor

![image](https://github.com/xenondevs/Nova/assets/42820438/b207c994-137c-4789-915b-3aca50598cf0)
This is a weird way of "inquiring how to become a contributor". Instead of just looking at the source code you want to contribute to, immediately assuming it's not worth your precious time is a great look.

**Comment by austanss** [comment]
Wow, that was the most horrendous insult to your code ever. Hear hear, a question mark and a period mean the same thing these days. How dare I make such a hasty inquiry. I *definitely* needed to be completely excommunicated from even inquiring about server administration, because I am such an obvious, impending threat to the order and productivity of your community; this threat was clearly demonstrated by my incessantly inflammatory remarks that were obviously directed in sharp criticism towards your (frankly ingenious) product.

Funny that you all are from Germany, it seems very in character.

Sorry I accidentally insulted you.

**Comment by NichtStudioCode** [comment]
I think you misunderstood @ByteZ1337. This was not about "insulting our code" (you clearly stated that you didn't look at it), but you seem to have some sort of superiority complex where you need us to tell you whether it is worth your time to look at the code? Then, for obvious reasons, you didn't receive a response to that and started spamming the channel the next day? I'm not sure why even need to explain this to you.
All in all, you seem to have some serious character flaws that you need to work on, which you've again confirmed with your distasteful Nazi remarks. We do not want such toxic personalities contributing to the project, nor do we want them on the Discord.
