### ISSUE TITLE
Resource pack do not load custom bow correctly

### ISSUE THREAD

**Issue by CptbeffHeart** [xenondevs/Nova#380]
### Agreements

- [X] I am using an official build of Nova.
- [X] I am running the latest version of Nova.
- [X] I am using a [server software supported by Nova](https://docs.xen.cx/nova/admin/compatibility/#compatible-server-software)
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Check for plugin incompatibilites

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova-0.16

### Nova Addons and Versions

Nova-0.16

### Expected behavior

When we register a new bow the overrides in the json file should look like something similar to that :
https://pastebin.com/k0TTauMJ

### Observed/Actual behavior

But it look like that :
https://pastebin.com/T2j5a6Rx

### Steps to reproduce

Register new bow in materials:
"custom_bow": {
    "item": {
      "material": "bow",
      "models": {
        "item/bow/custom_bow/%s": [0, 3]
      }
    }
  }

### Server log

.

### Additional context

The problem should probably come from xyz.xenondevs.nova.data.resources.builder.basepack.merger.ModelFileMerger
There is only one model data possibility, but it need one specific for the bow and the shield (maybe some other ? )

**Comment by NichtStudioCode** [comment]
This is working as intended, there is just currently no built-in way to do custom bows or shields
