### ISSUE TITLE
Problem with russian translation

### ISSUE THREAD

**Issue by webvlad** [xenondevs/Nova#382]
### Agreements

- [X] I am using an official build of Nova.
- [X] I am running the latest version of Nova.
- [X] I am using a [server software supported by Nova](https://docs.xen.cx/nova/admin/compatibility/#compatible-server-software)
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Check for plugin incompatibilites

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova-0.16, Paper 1.20.4

### Nova Addons and Versions

Machines-0.4.5 Simple-Upgrades-1.3

### Observed/Actual behavior

Instead of WAILA or other text i see only rectangles

### Steps to reproduce

![image](https://github.com/xenondevs/Nova/assets/22093556/44126e6d-c696-42ec-a033-4784117956ec)

### Server log

[latest.log](https://github.com/xenondevs/Nova/files/15190007/latest.log)

**Comment by NichtStudioCode** [comment]
You don't have the resource pack applied, refer to the [setup guide](https://docs.xen.cx/nova/admin/setup/).
