### ISSUE TITLE
Server crashes after installing the addon logistics

### ISSUE THREAD

**Issue by TurretedAsh** [xenondevs/Nova#386]
### Agreements

- [X] I am using an official build of Nova.
- [X] I am running the latest version of Nova.
- [X] I am using a [server software supported by Nova](https://docs.xen.cx/nova/admin/compatibility/#compatible-server-software)
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Check for plugin incompatibilites

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

paper-1.20.4-497.jar

### Nova Addons and Versions

Nova v0.16 , Logistics-0.2.8.jar, Machines-0.4.5.jar, Simple-Upgrades-1.3.jar , 

### Observed/Actual behavior

Server crashes after installing addon Logistics-0.2.8.jar

### Steps to reproduce

1. place Logistics-0.2.8.jar, in nova addon file. The start up server and it crashes

### Server log

[2024-05-29-9.log](https://github.com/xenondevs/Nova/files/15472325/2024-05-29-9.log)

**Comment by NichtStudioCode** [comment]
> Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin. In order to do that, remove all other plugins from your server and check if the issue still persists. If the issue is caused by another plugin, select "This issue is about a specific plugin incompatibility" and state the name, version and where to download that plugin in your report.
