### ISSUE TITLE
Nova Advancements not showing with UltimateAdvancementapi

### ISSUE THREAD

**Issue by TurretedAsh** [xenondevs/Nova#389]
### Agreements

- [X] I am using an official build of Nova.
- [X] I am running the latest version of Nova.
- [X] I am using a [server software supported by Nova](https://docs.xen.cx/nova/admin/compatibility/#compatible-server-software)
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Check for plugin incompatibilites

This issue is about a specific plugin incompatibility.

### Plugin Version, Server Software, Server Version

Nova-0.16.jar, UltimateAdvancementAPI 2.8.8, paper-1.20.4-497.jar

### Nova Addons and Versions

Nova v0.16 , Logistics-0.2.8.jar, Machines-0.4.5.jar, Simple-Upgrades-1.3.jar , 

### Expected behavior

When installing the UltimateAdvancementAPI, None of nova advancements work at all. Have been looking around to see if there a way to fix it but there nothing.

### Observed/Actual behavior

Installed plugin ( UltimateAdvancementAPI). Nova Advancement disables.

### Steps to reproduce

Install UltimateAdvancementAPI 2.2.8 (For 1.20.4 server)
Server Starts up and all other advancements work. But Nova advancement seems to be disabled.

### Server log

[latest (23).log](https://github.com/user-attachments/files/15527357/latest.23.log)

**Comment by NichtStudioCode** [comment]
I doubt this can be fixed on our end, from what you're saying it seems like UltimateAdvancementAPI is removing the advancements registered by Nova, so you should report this to UltimateAdvancementAPI dev(s) instead.
