### ISSUE TITLE
[Request - Generic]  Add crafter support

### ISSUE THREAD

**Issue by Katalijst** [xenondevs/Nova#433]
### Describe your feature request.

When adding a vanilla shaped or shapeless recipe, it works well with the crafting table but doesn't work in the crafter.
It would be good to make it work

**Comment by NichtStudioCode** [comment]
Works fine for me
![image](https://github.com/user-attachments/assets/2647b170-ab14-48c4-978b-d71c176d1f6a)

**Comment by Katalijst** [comment]
@NichtStudioCode  I just checked and yes it works, for some reason the night I wrote this issue we were two person testing it and it didn't work, but I wasnt able to reproduce the bug today.
I will report in a bug type issue if ever I find how to trigger it
