### ISSUE TITLE
[Request - Block] smeltery

### ISSUE THREAD

**Issue by MissGamerz** [xenondevs/Nova#44]
### Potential name of the block

Smeltery

### Describe the block

electric and coal powered variants

works in a similar way to a furnace but accepts two different metals to create a alloy 

like gold + copper = rose gold

or charcoal + iron = steel

this also allows for weirder stuff like

green diamonds(copper+diamond), yellow diamonds(diamond + sulfer but could use gold if new ores aren't a thing your wanting to do) plus more

this would allow for furture expension aswell

**Comment by NichtStudioCode** [comment]
Feature requests have been moved to [Discord](https://discord.gg/hnEknVWvUe).
