### ISSUE TITLE
Mob Catcher Lags the server

### ISSUE THREAD

**Issue by Nik0-0** [xenondevs/Nova#449]
### Agreements

- [X] I am using an official build of Nova.
- [X] I am running the latest version of Nova.
- [X] I am using a [server software supported by Nova](https://docs.xen.cx/nova/admin/compatibility/#compatible-server-software)
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Check for plugin incompatibilites

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova: 0.17-alpha.14 . Purpur 1.21.1

### Nova Addons and Versions

Vanilla-Hammers v1.5, SimpleUpgrades v1.4-alpha2, Logistics v0.2.9-alpha.3, Machines v0.4.6-alpha.8

### Expected behavior

Mob should just pickup normally without lag

### Observed/Actual behavior

Picking up any mob lags the whole server and causes issues

### Steps to reproduce

1. Get the Mob Catcher
2. Click on any mob
3. Observe the big TPS lag spike

### Server log

https://mclo.gs/pSpQJBA

**Comment by Nik0-0** [comment]
Okay i think it may be caused by FancyDamageIndicator. Not sure yet

**Comment by ByteZ1337** [comment]
Looks like the entity damage event is called with some very high damage amount when an entity is captured. Try switching the health mode in FancyDamageIndicator to `NUMBER` in the meantime as a temporary fix.

**Comment by Nik0-0** [comment]
Yea for now i just removed the plugin since it was also creating bunch of text displays stuff even when set to ``NUMBER ``

**Comment by ByteZ1337** [comment]
We'll remove the event call since it's no longer needed. That will also fix this issue. You should probably still report this to the FancyDamageIndicator author because nothing stops a plugin from calling that event with some nonsensical amount of damage.
