### ISSUE TITLE
Wind turbine waila

### ISSUE THREAD

**Issue by CptbeffHeart** [xenondevs/Nova#453]
### Agreements

- [X] I am using an official build of Nova.
- [X] I am running the latest version of Nova.
- [X] I am using a [server software supported by Nova](https://docs.xen.cx/nova/admin/compatibility/#compatible-server-software)
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Check for plugin incompatibilites

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova-0.17-alpha.15

### Nova Addons and Versions

Machines-0.4.6-alpha.9

### Observed/Actual behavior

Wind turbine section waila are not "link" with the base block

### Steps to reproduce

1. Place a wind turbine
2. Look at the sections

### Additional context

![image](https://github.com/user-attachments/assets/a1cd8a9b-60b2-43a8-b912-6abc9faf0a5a)

**Comment by AcdeAsdff** [comment]
maybe i can fix this,but my coding was bad and i dont know how to pull requests.
i guess what we want:
![2024-09-12_08 17 31](https://github.com/user-attachments/assets/53b3e1dc-44f3-4764-b237-21fa39decc67)
(can also be type:enhancement ?)
i tried to modify nova-parent and Official-Addons(machines) to make this
code changed:
--------------Nova Parent---------------
DefaultNovaWailaInfoProvider.kt:

      package xyz.xenondevs.nova.ui.waila.info.impl
      
      import net.kyori.adventure.text.Component
      import net.kyori.adventure.text.format.NamedTextColor
      import org.bukkit.entity.Player
      import xyz.xenondevs.commons.collections.firstInstanceOfOrNull
      import xyz.xenondevs.nova.world.block.tileentity.NetworkedTileEntity
      import xyz.xenondevs.nova.world.block.tileentity.network.type.energy.holder.DefaultEnergyHolder
      import xyz.xenondevs.nova.ui.waila.info.NovaWailaInfoProvider
      import xyz.xenondevs.nova.ui.waila.info.WailaInfo
      import xyz.xenondevs.nova.ui.waila.info.WailaLine
      import xyz.xenondevs.nova.ui.waila.info.line.EnergyHolderLine
      import xyz.xenondevs.nova.ui.waila.info.line.ToolLine
      import xyz.xenondevs.nova.world.BlockPos
      import xyz.xenondevs.nova.world.block.DefaultBlocks
      import xyz.xenondevs.nova.world.block.NovaMultiBlockSectionBlock
      import xyz.xenondevs.nova.world.block.NovaTileEntityBlock
      import xyz.xenondevs.nova.world.block.state.NovaBlockState
      import xyz.xenondevs.nova.world.format.WorldDataManager
      
      private val DELEGATES = setOf(
          DefaultBlocks.NOTE_BLOCK, DefaultBlocks.OAK_LEAVES, DefaultBlocks.SPRUCE_LEAVES,
          DefaultBlocks.BIRCH_LEAVES, DefaultBlocks.JUNGLE_LEAVES, DefaultBlocks.ACACIA_LEAVES,
          DefaultBlocks.DARK_OAK_LEAVES, DefaultBlocks.MANGROVE_LEAVES, DefaultBlocks.CHERRY_LEAVES,
          DefaultBlocks.AZALEA_LEAVES, DefaultBlocks.FLOWERING_AZALEA_LEAVES
      )
      
      object DefaultNovaWailaInfoProvider : NovaWailaInfoProvider(null) {
          
          override fun getInfo(player: Player, pos: BlockPos, blockState: NovaBlockState): WailaInfo {
              if (blockState.block in DELEGATES)
                  return DefaultVanillaWailaInfoProvider.getInfo(player, pos, pos.block.blockData)
      
      
              //start adding
              if(blockState.block is NovaMultiBlockSectionBlock){
                  val multiBlockSection = blockState.block
                  val lines = ArrayList<WailaLine>()
      
                  //get base info
                  val baseLocation = multiBlockSection.getBaseLocation(blockState,pos)
                  val baseState = WorldDataManager.getBlockState(baseLocation)
                  val baseBlockType = baseState?.block //hope not be null
                  val baseBlockName = baseBlockType?.name ?: blockState.block.name
                  val baseBlockId = baseBlockType?.id ?: blockState.block.id
      
                  lines += WailaLine(baseBlockName, WailaLine.Alignment.CENTERED)
                  lines += WailaLine(Component.text(baseBlockId.toString(), NamedTextColor.DARK_GRAY), WailaLine.Alignment.CENTERED)
                  lines += ToolLine.getToolLine(player, pos.block)
      
                  //maybe i should extract these
                  //paste (A)
                  val tileEntity = WorldDataManager.getTileEntity(baseLocation)
                  if (tileEntity is NetworkedTileEntity) {
                      val energyHolder = tileEntity.holders.firstInstanceOfOrNull<DefaultEnergyHolder>()
                      if (energyHolder != null) {
                          lines += EnergyHolderLine.getEnergyBarLine(energyHolder)
                          lines += EnergyHolderLine.getEnergyAmountLine(energyHolder)
                          lines += EnergyHolderLine.getEnergyDeltaLine(energyHolder)
                      }
                  }
                  //end paste (A)
      
                  return WailaInfo(baseBlockId, lines)
                  //ignores below -- not a good idea to write like this,leads into chaos
              }
              //end adding
      
              val blockType = blockState.block
              val id = blockType.id
      
              val lines = ArrayList<WailaLine>()
              lines += WailaLine(blockType.name, WailaLine.Alignment.CENTERED)
              lines += WailaLine(Component.text(id.toString(), NamedTextColor.DARK_GRAY), WailaLine.Alignment.CENTERED)
              lines += ToolLine.getToolLine(player, pos.block)
      
              if (blockState.block is NovaTileEntityBlock) {
                  //copy (marked as A)
                  val tileEntity = WorldDataManager.getTileEntity(pos)
                  if (tileEntity is NetworkedTileEntity) {
                      val energyHolder = tileEntity.holders.firstInstanceOfOrNull<DefaultEnergyHolder>()
                      if (energyHolder != null) {
                          lines += EnergyHolderLine.getEnergyBarLine(energyHolder)
                          lines += EnergyHolderLine.getEnergyAmountLine(energyHolder)
                          lines += EnergyHolderLine.getEnergyDeltaLine(energyHolder)
                      }
                  }
                  //end copy (A)
              }
              
              // TODO waila icon by block state
              
              return WailaInfo(id, lines)
          }
          
      }

NovaMultiBlockSectionBlock.kt[adding file](same folder as NovaBlockBuilder.kt)

      package xyz.xenondevs.nova.world.block
      
      import net.kyori.adventure.text.Component
      import net.kyori.adventure.text.format.Style
      import net.minecraft.resources.ResourceLocation
      import xyz.xenondevs.nova.world.block.state.NovaBlockState
      import xyz.xenondevs.nova.resources.layout.block.BlockModelLayout
      import xyz.xenondevs.nova.world.BlockPos
      import xyz.xenondevs.nova.world.block.behavior.BlockBehaviorHolder
      import xyz.xenondevs.nova.world.block.state.property.ScopedBlockStateProperty
      
      open class NovaMultiBlockSectionBlock internal constructor(
          id: ResourceLocation,
          name: Component,
          style: Style,
          behaviors: List<BlockBehaviorHolder>,
          properties: List<ScopedBlockStateProperty<*>>,
          configId: String,
          requestedLayout: BlockModelLayout,
          baseLocationGetter: NovaMultiBlockSectionBaseLocationGetter
      ) : NovaBlock(id, name, style, behaviors, properties, configId, requestedLayout) {
      
          private val baseLocGetter : NovaMultiBlockSectionBaseLocationGetter = baseLocationGetter
      
          //maybe i should change the position of the two arguments
          fun getBaseLocation(state : NovaBlockState, pos: BlockPos):BlockPos{
              return baseLocGetter.getBaseLocation(state, pos)
          }
      }
      
      interface NovaMultiBlockSectionBaseLocationGetter{
          fun getBaseLocation(state : NovaBlockState, pos: BlockPos):BlockPos
      }

NovaBlockBuilder.kt(addingLines in the end)

      //addingLines
      class NovaMultiBlockSectionBlockBuilder
      internal constructor(id: ResourceLocation, private val baseLocationGetter : NovaMultiBlockSectionBaseLocationGetter) : AbstractNovaBlockBuilder<NovaMultiBlockSectionBlock>(id) {
          internal constructor(addon: Addon, name: String,baseLocationGetter: NovaMultiBlockSectionBaseLocationGetter) : this(ResourceLocation(addon, name),baseLocationGetter)
      
          override fun build() = NovaMultiBlockSectionBlock(
              id,
              name.style(style),
              style,
              behaviors,
              stateProperties,
              configId,
              requestedLayout,
              baseLocationGetter
          )
      
      }
      //end addingLines

BlockRegistry.kt

      package xyz.xenondevs.nova.addon.registry
      
      import xyz.xenondevs.nova.world.block.*
      
      interface BlockRegistry : AddonGetter {
          
          fun tileEntity(name: String, constructor: TileEntityConstructor, tileEntity: NovaTileEntityBlockBuilder.() -> Unit): NovaTileEntityBlock =
              NovaTileEntityBlockBuilder(addon, name, constructor).apply(tileEntity).register()
          
          fun block(name: String, block: NovaBlockBuilder.() -> Unit): NovaBlock =
              NovaBlockBuilder(addon, name).apply(block).register()
          //addingLines
      
          fun multiBlockSection(name: String,baseLocationGetter: NovaMultiBlockSectionBaseLocationGetter, block: NovaMultiBlockSectionBlockBuilder.() -> Unit): NovaMultiBlockSectionBlock =
              NovaMultiBlockSectionBlockBuilder(addon, name, baseLocationGetter).apply(block).register()
          //end addingLines
      }

NovaMultiBlockSectionState.java[adding file](same folder as NovaBlockState.java)

      package xyz.xenondevs.nova.api.block;
      
      import org.bukkit.Location;
      import org.jetbrains.annotations.NotNull;
      
      public interface NovaMultiBlockSectionState extends NovaBlockState{
          @NotNull Location getBaseLocation();
      }

-------------------Official-Addons---------------

Blocks.kt (modified WIND_TURBINE_EXTRA)

      //    val WIND_TURBINE_EXTRA = block("wind_turbine_extra") {
      //        behaviors(WindTurbineSectionBehavior, METAL, BlockSounds(SoundGroup.METAL))
      //        stateProperties(ScopedBlockStateProperties.TURBINE_SECTION)
      //        models { modelLess { Material.BARRIER.createBlockData() } }
      //    } //before
          val WIND_TURBINE_EXTRA = multiBlockSection("wind_turbine_extra", WindTurbineExtraBase) { // only added WindTurbineExtraBase
              behaviors(WindTurbineSectionBehavior, METAL, BlockSounds(SoundGroup.METAL))
              stateProperties(ScopedBlockStateProperties.TURBINE_SECTION)
              models { modelLess { Material.BARRIER.createBlockData() } }
          }//after

WindTurbineExtraBase.kt(added package because i dont know where to place)

      package xyz.xenondevs.nova.addon.machines.multiblock.basepositiongetter
      
      import xyz.xenondevs.nova.addon.machines.registry.BlockStateProperties
      import xyz.xenondevs.nova.world.block.state.NovaBlockState
      import xyz.xenondevs.nova.world.BlockPos
      import xyz.xenondevs.nova.world.block.NovaMultiBlockSectionBaseLocationGetter
      
          object WindTurbineExtraBase : NovaMultiBlockSectionBaseLocationGetter {
              override fun getBaseLocation(state: NovaBlockState, pos: BlockPos): BlockPos {
                  val basePos = pos.add(0, -state.getOrThrow(BlockStateProperties.TURBINE_SECTION) - 1, 0) //get position like WindTurbineSectionBehavior
                  return basePos
              }
          
          }

**Comment by NichtStudioCode** [comment]
Fixed in Nova-Addons/Official-Addons@5fccdeac97df4e4c4ea2191f4b79b5a2ba3986c8
