### ISSUE TITLE
Chunk system error / World corruption & block issues

### ISSUE THREAD

**Issue by Nik0-0** [xenondevs/Nova#454]
### Agreements

- [X] I am using an official build of Nova.
- [X] I am running the latest version of Nova.
- [X] I am using a [server software supported by Nova](https://docs.xen.cx/nova/admin/compatibility/#compatible-server-software)
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Check for plugin incompatibilites

There are no other plugins running on my server / Not related to plugins.

### Plugin Version, Server Software, Server Version

Nova: 0.17-alpha.16 . Purpur Version: 1.21.1-2304-dee41bc (MC: 1.21.1)

### Nova Addons and Versions

Vanilla-Hammers v1.5, SimpleUpgrades v1.4-alpha2, Logistics v0.2.9-alpha.3, Machines v0.4.6-alpha.8

### Observed/Actual behavior

Sometimes plugin tries to access stuff that aren't loaded in yet, same goes for other case when sometimes it might corrupt the chunk or cause nbt corruption to the block, because it tries to tick some machines that aren't loaded in yet causing error like "An expectation occurred while ticking tile entity".

### Steps to reproduce

Seems pretty random, no idea how to reproduce it. Tested on "clean" server and same stuff happened. Crash frequently occurs more on terrain with high mountains ( maybe the ore is trying to spawn in unloaded chunk ? ) And most of the corruption happens when teleporting away from stuff / while unloading terrain. 

### Server log

https://mclo.gs/YFLUh9R

**Comment by NichtStudioCode** [comment]
Not sure whether this bug specifically caused corruption of region files
