### ISSUE TITLE
Quarry Crashes the server (Terralith related issue)

### ISSUE THREAD

**Issue by Nik0-0** [xenondevs/Nova#455]
### Agreements

- [X] I am using an official build of Nova.
- [X] I am running the latest version of Nova.
- [X] I am using a [server software supported by Nova](https://docs.xen.cx/nova/admin/compatibility/#compatible-server-software)
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Check for plugin incompatibilites

Datapack issues - Custom worldgen breaks stuff

~~Not sure about this one since i can't find the cause.
I tried to check for any compatibility issues by adding plugins one by one on my other server but that works fine here
(Tested on same version - same configs)~~

After even more testing it seems like it only breaks when using datapacks that changes terrain generation in any way.

### Plugin Version, Server Software, Server Version

Nova: 0.17-alpha.16 . Purpur Version: 1.21.1-2304-dee41bc (MC: 1.21.1)

### Nova Addons and Versions

Vanilla-Hammers v1.5, SimpleUpgrades v1.4-alpha2, Logistics v0.2.9-alpha.3, Machines v0.4.6-alpha.10

### Observed/Actual behavior

~~On my main server placing Quarry will crash the whole server (similar stuff to Towny issue), but while i was searching for compatibility issue on my second test server i didn't found anything. It just worked on the same config and same plugins etc.~~

While testing on my copied / test server - the same configuration with plugins and normal world doesn't cause any issues, but when terralith or any other world generation datapack is added to the world, it no longer works.

### Steps to reproduce

1. Setup a server with custom world generation stuff
2. Place down the Quarry - Server is no mor!

### Server log

https://mclo.gs/FtL2GKC#L2067

**Comment by NichtStudioCode** [comment]
Fixed in Nova-Addons/Official-Addons@0b491762f33f52428e101d9dc52cf3438805848e

This was actually not related to world generation (unless there's another bug that I didn't find), but related to the coordinates at which the Quarry was placed

**Comment by Nik0-0** [comment]
> Fixed in Nova-Addons/Official-Addons@0b491762f33f52428e101d9dc52cf3438805848e
> 
> This was actually not related to world generation (unless there's another bug that I didn't find), but related to the coordinates at which the Quarry was placed

I mean I think it was? Since in the fresh world it worked okay until I added Terralith
