### ISSUE TITLE
[Bug] Terminal bug

### ISSUE THREAD

**Issue by BlackGrandStyle** [xenondevs/Nova#47]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of Spigot or a Spigot fork.
- [X] I have checked for similar issues.

### Plugin Version and Server Software

Nova 0.6.8, Purpur 1421, Debian 11

### Expected behavior

Commands should work without any problems

### Observed/Actual behavior

When i write in terminal the command, where you need to specify the player's nick
i get this error: 
![изображение](https://user-images.githubusercontent.com/88898883/139583465-2b685b93-19d3-467e-985b-3c46ebeab111.png)

Completely buggy terminal that i can't write any commands
it is treated only by forced closed terminal through the screen -x -s ... kill

and yes, with other plugins there is no such problem

### Steps to reproduce

1. Run server on Debian
2. Add latest Nova
3. Write /nova give and get this error

**Comment by NichtStudioCode** [comment]
The only command that can be run from the console is nvuninstall

**Comment by BlackGrandStyle** [comment]
> 
> 
> The only command that can be run from the console is nvuninstall

okay, but i dont know adout it, and nowhere was it said about it

**Comment by NichtStudioCode** [comment]
> okay, but i dont know adout it, and nowhere was it said about it
That's why I am telling you now.

That the console is locked seems to be a paper issue.

**Comment by ByteZ1337** [comment]
We'll open an issue at paper and see if they can fix it on their end. Thanks for reporting

**Comment by ByteZ1337** [comment]
Will be fixed in the next patch
