### ISSUE TITLE
Nova sets all natural leaves to `distance: 7`

### ISSUE THREAD

**Issue by zacharee** [xenondevs/Nova#483]
### Agreements

- [X] I am using an official build of Nova.
- [X] I am running the latest version of Nova.
- [X] I am using a [server software supported by Nova](https://docs.xen.cx/nova/admin/compatibility/#compatible-server-software)
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Check for plugin incompatibilites

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova: 0.17-alpha.25; PaperMC 1.21.1-128-master@d348cb8; MC 1.21.1

### Nova Addons and Versions

None

### Expected behavior

The distance on leaf natural leaf blocks shouldn't be overridden.

### Observed/Actual behavior

Tree leaf distances are all set to 7, causing some tree feller plugins to fail as they rely on the distance for determining what to cut down.

### Steps to reproduce

1. Install this tree feller plugin alongside Nova: https://github.com/ThizThizzyDizzy/tree-feller.
2. Grow a new tree.
3. Open the F3 menu and see that the `distance` property is `7` on all of its leaves.
4. Make sure the tree feller is enabled and try cutting down the tree: it won't work.

### Server log

N/A

### Additional context

I see that Nova intentionally sets leaf distance to 7, likely to use the other states for custom block models. Is there another block that could be used instead, or a way to apply custom models without using the distance attribute?

**Comment by NichtStudioCode** [comment]
> I see that Nova intentionally sets leaf distance to 7, likely to use the other states for custom block models.

This is correct

> Is there another block that could be used instead

No, leaves have unique properties such as the ability to be waterlogged and allow for transparent models.
