### ISSUE TITLE
[Request - Generic] Compatibility with Lands - Land Claim Plugin

### ISSUE THREAD

**Issue by MasterMetaphor** [xenondevs/Nova#49]
### Describe your feature request.

Compatibility with Lands - Land Claim Plugin

https://www.spigotmc.org/resources/lands-land-claim-plugin-grief-prevention-protection-gui-management-nations-wars-1-17-support.53313/

**Comment by NichtStudioCode** [comment]
I asked the Lands dev for a free copy in order to add support for his plugin and just got blocked without any prior response. I'm afraid there won't be any support for the Lands plugin - sorry!

**Comment by Angeschossen** [comment]
I just saw this now. And think this is a misunderstanding. I never blocked you. I don't have DMs open. Maybe I had them temporarily enabled to test something and forgot that we weren't friends on Discord.
