### ISSUE TITLE
Colored/Dyed Shulker Boxes don't connect with wires, while natural colored Shulker Boxes do

### ISSUE THREAD

**Issue by GuilhermeAgR** [xenondevs/Nova#490]
### Agreements

- [X] I am using an official build of Nova.
- [X] I am running the latest version of Nova.
- [X] I am using a [server software supported by Nova](https://docs.xen.cx/nova/admin/compatibility/#compatible-server-software)
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Check for plugin incompatibilites

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova: 0.17-alpha.24; Paper: 1.21.1-119-master@7cd4f2c; MC: 1.21.1

### Nova Addons and Versions

Machines v0.4.6-alpha.12

### Expected behavior

Since regular colored Shulker Boxes connect with wires and are able to transfer items, named Shulker Boxes and dyed Shulker Boxes should work too.

### Observed/Actual behavior

While naming a Shulker Box does not affect it capability of transfering items, dyeing a Shulker Box breaks them, making them unable to transfer items via cables.

Removing the dye via a Cauldron with Water makes the Shulker Box functional again.

### Steps to reproduce

1. Dye a Shulker Box black
2. Connect a cable to it
3. Cable won't connect
4. Remove dye
5. Connect a cable to it
6. Cable connects
![image](https://github.com/user-attachments/assets/ec2097d4-24da-4e9a-9481-b28c05607265)
![image](https://github.com/user-attachments/assets/53292f4a-d41e-4a08-b51b-020a8856e743)

### Server log

I have no access to the server log

**Comment by GabFran** [comment]
Colored shulker boxes not only don't connect to cables, but they don't seem to interact with any of Nova's inventories at all.
