### ISSUE TITLE
[Request - Generic] Add drinkable item behavior

### ISSUE THREAD

**Issue by Katalijst** [xenondevs/Nova#492]
### Describe your feature request.

Add a way to make drinkable item with a behavior that can have a onConusme overridable event.
It can be based on a custom potion with custom color and a model with predicate based on the color of the potion

**Comment by NichtStudioCode** [comment]
I think this is redundant in 1.21.3, as component changes now allow the selection of the consume animation and sound effect. I have however added a handleConsume function to ItemBehavior, which will be available in 0.18
