### ISSUE TITLE
my console is spammed when i start my server

### ISSUE THREAD

**Issue by VulcanoSoftware** [xenondevs/Nova#498]
### Agreements

- [X] I am using an official build of Nova.
- [X] I am running the latest version of Nova.
- [X] I am using a [server software supported by Nova](https://docs.xen.cx/nova/admin/compatibility/#compatible-server-software)
- [X] I am running the latest version of my server software.
- [x] I have checked for similar issues.

### Check for plugin incompatibilites

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova v0.17-alpha.26, Current Purpur Version: 1.21.1-2329-803bf62 (MC: 1.21.1)

### Nova Addons and Versions

Jetpacks-0.1.13-alpha.2, Logistics-0.2.9-alpha.3, Machines-0.4.6-alpha.12, Simple-Upgrades-1.4-alpha.2, Vanilla-Hammers-1.5-alpha.1

### Expected behavior

the console was spammed by nova
[latest (1).log](https://github.com/user-attachments/files/17643905/latest.1.log)

### Observed/Actual behavior

the console was spammed by nova
[latest (1).log](https://github.com/user-attachments/files/17643905/latest.1.log)

### Steps to reproduce

1. server started

### Server log

[latest (1).log](https://github.com/user-attachments/files/17643916/latest.1.log)

**Comment by VulcanoSoftware** [comment]
i updated nova to the latest version and this issue still isn't solved

**Comment by NichtStudioCode** [comment]
Hence why the issue is still open
