### ISSUE TITLE
[Bug] Power Cell Dupe

### ISSUE THREAD

**Issue by BlackGrandStyle** [xenondevs/Nova#50]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of Spigot or a Spigot fork.
- [X] I have checked for similar issues.

### Plugin Version and Server Software

Nova 0.6.10 Purpur 1423

### Observed/Actual behavior

Player found this bug, craft extremely many cells and drop server economy on auction

### Expected behavior

A serious dupe, which of course is less serious than the previous one, but also has a lot of weight and must be urgently fixed

### Steps to reproduce

1. Get all need items for Advanced Power Cell
2. Try to craft him in workbench
3. Get full inventory of Cells

### Additional context

https://pastebin.com/RuRujBvs

**Comment by NichtStudioCode** [comment]
Thank you for reporting this, but I can't seem to reproduce this bug. Crafting an Advanced Power Cell works fine for me. 
![](https://i.imgur.com/ehuwDbk.gif)
Are you doing anything different?
What other plugins are running on your server? Does this bug also occur without any other plugins present?
Also, the thread dump you attached suggests that the server lagged / crashed, what exactly happened there and when does that occur?

**Comment by BlackGrandStyle** [comment]
>  Are you doing anything different?
They click with SHIFT

> What other plugins are running on your server?
https://imgur.com/a/kLzuhOU

> Does this bug also occur without any other plugins present?
Noup, but TPS drops to 18-17 when player craft many Nova items

> Also, the thread dump you attached suggests that the server lagged / crashed,
Lagged to 10 TPS

> there and when does that occur?
When player craft a power cell in workbench

**Comment by NichtStudioCode** [comment]
> Noup

Can you try and find out which plugin is causing the dupe issue? It's probably a plugin that has custom crafting recipes / modifies crafting behavior.

> but TPS drops to 18-17 when player craft many Nova items

That is probably caused by Minecraft's crafting logic, which recalculates the output item 9 times for every item crafted (64*9 = 576 times!).
I'll implement a system that caches this result to hopefully improve performance.

**Comment by BlackGrandStyle** [comment]
> Can you try and find out which plugin is causing the dupe issue? It's probably a plugin that has custom crafting recipes / modifies crafting behavior.

Only ItemsAdder add new crafts


This bug fixed after an emergency restart of the server
but i don't know when he might appear again

**Comment by NichtStudioCode** [comment]
Okay, please open a new issue if you find the plugin that causes this problem.
