### ISSUE TITLE
[Machines] Breeder consumes items when animals are in breeding cooldown

### ISSUE THREAD

**Issue by GabFran** [xenondevs/Nova#504]
### Agreements

- [X] I am using an official build of Nova.
- [X] I am running the latest version of Nova.
- [X] I am using a [server software supported by Nova](https://docs.xen.cx/nova/admin/compatibility/#compatible-server-software)
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Check for plugin incompatibilites

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova: 0.17-alpha.28; Paper: 1.21.1-119-master@7cd4f2c; MC: 1.21.1

### Nova Addons and Versions

Simple-Upgrades v1.4-alpha.2, Machines v0.4.6-alpha.12, Logistics v0.2.9-alpha.5

### Expected behavior

When a breeder finds animals which are in breeding cooldown, it should not consume items.

### Observed/Actual behavior

When a breeder finds animals in breeding cooldown, it force feeds these animals, essentially deleting items.
Edit 1: When there are no animals in range, it still consumes one item.
Edit 2: I am not sure if it is consuming items to feed babies, if it is, then they don't show any particles. Either way, I suppose this is not intended behaviour, as it is a breeder, and not a baby grower :)

### Steps to reproduce

1. Place two or more animals inside the working area of a breeder.
2. Place the appropriate breeding item for the animal (e.g. wheat for cows)
3. Watch as the breeder first properly feeds the animals not in breeding cooldown.
4. After all animals have been fed and are in breeding cooldown, watch the breeder deleting the remaning items as it force feeds animals.

### Server log

https://pastebin.com/4DGZHVVm

**Comment by NichtStudioCode** [comment]
Yeah it was feeding babies. Fixed & added a config option to revert to the previous behavior.
