### ISSUE TITLE
[Bug] MultiModel is closed

### ISSUE THREAD

**Issue by BlackGrandStyle** [xenondevs/Nova#51]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of Spigot or a Spigot fork.
- [X] I have checked for similar issues.

### Other plugins

This bug also occurs when no other plugins are present.

### Plugin Version, Server Software, Server Version

Nova 0.6.10 / Purpur 1423

### Observed/Actual behavior

A huge log full of WARNs and an absolutely inaccessible terminal, + TPS drops

### Steps to reproduce

1. Place and setup the Chunk Loader on the Nether
2. Place and setup the Quarry in range work Chunk Loader
3. Leave from Nether

### Errors

https://pastebin.com/PaYGfCgX

**Comment by NichtStudioCode** [comment]
I am unable to reproduce this issue.
