### ISSUE TITLE
[Bug] Mob Dublicators dont work

### ISSUE THREAD

**Issue by BlackGrandStyle** [xenondevs/Nova#52]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of Spigot or a Spigot fork.
- [X] I have checked for similar issues.

### Other plugins

This bug also occurs when no other plugins are present.

### Plugin Version, Server Software, Server Version

Nova 0.6.11 / Purpur 1415

### Observed/Actual behavior

after upgrading to a Nova 0.6.11, the Mod Dublicators that were installed on earlier versions stopped working

### Steps to reproduce

1. Upgrade to new Nova version with older Mob Dublicators

### Errors

When player click on the Dublicator:
https://pastebin.com/K3pvN0t6

After server start:
https://pastebin.com/La7uLx7F

**Comment by NichtStudioCode** [comment]
Can you send me your `config.json` file from `plugins/Nova/config/`?

**Comment by BlackGrandStyle** [comment]
here this
https://pastebin.com/07tHSsEq

**Comment by NichtStudioCode** [comment]
You spelled `RAVAGER` wrong, changing that should fix your issue.
