### ISSUE TITLE
[Bug] Server crash after adding a second chest to an already filtered chest

### ISSUE THREAD

**Issue by sarhatabaot** [xenondevs/Nova#54]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of Spigot or a Spigot fork.
- [X] I have checked for similar issues.

### Other plugins

This bug also occurs when no other plugins are present.

### Plugin Version, Server Software, Server Version

Nova 0.6.11, Purpur version git-Purpur-1415 (MC: 1.17.1)

### Expected behavior

No crash.

### Observed/Actual behavior

Server crash after adding a 2nd chest to create a double chest.

This chest was already connected to 2 machines, 1 harvester, and 1 planter.

### Steps to reproduce

1. Place a planter and a harvester.
2. Connect a chest to the output of a harvester & to the input of a planter.
3. Add another chest to create a double chest. Making 2 connections to the cable.
4. If it doesn't crash there, break the chest you just added.

### Errors

https://pastebin.com/1DigAev8

**Comment by NichtStudioCode** [comment]
Can you send me a screenshot or video of your setup?
Also, you're running an outdated version of Purpur, please update.

**Comment by sarhatabaot** [comment]
Whoops, will do!
