### ISSUE TITLE
[Bug] Taking off Jetpack kicks player

### ISSUE THREAD

**Issue by sarhatabaot** [xenondevs/Nova#55]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Other plugins

This bug also occurs when no other plugins are present.

### Plugin Version, Server Software, Server Version

Nova 0.6.11, Purpur version git-Purpur-1423 

### Expected behavior

Taking off jetpack puts it back in inventory.

### Observed/Actual behavior

Player gets disconnected from server.
See https://puu.sh/Io0rI/a72e011a3c.gif

### Steps to reproduce

1. Equip jetpack
2. Try to take it off

### Errors

https://puu.sh/Io0nr/aec5fce39b.png

`sarhatabaot lost connection: Internal Exception: java.lang.IllegalArgumentException: Could not convert to Component: []`

**Comment by NichtStudioCode** [comment]
Already fixed that, just not released yet.
Thanks for reporting though!
