### ISSUE TITLE
[Request - Generic] Oraxen compatibility

### ISSUE THREAD

**Issue by BookWyrm114** [xenondevs/Nova#56]
### Describe your feature request.

Nova could expand upon the oraxen API, allowing for people to easily add Nova's energy system and make functional GUI's using Oraxen with nova. This would allow for practically infinite customization of Nova, with the ability to add new blocks, items, etc. using all of nova and oraxen's features Nova could also generate it's resource pack inside Oraxen's pack folder when Oraxen is present

**Comment by ByteZ1337** [comment]
We don't use noteblocks for custom blocks.

**Comment by BookWyrm114** [comment]
Oh, do you use mushroom blocks then?

**Comment by ByteZ1337** [comment]
We use ArmorStands. Oraxen should be compatible as long as no conflicts arise in the item model files.

**Comment by BookWyrm114** [comment]
That's great! though I did add some more to the original suggestion that still applies, I'll just edit out the part about noteblocks, thanks!

**Comment by NichtStudioCode** [comment]
We currently do not have any plans to give server admins the ability to create their own Nova blocks. Compatibility with Oraxen like you're suggesting would probably be even more work than doing the whole system ourselves. If you feel like Nova is missing a machine, you can submit your ideas here on GitHub.
