### ISSUE TITLE
[Request - Generic] Add command to check the item СustomModelData

### ISSUE THREAD

**Issue by BlackGrandStyle** [xenondevs/Nova#57]
### Describe your feature request.

it would be cool if there was a command to check the CustomModelData of the item
similar is in itemsadder, it is extremely useful when creating a gooie in the first place in which i want to display a unique item/block

![изображение](https://user-images.githubusercontent.com/88898883/140994330-a3836e51-fd10-4ca6-9eda-0a7b6c6d5dc7.png)

**Comment by NichtStudioCode** [comment]
You can print out the NBT data of an item in your hand with `/data get entity @s SelectedItem`.
What do you mean with "gooie"? It's not a word.

**Comment by BlackGrandStyle** [comment]
it's just a matter of user friendliness

**Comment by sarhatabaot** [comment]
He probably means GUI
