### ISSUE TITLE
Autofisher causing console spam [Bug] 

### ISSUE THREAD

**Issue by IlPachi** [xenondevs/Nova#58]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Other plugins

This bug also occurs when no other plugins are present.

### Plugin Version, Server Software, Server Version

Nova 0.6.12, CraftBukkit version 3172-Spigot-610a8c0-99561c2 (MC: 1.17.1)

### Observed/Actual behavior

Error messages appearing in console regularly every few seconds.

### Steps to reproduce

1. Place for the first time in this world nine autofishers.
2. The console started spamming errors.

### Errors

https://pastebin.com/vwjxtCwc

**Comment by NichtStudioCode** [comment]
The latest spigot version is `3277`, not `3172`. You're running over 100 versions behind.
