### ISSUE TITLE
[Bug] Pulverizer doesn't remove items when outputting to hopper

### ISSUE THREAD

**Issue by JugefB28** [xenondevs/Nova#59]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Other plugins

This bug also occurs when no other plugins are present.

### Plugin Version, Server Software, Server Version

Nova 0.6.12, Paper: git-Paper-384 1.17.1

### Observed/Actual behavior

When we put a hopper under the pulverizer to get it into something the iron dust stay there and it put infinite iron dust in the hopper ( sorry if not precise enough )

### Steps to reproduce

Place a pulverizer and a hopper under it that goes into a chest 

### Additional context

also does it with gold ***

**Comment by NichtStudioCode** [comment]
The ``Plugin Version, Server Software, Server Version`` field is not filled out correctly.

You also probably just didn't configure the pulverizer to output items at the bottom.

**Comment by ByteZ1337** [comment]
Edited to include needed information
