### ISSUE TITLE
Advanced power cell [Bug] 

### ISSUE THREAD

**Issue by JugefB28** [xenondevs/Nova#60]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Other plugins

This bug also occurs when no other plugins are present.

### Plugin Version, Server Software, Server Version

the last version of the plugin , its on my own pc with papermc to create it and its in 1.17.1

### Expected behavior

give me an advanced power cell when i craft one

### Observed/Actual behavior

I can't get the advanced power cell it always go back to the crafting table

### Steps to reproduce

put everything needed in the craftiong table and try to pick it up

**Comment by NichtStudioCode** [comment]
The ``Plugin Version, Server Software, Server Version`` field is not filled out correctly.
