### ISSUE TITLE
[Request - Block] Redstone Cutoff blocks

### ISSUE THREAD

**Issue by NeverPie** [xenondevs/Nova#62]
### Potential name of the block

Redstone Energy or Item cutoff valve

### Describe the block

Should just be a block that works as a wire in terms of transferring energy but when the block receives a redstone signal (like a toggled switch) it stops the flow of energy in both directions.

I think it would make sense to make a similar black that does the same thing but with items, but I'm .ore concerned with the energy idea.

I think redstone should be in the name this way it's a little more intuitive and you guys don't get bombarded with questions of how it works like with the whole star dust questioning.

### Additional context

I would like this block so I can toggle things like the mob duplicator more easily and to reduce lag when possible.

**Comment by robbcrg** [comment]
And I am more concerned with items. One example: I currently have a large sorting complex. When I want to add or change filters it is safest to just break the input route, do the changes then add the input back in. A Redstone controlled switch would be a to easier to manage.

**Comment by NichtStudioCode** [comment]
Feature requests have been moved to [Discord](https://discord.gg/hnEknVWvUe).
