### ISSUE TITLE
[Request - Generic] Provide An API.

### ISSUE THREAD

**Issue by gwygwy233** [xenondevs/Nova#63]
### Describe your feature request.

I suggest that you can program an API for us, developers, to use.It will be mainly used to add new machines with new textures, items, crops and so on. Then we can develop our own plugins to add more thing and make minecraft more wonderful easily.Sorry for my poor English and thank you for you can read me till the end.

**Comment by ByteZ1337** [comment]
If you want to add more blocks, you can open a pull request. It's very unlikely that we'll integrate some sort of add-on system into Nova. If you are interested in contributing to Nova, you can contact us via discord: https://discord.gg/EpVMXtXB2t.
An API for other stuff is definitely coming in the future, though.
