### ISSUE TITLE
[Bug] Messages and Item names bug

### ISSUE THREAD

**Issue by Hugytor09YT** [xenondevs/Nova#64]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Other plugins

This bug also occurs when no other plugins are present.

### Plugin Version, Server Software, Server Version

1.18 PaperSpigot

### Observed/Actual behavior

None.

### Steps to reproduce

Install Nova in the server.
Get a nova item o message
![image](https://user-images.githubusercontent.com/53868414/147096359-969de2b0-624c-4d14-8969-9dc365d3ff95.png)
![image](https://user-images.githubusercontent.com/53868414/147096402-69236890-e68a-4d0c-8dcf-ac0d42360423.png)

### Errors

None.

**Comment by ByteZ1337** [comment]
You don't have the resourcepack. If you didn't get it while joining it was probably caused by another plugin trying to send their resourcepack as well.
