### ISSUE TITLE
Removing block and crafting

### ISSUE THREAD

**Issue by Truzzolo** [xenondevs/Nova#65]
### Describe your feature request.

There are some blocks and items of this faboulus modpack which i don't want to insert in my spigot server, how can i remove them, there is a way like a plugin or something like it?
This is a wonderful plugin and i don't want to remove it!
Thanks so much
Truzzolo_10

**Comment by ByteZ1337** [comment]
Just delete the recipe files and set the TileEntity limit to 0 for the unwanted blocks.

Also this isn't a place for support. Join the discord if you have more questions.
