### ISSUE TITLE
[Bug] Dupe

### ISSUE THREAD

**Issue by RAPHAEL599** [xenondevs/Nova#68]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Other plugins

This bug also occurs when no other plugins are present.

### Plugin Version, Server Software, Server Version

Nova: 0.7.7 Paper: git-Paper-132 (MC: 1.18.1)

### Observed/Actual behavior

An easy way to duplicate items using storage

### Steps to reproduce

1 Place a storage unit.
2. with at least 2 items you want to duplicate put them in the storage unit
3. With another item, place it in the first hot bar slot
4. Place the mouse pointer on the items exit and press the 1 key

### Additional context

[](https://www.youtube.com/watch?v=O-XeXZ2hvbM&ab_channel=RAPHAEL599)

**Comment by RAPHAEL599** [comment]
I forgot to put the video link:
https://www.youtube.com/watch?v=O-XeXZ2hvbM&ab_channel=RAPHAEL599

**Comment by ByteZ1337** [comment]
Thanks for reporting. Will be fixed in ``0.7.8``
