### ISSUE TITLE
[Bug]  Nova lagging too much

### ISSUE THREAD

**Issue by Nikotecnology** [xenondevs/Nova#76]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Other plugins

This bug also occurs when no other plugins are present.

### Plugin Version, Server Software, Server Version

Nova 0.7.11, Paper: 144 (MC:1 .18.1)

### Observed/Actual behavior

Nova lagging in a server with multiple machines in a chunk, the server has 20gb of ram dedicated

### Steps to reproduce

1. Place multiple machines like 20 or 30,  eletric furnaces etc..
2. put all upgrades and make smelting in all the machines

### Errors

https://pastebin.com/2Yv2Ridh

**Comment by ByteZ1337** [comment]
> Nova 0.7.9, Paper: 114 (MC:1 .18.1)

Don't copy and paste your server and nova version from another issue. Please update your issue with the actual versions.

**Comment by Nikotecnology** [comment]
Done

**Comment by ByteZ1337** [comment]
![unknown](https://user-images.githubusercontent.com/42820438/148779383-767ab449-70d4-414b-befb-e69c697ab79d.png)
...
Can't reproduce on both versions.
