### ISSUE TITLE
[Bug] Silverfish can enter tile-entities

### ISSUE THREAD

**Issue by MrJorman** [xenondevs/Nova#78]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Other plugins

This bug also occurs when no other plugins are present.

### Plugin Version, Server Software, Server Version

0.7.11

### Observed/Actual behavior

Silverfish can enter tile-entities that have cobblestone as their hitbox.

### Steps to reproduce

1. Place any tile-entity
2. Spawn a silverfish
3. Wait for the silverfish to enter and break the tile-entity

**Comment by ByteZ1337** [comment]
Fixed in 0.7.12
