### ISSUE TITLE
Cable without hitbox

### ISSUE THREAD

**Issue by Ielelele29** [xenondevs/Nova#8]
**Describe the bug**
If you place cables in the way showed in the screenshot there in a part that doesn't have hitbox

**To Reproduce**
1. Place cables like in the screenshot; the parts of chain need to be all in same direction like the screenshot

**Expected behavior**
I think that these cables need to have hitboxes like others.

**Errors**
There isn't any error on console.

**Screenshots**
![2021-07-08_00 57 01](https://user-images.githubusercontent.com/76882886/124838888-06f1fa80-df88-11eb-9c16-56609cf5584b.png)

**Comment by NichtStudioCode** [comment]
Not a bug, there is no block that has a hitbox like this
