### ISSUE TITLE
Nova crash

### ISSUE THREAD

**Issue by freethemice** [xenondevs/Nova#80]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Other plugins

This bug also occurs when no other plugins are present.

### Plugin Version, Server Software, Server Version

Nova 0.7.13 paper 1.18.1

### Observed/Actual behavior

This error has happened twice today, Ive tried to recreate it but can't. The error happed randomly both time when I was breaking cables attached to chest. 

### Steps to reproduce

1. Break cable next to chest

### Errors

https://pastebin.com/6fuKJShC

### Additional context

![image](https://user-images.githubusercontent.com/6777346/149249576-f67eac9e-6c80-4f38-a04d-7cff91d83c06.png)
![image](https://user-images.githubusercontent.com/6777346/149249587-10a958d1-360f-46cd-b97d-3b8b6157005b.png)

**Comment by NichtStudioCode** [comment]
Thanks for reporting, will be fixed in the next patch!
