### ISSUE TITLE
[Bug] Error building project with Nova 0.8 API and GitHub actions

### ISSUE THREAD

**Issue by steve4744** [xenondevs/Nova#81]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Other plugins

This bug also occurs when no other plugins are present.

### Plugin Version, Server Software, Server Version

Nova 0.8 API

### Expected behavior

Building project should succeed.

### Observed/Actual behavior

Build fails with error:

`Failed to collect dependencies at xyz.xenondevs.nova:Nova-API:jar:0.8: Failed to read artifact descriptor for xyz.xenondevs.nova:Nova-API:jar:0.8: Could not find artifact xyz.xenondevs.nova:Nova-Parent:pom:0.8`

### Steps to reproduce

Attempt to build project with Nova-API
```
<dependency>
        <groupId>xyz.xenondevs.nova</groupId>
        <artifactId>Nova-API</artifactId>
        <version>0.8</version>
        <scope>provided</scope>
</dependency>
```
```
<repository>
        <id>xenondevs-releases</id>
        <name>xenondevs</name>
        <url>https://repo.xenondevs.xyz/releases</url>
</repository>
```

### Errors

`Failed to collect dependencies at xyz.xenondevs.nova:Nova-API:jar:0.8: Failed to read artifact descriptor for xyz.xenondevs.nova:Nova-API:jar:0.8: Could not find artifact xyz.xenondevs.nova:Nova-Parent:pom:0.8 `

### Additional context

The error mentions "Nova-Parent" which is not present on the repo which may be the problem.

**Comment by ByteZ1337** [comment]
Thanks for reporting. We'll deploy Nova-Parent as well later today.

**Comment by ByteZ1337** [comment]
Deployed now. Let me know if it works

**Comment by steve4744** [comment]
Yes it works perfectly. Thank you.
