### ISSUE TITLE
[Request - Item] Backpacks

### ISSUE THREAD

**Issue by Kysha7** [xenondevs/Nova#82]
There is not much to explain about this, just that it is useful...

Crafting can be leather + chest // And with Tiers, first backpack leader surrounding a chest, and the next is leather surrounding the last backpack you did. Maybe with the Press, you can make a more strong leather up to tier 3

**Comment by NichtStudioCode** [comment]
Feature requests have been moved to [Discord](https://discord.gg/hnEknVWvUe).
