### ISSUE TITLE
[Request - Block] Ecological Generator // Nuclear Power Plant

### ISSUE THREAD

**Issue by Kysha7** [xenondevs/Nova#83]
An ecological generator that works with... well that... ecological things (food, drops of mobs like the zombie, etc). I know there are already several options to choose from, but a few more won't hurt. The ecological plant, can generate as much or more than the Furnace Generator, but less than the Lava Generator. Useful for those who like to make bases and dont go out, like subnautica. It does not generate any danger for the player or the environment.

  The nuclear generator, on the other hand, is dangerous both for the player (radiation = nausea, blindness, weakness, other?), and for the environment, since if it is not kept stable, it can explode (3 times the explosion of 1 electric creeper). It produces so much energy that you must wear a **_Radiation Suit_** (New item too? c:) to get close. To keep it running, it needs **_Liquid Nitrogen Cells_** to keep it cool + **_Plutonium_**(Radiation Suit to pick up this) for fuel. To feed it from a distance, it is necessary to use a special **_reinforced cable_**, since the radiation destroys the common cable.

With these generators, you can also add new items such as those mentioned and **_highlighted_**

**_Radiation Suit_** can be a leather armor with a yellow skin, like the real suits.
**_Liquid Nitrogen Cells_** you need to use Blue Ice + gunpowder to make it (A better crafting if possible)
**_Plutonium_** Emeral dust + lava in the Liquid Infuser (Again, better crafting pls u.u)
**_reinforced cable_** ultimate_cable + netherite plate into de Press (Again, same as above >.<)

**Comment by Clexus** [comment]
It looks like Slimefun

**Comment by Kysha7** [comment]
I was thinking about subnautica...

**Comment by NichtStudioCode** [comment]
Feature requests have been moved to [Discord](https://discord.gg/hnEknVWvUe).
