### ISSUE TITLE
[Request - Block] Terminal and Crafting item + Tiers

### ISSUE THREAD

**Issue by Kysha7** [xenondevs/Nova#84]
Now that there are filters, it would be great if there was also a terminal where you can see all the items (with the quantity) that you have stored and connected to the terminal. A good example would be Terminals from Applied Energetics 2 mod. (From there is the idea)
  In addition to this, an autocrafting system would continue with the theme that the plugin presents. And maybe, a disassembly table would end up completing the idea.

All this only work with energy, players need to be careful about the amount of storage they connect to the terminal or they might crash and destroy it. This could add the mechanics of different terminal tiers, better tier, more storage capacity.

**Comment by NichtStudioCode** [comment]
Feature requests have been moved to [Discord](https://discord.gg/hnEknVWvUe).
