### ISSUE TITLE
[Request - Block] Lunar Panel

### ISSUE THREAD

**Issue by Kysha7** [xenondevs/Nova#87]
### Potential name of the block

Lunar Panel

### Describe the block

Just like the Solar, but this panel work at night.

### Additional context

Generate the same amount of energy as Solar Panel

**Comment by Sheikins** [comment]
It becomes totally unrealistic, and perhaps a little too easy. I'm not too much for it.

**Comment by ByteZ1337** [comment]
I agree. We have other way to produce energy at night.
