### ISSUE TITLE
[Request - Item] Wireless Energy

### ISSUE THREAD

**Issue by Kysha7** [xenondevs/Nova#88]
### Potential name of the item

Anntenna

### Describe the item

With this item the machines receive energy without the need to be connected to the same generator. This item must receive power by cable, but transmits the same power to x blocks from it.

### Additional context

With efficiency updates, you can enlarge the radius.

**Comment by NichtStudioCode** [comment]
Feature requests have been moved to [Discord](https://discord.gg/hnEknVWvUe).
