### ISSUE TITLE
Item Filter Dupe

### ISSUE THREAD

**Issue by freethemice** [xenondevs/Nova#89]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Other plugins

This bug also occurs when no other plugins are present.

### Plugin Version, Server Software, Server Version

Nova 0.8.1, Paper 1.18.1

### Observed/Actual behavior

If you place any item, other than a item filter, in the Item filter slot when you close the GUI and reopen it. the item has turned in to a blank item filter. This lets you dupe them over and over again.

### Steps to reproduce

If you place any item, other than a item filter, in the Item filter slot when you close the GUI and reopen it. the item has turned in to a blank item filter. This lets you dupe them over and over again.

### Additional context

![image](https://user-images.githubusercontent.com/6777346/150233577-ede5646f-5746-404f-986b-30e428283689.png)
![image](https://user-images.githubusercontent.com/6777346/150233634-28effa39-3a95-439c-a717-71281d1a7323.png)

**Comment by ByteZ1337** [comment]
Already fixed. Just isn't released yet: 96d385e74ed946b9c3257fe9602742fa7a0b8861
