### ISSUE TITLE
Duping bug

### ISSUE THREAD

**Issue by Ielelele29** [xenondevs/Nova#9]
**Describe the bug**
If you break a shulker that contains something with a block breaker, in the block breaker inventory will appear the shulker, and a copy of the item of shulker

**To Reproduce**
1. Get a shulker with something inside
2. Break it with a block breaker

**Expected behavior**
The block breaker should have in his inventory only the shulker

**Errors**
There isn't any error in console

**Screenshots**
![2021-07-08_01 08 54](https://user-images.githubusercontent.com/76882886/124839619-68ff2f80-df89-11eb-9809-cd7880c436e1.png)

**Comment by NichtStudioCode** [comment]
Thanks for reporting!
