### ISSUE TITLE
[Bug] Residence compatibility

### ISSUE THREAD

**Issue by JakeQAQ** [xenondevs/Nova#90]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Other plugins

This issue is about a specific plugin incompatibility.

### Plugin Version, Server Software, Server Version

Nova：0.83，paper-1.18.1.jar:git-Paper-104 （mc：1.18.1）

### Expected behavior

It is recommended that Nova and residence5.0.1.0 plug-ins are compatible.

### Observed/Actual behavior

When Nova and residence 5.0.1.0 plug-ins are used at the same time, opening Nova's synthetic recipe panel and clicking the search button will crash the main thread of the server.

### Steps to reproduce

1 install Nova 0.83 and residence 5.0.1.0 plug-ins at the same time

2. Use the command to open Nova's synthetic recipe panel.

3. Click the search button in Nova synthetic formula panel.

4. The server main thread crashes.

**Comment by ByteZ1337** [comment]
Please send us the full crash log

**Comment by JakeQAQ** [comment]
OK, sent.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xenondevs/Nova"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月24日(星期一) 下午2:49
***@***.***&gt;;
抄送:&nbsp;"҉҉҉҉҉҉cิy  ҉҉jc҉ ***@***.******@***.***&gt;;
主题:&nbsp;Re: [xenondevs/Nova] [Bug]  (Issue #90)





 
Please send us the full crash log
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ByteZ1337** [comment]
Where?

**Comment by JakeQAQ** [comment]
Mail attachments.

**Comment by ByteZ1337** [comment]
GitHub doesn’t forward them. Please upload them somewhere. (For example Pastebin or mclo.gs)

**Comment by JakeQAQ** [comment]
纸张服务器日志 [#jUbdiFG] - mclo.gs

**Comment by NichtStudioCode** [comment]
Fixed in [InvUI/f99c1e0](https://github.com/NichtStudioCode/InvUI/commit/f99c1e0e9fb4d59f4a23ea1d3debb0be64a99990)
