### ISSUE TITLE
[Request - Block] Conveyor

### ISSUE THREAD

**Issue by Calvitrix** [xenondevs/Nova#96]
### Potential name of the block

Conveyor 

### Describe the block

The conveyor would be able to move items from one place to another, like hoppers. It would be able to move stacks of items at a time, and would be able to move items up (unlike the hopper). They would connect like redstone dust. 

### Additional context

It would require 2 iron plates, 5 iron gears, and a hopper to craft.

**Comment by ByteZ1337** [comment]
Any particular reason why you don’t just use cables? I don‘t think conveyor belts can be implemented without spawning a ton of ArmorStands and lagging out the server

**Comment by Rom4ik777** [comment]
> Any particular reason why you don’t just use cables? I don‘t think conveyor belts can be implemented without using a ton of ArmorStands and lagging out the server/client

I saw an implementation of a conveyor plugin somewhere. There worked the conveyor on ice blocks. That is, the objects themselves slid on the ice

**Comment by ByteZ1337** [comment]
Use cables. Conveyor belts can't be implemented efficiently at a large scale.
