### ISSUE TITLE
[Request - Block] Shopfront

### ISSUE THREAD

**Issue by Calvitrix** [xenondevs/Nova#97]
### Potential name of the block

Shopfront

### Describe the block

A sort of trading system that players can buy and sell things from. Like vending machines from rust, a player can set what they want for a certain item. There would be 5 slots of storage for items that are sold to the shop, and 9 slots of storage for what you are selling. It can only be accessed by the placer, or people with the permission nova.shopfront.all

### Additional context

It would require power to work.

**Comment by ByteZ1337** [comment]
Doesn't really sound like something that belongs into Nova.

**Comment by strich3** [comment]
I would love to see that block in the plugin!

**Comment by NichtStudioCode** [comment]
Feature requests have been moved to [Discord](https://discord.gg/hnEknVWvUe).
