### ISSUE TITLE
[Request - Generic] Add an option to remove the growing tree in the factory

### ISSUE THREAD

**Issue by GioPera06** [xenondevs/Nova#98]
### Describe your feature request.

Some servers like mine to make the texturepack as light as possible go to remove the models of the trees of the treefactory, but currently if they are removed from the pack the block above the missing texture remains, I ask if it is possible to implement a feature to deactivate and reactivate these trees growing from the server config

**Comment by GioPera06** [comment]
If any of the admins can remove the label: enchantment I would be very grateful

**Comment by ByteZ1337** [comment]
> If any of the admins can remove the label: enchantment I would be very grateful

I think you misread that. It says "enhancement" which is correct.

**Comment by NichtStudioCode** [comment]
Feature requests have been moved to [Discord](https://discord.gg/hnEknVWvUe).
