### ISSUE TITLE
[Bug] Mass sorting causes mass latency

### ISSUE THREAD

**Issue by freethemice** [xenondevs/Nova#99]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Other plugins

This bug also occurs when no other plugins are present.

### Plugin Version, Server Software, Server Version

Nova 0.85 paper 1.18.1

### Expected behavior

normal ping

### Observed/Actual behavior

8000 ping

### Steps to reproduce

I have a 60 storage units connect to pipes with item filters for each storage unit. The server runs fine with 20 tps, but I have very high ping, its start normal and grows higher over time up to 8000. At first I thought it was my host, and change to a different host in a new location with better specs, that didn't work. I then tried pingpath and other test, and again nothing showed up. I disabled plugins one at a time until I finally disabled nova and my ping went back to normal of about 30. I reenabled nova and started to go threw my nova network and when I broke 1 pipe that leads to my sorting, the problem went away and again ping returned to 30.

### Additional context

![image](https://user-images.githubusercontent.com/6777346/151460185-feb0bee6-7a9a-4ad3-8be3-e43ea577652b.png)
![image](https://user-images.githubusercontent.com/6777346/151460776-7dbe5037-c903-4fff-9b96-8432d2732a0b.png)
![image](https://user-images.githubusercontent.com/6777346/151460812-eb4a3eb2-cc8c-4b45-bf09-f36b65e8c109.png)
![image](https://user-images.githubusercontent.com/6777346/151460865-97441ae0-1a3e-4354-a64e-b3ae6ed35288.png)
![image](https://user-images.githubusercontent.com/6777346/151461112-93f80620-6b7e-4949-81fa-365a2abcb048.png)

**Comment by ByteZ1337** [comment]
Did you close the issue on accident or was it caused by something else?

**Comment by freethemice** [comment]
It is caused by nova, when I remove the plugin it stops, but it wasn’t the sorting. Maybe the wind turbines sending packs for the spinning? I’m not sure

**Comment by ByteZ1337** [comment]
We have a config option to disable wind turbine animations. Could you check if that improves your ping?

**Comment by freethemice** [comment]
I’ll check after work, this afternoon and let you know

**Comment by freethemice** [comment]
looks like that fix it, thanks
